import type { DetectedAnimation } from '../types/domain';

export type MotionFilter = 'all' | 'running' | 'css' | 'waapi' | 'transition' | 'inferred' | 'exact';
export type MotionOverview = { cssAnimations:number; cssTransitions:number; waapi:number; javascript:number; unknown:number; total:number };
export type PerformanceIssue = { animationId:string; severity:'info'|'warn'; message:string };

const risky = new Set(['width','height','top','left','right','bottom','margin','margin-left','margin-right','margin-top','margin-bottom','padding','padding-left','padding-right','padding-top','padding-bottom']);

export function overview(animations:DetectedAnimation[]):MotionOverview {
  return animations.reduce<MotionOverview>((out,a)=>{out.total++;if(a.type==='css-animation')out.cssAnimations++;else if(a.type==='css-transition')out.cssTransitions++;else if(a.type==='web-animation')out.waapi++;else if(a.type==='unknown')out.unknown++;else out.javascript++;return out;},{cssAnimations:0,cssTransitions:0,waapi:0,javascript:0,unknown:0,total:0});
}
export function filterAnimations(animations:DetectedAnimation[], query:string, filter:MotionFilter):DetectedAnimation[] {
  const needle=query.trim().toLowerCase();return animations.filter(a=>{const matches=filter==='all'||(filter==='running'&&a.runtimeState==='running')||(filter==='css'&&a.type==='css-animation')||(filter==='waapi'&&a.type==='web-animation')||(filter==='transition'&&a.type==='css-transition')||(filter==='inferred'&&(a.confidence==='inferred'||a.confidence==='unknown'))||(filter==='exact'&&(a.confidence==='exact'||a.confidence==='source-correlated'));if(!matches)return false;if(!needle)return true;return[a.name,a.type,a.confidence,a.source?.file,a.source?.selector,...a.properties.map(p=>p.name)].filter(Boolean).join(' ').toLowerCase().includes(needle);});
}
export function performanceIssues(animations:DetectedAnimation[]):PerformanceIssue[] {const issues:PerformanceIssue[]=[];for(const animation of animations)for(const property of animation.properties){if(risky.has(property.name))issues.push({animationId:animation.id,severity:'warn',message:`${property.name} can trigger layout; measure before optimizing.`});if(property.name==='filter')issues.push({animationId:animation.id,severity:'info',message:'filter can be GPU-expensive depending on blur radius and affected area.'});}return issues;}
export function parseBezier(value:string):[number,number,number,number]|undefined {const m=value.trim().match(/^cubic-bezier\(\s*(-?[\d.]+)\s*,\s*(-?[\d.]+)\s*,\s*(-?[\d.]+)\s*,\s*(-?[\d.]+)\s*\)$/i);if(!m)return undefined;return[Number(m[1]),Number(m[2]),Number(m[3]),Number(m[4])];}
export function bezierPath(points:[number,number,number,number]):string {const[x1,y1,x2,y2]=points,x=(v:number)=>10+v*140,y=(v:number)=>150-v*140;return`M 10 150 C ${x(x1)} ${y(y1)}, ${x(x2)} ${y(y2)}, 150 10`;}
export type TransformParts={translateX:number;translateY:number;scaleX:number;scaleY:number;rotate:number;skewX:number;skewY:number};
export function defaultTransform():TransformParts{return{translateX:0,translateY:0,scaleX:1,scaleY:1,rotate:0,skewX:0,skewY:0};}
export function parseTransform(value:string|undefined):TransformParts {const out=defaultTransform();if(!value||value==='none')return out;const read=(name:string)=>value.match(new RegExp(`${name}\\(([^)]+)\\)`,'i'))?.[1]?.trim(),finite=(input:string|undefined,fallback:number)=>{const parsed=input===undefined?NaN:parseFloat(input);return Number.isFinite(parsed)?parsed:fallback;};const tx=read('translateX'),ty=read('translateY'),scale=read('scale'),sx=read('scaleX'),sy=read('scaleY'),rotate=read('rotate'),skewX=read('skewX'),skewY=read('skewY');if(tx)out.translateX=finite(tx,0);if(ty)out.translateY=finite(ty,0);if(scale){const n=parseFloat(scale);if(Number.isFinite(n)){out.scaleX=n;out.scaleY=n;}}if(sx)out.scaleX=finite(sx,1);if(sy)out.scaleY=finite(sy,1);if(rotate)out.rotate=finite(rotate,0);if(skewX)out.skewX=finite(skewX,0);if(skewY)out.skewY=finite(skewY,0);return out;}
export function buildTransform(p:TransformParts):string{return`translateX(${p.translateX}px) translateY(${p.translateY}px) scaleX(${p.scaleX}) scaleY(${p.scaleY}) rotate(${p.rotate}deg) skewX(${p.skewX}deg) skewY(${p.skewY}deg)`;}
export function normalizedKeyframes(animation:DetectedAnimation):Array<Record<string,string|number|null>> {const frames=animation.keyframes?.map(frame=>({...frame}))??[{offset:0,opacity:0},{offset:1,opacity:1}],count=Math.max(1,frames.length-1);return frames.map((frame,index)=>({offset:typeof frame.offset==='number'?frame.offset:index/count,...frame}));}
export function updateKeyframe(frames:Array<Record<string,string|number|null>>,index:number,key:string,value:string|number|null):Array<Record<string,string|number|null>> {return frames.map((frame,i)=>i===index?{...frame,[key]:value}:frame);}
export function addKeyframe(frames:Array<Record<string,string|number|null>>):Array<Record<string,string|number|null>> {const copy=frames.map(f=>({...f})),last=copy.at(-1)??{opacity:1,offset:1};copy.splice(Math.max(1,copy.length-1),0,{...last,offset:.5});return copy.sort((a,b)=>Number(a.offset??0)-Number(b.offset??0));}
export function duplicateKeyframe(frames:Array<Record<string,string|number|null>>,index:number):Array<Record<string,string|number|null>> {const copy=frames.map(f=>({...f})),base=copy[index];if(!base)return copy;const previous=copy[index-1],next=copy[index+1],baseOffset=Number(base.offset??(copy.length<=1?0:index/(copy.length-1)));const offset=next?(baseOffset+Number(next.offset??1))/2:previous?(Number(previous.offset??0)+baseOffset)/2:baseOffset;copy.splice(index+1,0,{...base,offset});return copy;}
export function deleteKeyframe(frames:Array<Record<string,string|number|null>>,index:number):Array<Record<string,string|number|null>> {return frames.length<=2?frames:frames.filter((_,i)=>i!==index);}
