import type {MotionKeyframe,MotionTrack,MotionValue} from './motion-model';

export function normalizedMotionKeyframes(track:MotionTrack):MotionKeyframe[]{const frames=track.keyframes.length?track.keyframes.map(frame=>cloneFrame(frame)):[{offset:0,values:{opacity:0}},{offset:1,values:{opacity:1}}],count=Math.max(1,frames.length-1);return frames.map((frame,index)=>({...frame,offset:typeof frame.offset==='number'?frame.offset:index/count}));}
export function updateMotionKeyframe(frames:MotionKeyframe[],index:number,key:string,value:MotionValue):MotionKeyframe[]{return frames.map((frame,i)=>{if(i!==index)return frame;if(key==='offset'&&typeof value==='number')return{...frame,offset:clamp01(value)};if(key==='easing'&&typeof value==='string')return{...frame,easing:value};if(key==='composite'&&typeof value==='string')return{...frame,composite:value};return{...frame,values:{...frame.values,[key]:value}};});}
export function addMotionKeyframe(frames:MotionKeyframe[]):MotionKeyframe[]{const copy=frames.map(cloneFrame),last=copy.at(-1)??{offset:1,values:{opacity:1}},before=copy.at(-2),end=Number(last.offset??1),start=Number(before?.offset??0),offset=(start+end)/2;copy.splice(Math.max(1,copy.length-1),0,{...last,values:{...last.values},offset});return sortFrames(copy);}
export function duplicateMotionKeyframe(frames:MotionKeyframe[],index:number):MotionKeyframe[]{const copy=frames.map(cloneFrame),base=copy[index];if(!base)return copy;const previous=copy[index-1],next=copy[index+1],baseOffset=Number(base.offset??(copy.length<=1?0:index/(copy.length-1))),offset=next?(baseOffset+Number(next.offset??1))/2:previous?(Number(previous.offset??0)+baseOffset)/2:baseOffset;copy.splice(index+1,0,{...base,values:{...base.values},offset:clamp01(offset)});return sortFrames(copy);}
export function deleteMotionKeyframe(frames:MotionKeyframe[],index:number):MotionKeyframe[]{return frames.length<=2?frames:frames.filter((_,i)=>i!==index).map(cloneFrame);}
export function addMotionProperty(frames:MotionKeyframe[],name:string):MotionKeyframe[]{return frames.map(frame=>({...frame,values:{...frame.values,[name]:frame.values[name]??''}}));}
export function moveMotionKeyframe(frames:MotionKeyframe[],index:number,offset:number):MotionKeyframe[]{return sortFrames(updateMotionKeyframe(frames,index,'offset',clamp01(offset)));}
export function cloneMotionKeyframes(frames:MotionKeyframe[]):MotionKeyframe[]{return frames.map(cloneFrame);}
function cloneFrame(frame:MotionKeyframe):MotionKeyframe{return{...frame,values:{...frame.values}};}
function sortFrames(frames:MotionKeyframe[]):MotionKeyframe[]{return frames.sort((a,b)=>Number(a.offset??0)-Number(b.offset??0));}
function clamp01(value:number):number{return Math.max(0,Math.min(1,Number.isFinite(value)?value:0));}
