import type {AnimationType,DetectedAnimation} from '../../types/domain';
import type {MotionKeyframe,MotionPropertyTrack,MotionSourceKind,MotionTrack,MotionValueKind} from './motion-model';

const sourceKind=(type:AnimationType):MotionSourceKind=>{switch(type){case'css-animation':return'css-animation';case'css-transition':return'css-transition';case'web-animation':return'waapi';case'javascript':return'javascript';case'raf':return'raf';case'runtime-style':return'runtime-style';case'gsap':return'gsap';case'framer-motion':return'framer-motion';case'scroll-timeline':return'scroll-timeline';case'svg':return'svg';case'canvas':return'canvas';default:return'unknown';}};
const legacyType=(track:MotionTrack):AnimationType=>{const stored=track.metadata?.legacyType;if(isAnimationType(stored))return stored;switch(track.source.kind){case'css-animation':return'css-animation';case'css-transition':return'css-transition';case'waapi':return'web-animation';case'javascript':return'javascript';case'raf':return'raf';case'runtime-style':return'runtime-style';case'gsap':return'gsap';case'framer-motion':return'framer-motion';case'scroll-timeline':return'scroll-timeline';case'svg':return'svg';case'canvas':return'canvas';default:return'unknown';}};
const isAnimationType=(value:unknown):value is AnimationType=>value==='css-animation'||value==='css-transition'||value==='web-animation'||value==='javascript'||value==='raf'||value==='runtime-style'||value==='gsap'||value==='framer-motion'||value==='scroll-timeline'||value==='svg'||value==='canvas'||value==='unknown';
const valueKind=(name:string):MotionValueKind=>{const key=name.toLowerCase();if(key==='transform')return'transform';if(key==='filter'||key==='backdrop-filter')return'filter';if(key.startsWith('--'))return'custom-property';if(key.includes('color')||key==='fill'||key==='stroke')return'color';if(key==='d'||key==='offset-path'||key==='clip-path')return'path';if(key.includes('rotate')||key.includes('skew'))return'angle';if(['width','height','top','right','bottom','left','margin','padding','gap','translate','translatex','translatey','perspective','border-radius','font-size','letter-spacing'].some(token=>key===token||key.startsWith(`${token}-`)))return'length';if(['opacity','scale','scalex','scaley','z-index','flex-grow','flex-shrink','order'].includes(key))return'number';if(['display','visibility','position','overflow','pointer-events','font-family'].includes(key))return'discrete';return'unknown';};
const isInterpolable=(kind:MotionValueKind):boolean|undefined=>kind==='discrete'?false:kind==='number'||kind==='length'||kind==='angle'||kind==='color'||kind==='transform'||kind==='filter'||kind==='path'||kind==='custom-property'?true:undefined;
const normalizeProperties=(properties:DetectedAnimation['properties']):MotionPropertyTrack[]=>properties.map(property=>{const kind=valueKind(property.name),interpolable=isInterpolable(kind);return{name:property.name,...(property.from!==undefined?{from:property.from}:{}),...(property.to!==undefined?{to:property.to}:{}),...(property.values!==undefined?{values:[...property.values]}:{}),valueKind:kind,...(interpolable!==undefined?{interpolable}:{})};});
const normalizeKeyframes=(frames:DetectedAnimation['keyframes']):MotionKeyframe[]=>frames?.map(frame=>{const values:Record<string,string|number|null>={};let offset:number|undefined,easing:string|undefined,composite:string|undefined;for(const[key,value]of Object.entries(frame)){if(key==='offset'&&typeof value==='number'){offset=value;continue;}if(key==='easing'&&typeof value==='string'){easing=value;continue;}if(key==='composite'&&typeof value==='string'){composite=value;continue;}values[key]=value;}return{values,...(offset!==undefined?{offset}:{}),...(easing?{easing}:{}),...(composite?{composite}:{})};})??[];
const denormalizeKeyframes=(frames:MotionKeyframe[]):DetectedAnimation['keyframes']=>frames.length?frames.map(frame=>({...frame.values,...(frame.offset!==undefined?{offset:frame.offset}:{}),...(frame.easing?{easing:frame.easing}:{}),...(frame.composite?{composite:frame.composite}:{})})):undefined;

export function detectedAnimationToMotionTrack(animation:DetectedAnimation):MotionTrack{return{id:animation.id,...(animation.name?{name:animation.name}:{}),target:{elementId:animation.elementId,...(animation.source?.selector?{selector:animation.source.selector}:{})},timing:{start:animation.startTime,...(animation.duration!==undefined?{duration:animation.duration}:{}),...(animation.delay!==undefined?{delay:animation.delay}:{}),...(animation.iterations!==undefined?{iterations:animation.iterations}:{}),...(animation.direction?{direction:animation.direction}:{}),...(animation.easing?{easing:animation.easing}:{}),...(animation.fill?{fill:animation.fill}:{})},properties:normalizeProperties(animation.properties),keyframes:normalizeKeyframes(animation.keyframes),trigger:triggerFor(animation),source:{kind:sourceKind(animation.type),...(animation.source?{reference:animation.source}:{}),confidence:animation.confidence},runtimeState:animation.runtimeState,metadata:{legacyType:animation.type}};}
export function motionTrackToDetectedAnimation(track:MotionTrack):DetectedAnimation{return{id:track.id,elementId:track.target.elementId,type:legacyType(track),...(track.name?{name:track.name}:{}),startTime:track.timing.start,...(track.timing.duration!==undefined?{duration:track.timing.duration}:{}),...(track.timing.delay!==undefined?{delay:track.timing.delay}:{}),...(track.timing.iterations!==undefined?{iterations:track.timing.iterations}:{}),...(track.timing.direction?{direction:track.timing.direction}:{}),...(track.timing.easing?{easing:track.timing.easing}:{}),...(track.timing.fill?{fill:track.timing.fill}:{}),properties:track.properties.map(property=>({name:property.name,...(property.from!==undefined?{from:property.from}:{}),...(property.to!==undefined?{to:property.to}:{}),...(property.values?{values:[...property.values]}:{})})),...(track.source.reference?{source:track.source.reference}:{}),confidence:track.source.confidence,runtimeState:track.runtimeState,...(track.keyframes.length?{keyframes:denormalizeKeyframes(track.keyframes)}:{})};}
export const detectedAnimationsToMotionTracks=(animations:DetectedAnimation[]):MotionTrack[]=>animations.map(detectedAnimationToMotionTrack);
export const motionTracksToDetectedAnimations=(tracks:MotionTrack[]):DetectedAnimation[]=>tracks.map(motionTrackToDetectedAnimation);
function triggerFor(animation:DetectedAnimation):MotionTrack['trigger']{if(animation.type==='scroll-timeline')return{kind:'scroll-progress',source:'scroll-timeline'};return{kind:'unknown'};}
