import type { MotionTrack } from './motion-model';

export type MotionFilter='all'|'running'|'css'|'waapi'|'transition'|'inferred'|'exact';
export type MotionOverview={cssAnimations:number;cssTransitions:number;waapi:number;javascript:number;unknown:number;total:number};
export type MotionPerformanceIssue={trackId:string;severity:'info'|'warn';message:string};
const risky=new Set(['width','height','top','left','right','bottom','margin','margin-left','margin-right','margin-top','margin-bottom','padding','padding-left','padding-right','padding-top','padding-bottom']);

export function overviewMotionTracks(tracks:MotionTrack[]):MotionOverview{return tracks.reduce<MotionOverview>((out,track)=>{out.total++;if(track.source.kind==='css-animation')out.cssAnimations++;else if(track.source.kind==='css-transition')out.cssTransitions++;else if(track.source.kind==='waapi')out.waapi++;else if(track.source.kind==='unknown')out.unknown++;else out.javascript++;return out;},{cssAnimations:0,cssTransitions:0,waapi:0,javascript:0,unknown:0,total:0});}
export function filterMotionTracks(tracks:MotionTrack[],query:string,filter:MotionFilter):MotionTrack[]{const needle=query.trim().toLowerCase();return tracks.filter(track=>{const confidence=track.source.confidence,kind=track.source.kind,matches=filter==='all'||(filter==='running'&&track.runtimeState==='running')||(filter==='css'&&kind==='css-animation')||(filter==='waapi'&&kind==='waapi')||(filter==='transition'&&kind==='css-transition')||(filter==='inferred'&&(confidence==='inferred'||confidence==='unknown'))||(filter==='exact'&&(confidence==='exact'||confidence==='source-correlated'));if(!matches)return false;if(!needle)return true;const reference=track.source.reference;return[track.name,kind,confidence,reference?.file,reference?.selector,...track.properties.map(property=>property.name)].filter(Boolean).join(' ').toLowerCase().includes(needle);});}
export function motionPerformanceIssues(tracks:MotionTrack[]):MotionPerformanceIssue[]{const issues:MotionPerformanceIssue[]=[];for(const track of tracks)for(const property of track.properties){if(risky.has(property.name))issues.push({trackId:track.id,severity:'warn',message:`${property.name} can trigger layout; measure before optimizing.`});if(property.name==='filter')issues.push({trackId:track.id,severity:'info',message:'filter can be GPU-expensive depending on blur radius and affected area.'});}return issues;}
