import fs from 'node:fs';
import path from 'node:path';
import postcss,{type AtRule,type Declaration,type Root,type Rule} from 'postcss';
import type {AnimationType,DetectedAnimation} from '../src/types/domain.js';
import {detectedAnimationsToMotionTracks} from '../src/core/motion/normalize.js';
import type {MotionTrack} from '../src/types/motion.js';
import {detectSourceMotion,type SourceDetectedAnimation} from './motion-source-detectors.js';
import type {LoadedProject} from './project.js';

interface SourceRef{file:string;line?:number;column?:number;selector?:string;snippet?:string;media?:string;}
interface StaticTransition{selector:string;properties:string[];source:SourceRef;}
interface StaticCandidate{kind:string;file:string;line:number;column?:number;functionName?:string;snippet:string;}
interface AncestorNode{type:string;name?:string;params?:string;parent?:unknown;}
export interface AnalysisResult{animations:DetectedAnimation[];motionTracks:MotionTrack[];transitions:StaticTransition[];candidates:StaticCandidate[];reducedMotion:boolean;}
type ParsedCss={file:string;rel:string;root:Root};
type KeyframeRef={file:string;node:AtRule};
type AnimationSpec={name?:string;duration?:number;delay?:number;easing?:string;iterations?:number;direction?:string;fill?:string};

const ignored=new Set(['node_modules','.git','dist','build','coverage','.cache','server-dist','.animator']);
const directions=new Set(['normal','reverse','alternate','alternate-reverse']);
const fills=new Set(['none','forwards','backwards','both']);
const timingKeywords=new Set(['linear','ease','ease-in','ease-out','ease-in-out','step-start','step-end']);
const animationReserved=new Set(['none','infinite','running','paused',...directions,...fills,...timingKeywords]);

export function analyzeProject(project:LoadedProject):AnalysisResult{
  const animations:DetectedAnimation[]=[],transitions:StaticTransition[]=[],candidates:StaticCandidate[]=[];let reducedMotion=false;
  const files=collectFiles(project.root),css=parseCssFiles(files,project.root),keyframes=new Map<string,KeyframeRef>();
  for(const item of css)item.root.walkAtRules(at=>{if(/(?:^|-)keyframes$/i.test(at.name))keyframes.set(at.params.trim(),{file:item.rel,node:at});if(at.name.toLowerCase()==='media'&&/prefers-reduced-motion\s*:\s*reduce/i.test(at.params))reducedMotion=true;});
  for(const item of css)item.root.walkRules((rule:Rule)=>{
    if(isInsideKeyframes(rule))return;const declarations=directDeclarations(rule),animationDeclaration=findMotionDeclaration(declarations,'animation');
    if(animationDeclaration){const specs=parseAnimationSpecs(declarations,keyframes),location=animationDeclaration.source?.start,media=mediaContext(rule),timeline=declarations.get('animation-timeline')?.value,rangeStart=declarations.get('animation-range-start')?.value,rangeEnd=declarations.get('animation-range-end')?.value,type:AnimationType=timeline&&timeline.trim()!=='auto'?'scroll-timeline':'css-animation';specs.forEach((spec,index)=>{const frame=spec.name?keyframes.get(spec.name):undefined,snippet=[animationDeclaration.toString(),timeline?`animation-timeline: ${timeline}`:'',rangeStart?`animation-range-start: ${rangeStart}`:'',rangeEnd?`animation-range-end: ${rangeEnd}`:''].filter(Boolean).join('; ');animations.push({id:`css:${item.rel}:${location?.line??0}:${rule.selector}:${index}`,elementId:`static:${rule.selector}`,type,...(spec.name?{name:spec.name}:{}),startTime:0,...(spec.duration!==undefined?{duration:spec.duration}:{}),...(spec.delay!==undefined?{delay:spec.delay}:{}),...(spec.iterations!==undefined?{iterations:spec.iterations}:{}),...(spec.direction?{direction:spec.direction}:{}),...(spec.easing?{easing:spec.easing}:{}),...(spec.fill?{fill:spec.fill}:{}),properties:frame?extractKeyframeProps(frame.node):[],source:{file:item.rel,...(location?.line?{line:location.line}:{}),...(location?.column?{column:location.column}:{}),selector:rule.selector,snippet,...(media?{media}:{})},confidence:'exact',runtimeState:'idle'});});}
    const transitionDeclaration=findMotionDeclaration(declarations,'transition');if(transitionDeclaration){const location=transitionDeclaration.source?.start,media=mediaContext(rule);transitions.push({selector:rule.selector,properties:parseTransitionProperties(declarations),source:{file:item.rel,...(location?.line?{line:location.line}:{}),...(location?.column?{column:location.column}:{}),selector:rule.selector,snippet:transitionDeclaration.toString(),...(media?{media}:{})}});}
  });
  for(const file of files){if(!/\.(?:m?[jt]s|[jt]sx|svg|html?)$/i.test(file))continue;const detected=detectSourceMotion(file,project.root);animations.push(...detected.animations.map(toDetectedAnimation));candidates.push(...detected.candidates);}
  const dedupedAnimations=dedupeAnimations(animations);return{animations:dedupedAnimations,motionTracks:detectedAnimationsToMotionTracks(dedupedAnimations),transitions,candidates:dedupeCandidates(candidates),reducedMotion};
}

function toDetectedAnimation(animation:SourceDetectedAnimation):DetectedAnimation{return{id:animation.id,elementId:animation.elementId,type:animation.type,...(animation.name?{name:animation.name}:{}),startTime:animation.startTime,...(animation.duration!==undefined?{duration:animation.duration}:{}),...(animation.delay!==undefined?{delay:animation.delay}:{}),...(animation.iterations!==undefined?{iterations:animation.iterations}:{}),...(animation.direction?{direction:animation.direction}:{}),...(animation.easing?{easing:animation.easing}:{}),...(animation.fill?{fill:animation.fill}:{}),properties:animation.properties,source:animation.source,confidence:animation.confidence,runtimeState:animation.runtimeState,...(animation.keyframes?{keyframes:animation.keyframes}:{})};}
function dedupeAnimations(items:DetectedAnimation[]):DetectedAnimation[]{const seen=new Set<string>();return items.filter(item=>{const source=item.source,key=`${item.type}:${source?.file??''}:${source?.line??''}:${source?.column??''}:${item.name??item.id}`;if(seen.has(key))return false;seen.add(key);return true;});}
function dedupeCandidates(items:StaticCandidate[]):StaticCandidate[]{const seen=new Set<string>();return items.filter(item=>{const key=`${item.kind}:${item.file}:${item.line}:${item.column??0}`;if(seen.has(key))return false;seen.add(key);return true;});}
function collectFiles(root:string):string[]{const out:string[]=[];const visit=(dir:string):void=>{for(const entry of fs.readdirSync(dir,{withFileTypes:true})){if(ignored.has(entry.name))continue;const full=path.join(dir,entry.name);if(entry.isDirectory())visit(full);else out.push(full);}};visit(root);return out;}
function parseCssFiles(files:string[],root:string):ParsedCss[]{const out:ParsedCss[]=[];for(const file of files.filter(candidate=>/\.(?:css|scss)$/i.test(candidate))){const source=fs.readFileSync(file,'utf8');try{out.push({file,rel:path.relative(root,file).split(path.sep).join('/'),root:postcss.parse(source,{from:file})});}catch{}}return out;}
function directDeclarations(rule:Rule):Map<string,Declaration>{const map=new Map<string,Declaration>();for(const node of rule.nodes??[])if(node.type==='decl')map.set(node.prop.toLowerCase(),node);return map;}
function findMotionDeclaration(declarations:Map<string,Declaration>,prefix:'animation'|'transition'):Declaration|undefined{return[...declarations].find(([property])=>property===prefix||property.startsWith(`${prefix}-`))?.[1];}
function parseAnimationSpecs(declarations:Map<string,Declaration>,keyframes:Map<string,KeyframeRef>):AnimationSpec[]{const shorthand=declarations.get('animation')?.value;if(shorthand)return splitCssList(shorthand).map(part=>parseAnimationShorthand(part,keyframes));const names=cssList(declarations.get('animation-name')?.value),durations=cssList(declarations.get('animation-duration')?.value).map(toMs),delays=cssList(declarations.get('animation-delay')?.value).map(toMs),easings=cssList(declarations.get('animation-timing-function')?.value),iterations=cssList(declarations.get('animation-iteration-count')?.value).map(parseIterations),directionList=cssList(declarations.get('animation-direction')?.value),fillList=cssList(declarations.get('animation-fill-mode')?.value),count=Math.max(1,names.length,durations.length,delays.length,easings.length,iterations.length,directionList.length,fillList.length);return Array.from({length:count},(_,index)=>({...((cycle(names,index)&&cycle(names,index)!=='none')?{name:cycle(names,index)}:{}),...(cycle(durations,index)!==undefined?{duration:cycle(durations,index)}:{}),...(cycle(delays,index)!==undefined?{delay:cycle(delays,index)}:{}),...(cycle(easings,index)?{easing:cycle(easings,index)}:{}),...(cycle(iterations,index)!==undefined?{iterations:cycle(iterations,index)}:{}),...(cycle(directionList,index)?{direction:cycle(directionList,index)}:{}),...(cycle(fillList,index)?{fill:cycle(fillList,index)}:{})}));}
function parseAnimationShorthand(value:string,keyframes:Map<string,KeyframeRef>):AnimationSpec{const tokens=splitWhitespace(value),spec:AnimationSpec={};let timeCount=0;const unclassified:string[]=[];for(const token of tokens){const time=toMs(token);if(time!==undefined){if(timeCount===0)spec.duration=time;else if(timeCount===1)spec.delay=time;timeCount++;continue;}if(isTiming(token)){spec.easing=token;continue;}if(token==='infinite')continue;const iterations=parseIterations(token);if(iterations!==undefined&&/^\d/.test(token)){spec.iterations=iterations;continue;}if(directions.has(token)){spec.direction=token;continue;}if(fills.has(token)){spec.fill=token;continue;}if(token==='running'||token==='paused')continue;if(keyframes.has(token)){spec.name=token;continue;}if(!animationReserved.has(token))unclassified.push(token);}if(!spec.name&&unclassified.length)spec.name=unclassified.at(-1);return spec;}
function parseTransitionProperties(declarations:Map<string,Declaration>):string[]{const explicit=declarations.get('transition-property')?.value;if(explicit)return cssList(explicit).filter(Boolean);const shorthand=declarations.get('transition')?.value;if(!shorthand)return['all'];return splitCssList(shorthand).map(part=>{for(const token of splitWhitespace(part))if(toMs(token)===undefined&&!isTiming(token)&&!['allow-discrete','normal'].includes(token))return token;return'all';});}
function splitCssList(value:string|undefined):string[]{if(!value)return[];return splitTopLevel(value,',').map(item=>item.trim()).filter(Boolean);}
function cssList(value:string|undefined):string[]{return splitCssList(value);}
function splitWhitespace(value:string):string[]{const out:string[]=[];let current='',depth=0,quote='';const flush=()=>{if(current.trim())out.push(current.trim());current='';};for(const char of value){if(quote){current+=char;if(char===quote)quote='';continue;}if(char==='"'||char==="'"){quote=char;current+=char;continue;}if(char==='('||char==='['){depth++;current+=char;continue;}if(char===')'||char===']'){depth=Math.max(0,depth-1);current+=char;continue;}if(/\s/.test(char)&&depth===0){flush();continue;}current+=char;}flush();return out;}
function splitTopLevel(value:string,separator:string):string[]{const out:string[]=[];let current='',depth=0,quote='';for(const char of value){if(quote){current+=char;if(char===quote)quote='';continue;}if(char==='"'||char==="'"){quote=char;current+=char;continue;}if(char==='('||char==='['){depth++;current+=char;continue;}if(char===')'||char===']'){depth=Math.max(0,depth-1);current+=char;continue;}if(char===separator&&depth===0){out.push(current);current='';continue;}current+=char;}out.push(current);return out;}
function cycle<T>(values:T[],index:number):T|undefined{return values.length?values[index%values.length]:undefined;}
function toMs(value:string|undefined):number|undefined{if(!value)return undefined;const match=value.trim().match(/^(-?[\d.]+)(ms|s)$/i);if(!match)return undefined;return Number(match[1])*(match[2]?.toLowerCase()==='s'?1000:1);}
function parseIterations(value:string|undefined):number|undefined{if(!value||value==='infinite')return undefined;const n=Number(value);return Number.isFinite(n)?n:undefined;}
function isTiming(value:string):boolean{return timingKeywords.has(value)||/^(?:cubic-bezier|steps|linear)\(/i.test(value);}
function extractKeyframeProps(at:AtRule):Array<{name:string;values:string[]}>{const out=new Map<string,string[]>();at.walkDecls(declaration=>{const values=out.get(declaration.prop)??[];values.push(declaration.value);out.set(declaration.prop,values);});return[...out].map(([name,values])=>({name,values}));}
function ancestors(rule:Rule):AncestorNode[]{const out:AncestorNode[]=[];let current=rule.parent as unknown as AncestorNode|undefined;while(current){out.push(current);current=current.parent as AncestorNode|undefined;}return out;}
function isInsideKeyframes(rule:Rule):boolean{return ancestors(rule).some(parent=>parent.type==='atrule'&&typeof parent.name==='string'&&/(?:^|-)keyframes$/i.test(parent.name));}
function mediaContext(rule:Rule):string|undefined{const media=ancestors(rule).filter(parent=>parent.type==='atrule'&&parent.name?.toLowerCase()==='media'&&typeof parent.params==='string').map(parent=>parent.params as string).reverse();return media.length?media.join(' and '):undefined;}
