export const auxiliaryRuntimeSource = String.raw`(()=>{
  if(window.__ANIMATOR_AUX_RUNTIME__)return;window.__ANIMATOR_AUX_RUNTIME__=true;
  const SOURCE='animator-preview',started=performance.now(),eventQueue=[],births=[],birthSeen=new WeakSet(),savedVisibility=new WeakMap(),shadowRoots=new Set(),shadowObservers=new WeakMap();
  let lastFrame=started,lastDrop=0,lastConcurrent=0,flushTimer=0,birthCursor=0,loadEnd=0,highlight=null,recording=true,shadowSyncQueued=false;
  const post=(type,payload={})=>parent.postMessage({source:SOURCE,type,...payload},'*');
  const now=()=>Math.max(0,performance.now()-started);
  const isShadowSnapshot=el=>el instanceof Element&&el.hasAttribute('data-animator-shadow-snapshot');
  const isInternal=el=>el instanceof Element&&(isShadowSnapshot(el)||el.hasAttribute('data-animator-internal')||el.hasAttribute('data-animator-focus-overlay')||el.hasAttribute('data-animator-magnify-host')||el.hasAttribute('data-animator-magnify-lens')||el.hasAttribute('data-animator-magnify-clone')||el.hasAttribute('data-animator-selection-highlight')||el.hasAttribute('data-animator-dom-highlight')||el.hasAttribute('data-animator-picker-outline')||el.hasAttribute('data-animator-reduced-motion'));
  const flush=()=>{flushTimer=0;if(!eventQueue.length)return;post('EVENTS',{events:eventQueue.splice(0,eventQueue.length)});};
  const event=(kind,label,data={},at=now())=>{if(!recording)return;eventQueue.push({id:'ev-'+Math.random().toString(36).slice(2),at:Math.max(0,at),kind,label,data});if(!flushTimer)flushTimer=setTimeout(flush,16);};
  const escapePart=value=>{try{return CSS.escape(String(value));}catch{return String(value).replace(/[^a-zA-Z0-9_-]/g,'\\$&');}};
  const selectorFor=el=>{if(!(el instanceof Element))return'';if(el.id)return'#'+escapePart(el.id);const parts=[];let node=el;while(node instanceof Element&&node!==document.documentElement){let part=node.tagName.toLowerCase();const parent=node.parentElement;if(parent){const same=[...parent.children].filter(child=>child.tagName===node.tagName);if(same.length>1)part+=':nth-of-type('+(same.indexOf(node)+1)+')';}parts.unshift(part);node=parent;if(parts.length>=8)break;}return parts.join(' > ');};
  const depthOf=el=>{let depth=0,node=el.parentElement;while(node&&node!==document.documentElement){depth++;node=node.parentElement;}return depth;};
  const shadowCss=root=>{const chunks=[];try{for(const sheet of root.adoptedStyleSheets||[]){try{chunks.push([...sheet.cssRules].map(rule=>rule.cssText).join('\n'));}catch{}}}catch{}return chunks.filter(Boolean).join('\n');};
  const shadowCloneHtml=root=>{
    const container=document.createElement('div'),pairs=[];
    for(const node of root.childNodes){const clone=node.cloneNode(true);container.appendChild(clone);if(node instanceof Element&&clone instanceof Element)pairs.push([node,clone]);}
    const walkPair=(source,clone)=>{if(source instanceof HTMLCanvasElement&&clone instanceof HTMLCanvasElement){try{const data=source.toDataURL('image/png');if(data&&data!=='data:,'){clone.style.backgroundImage='url("'+data.replace(/"/g,'%22')+'")';clone.style.backgroundSize='100% 100%';clone.style.backgroundRepeat='no-repeat';clone.style.backgroundPosition='center';clone.dataset.animatorShadowCanvas='true';}}catch{}}const sourceChildren=source.children||[],cloneChildren=clone.children||[];for(let i=0;i<Math.min(sourceChildren.length,cloneChildren.length);i++)walkPair(sourceChildren[i],cloneChildren[i]);};
    for(const [source,clone] of pairs)walkPair(source,clone);
    container.querySelectorAll('script,[data-animator-internal],[data-animator-picker-outline],[data-animator-recorded-viewport],[data-animator-recorded-cursor]').forEach(node=>node.remove());
    const adopted=shadowCss(root);if(adopted){const style=document.createElement('style');style.dataset.animatorShadowAdopted='';style.textContent=adopted;container.prepend(style);}
    return container.innerHTML;
  };
  const mirrorShadowRoot=root=>{const host=root.host;if(!(host instanceof Element)||!host.isConnected)return;let template=[...host.children].find(child=>isShadowSnapshot(child));if(!(template instanceof HTMLTemplateElement)){template=document.createElement('template');template.dataset.animatorShadowSnapshot=root.mode||'open';host.appendChild(template);}try{template.innerHTML=shadowCloneHtml(root);}catch{}};
  const syncShadows=()=>{shadowSyncQueued=false;const roots=[...shadowRoots].filter(root=>root instanceof ShadowRoot&&root.host?.isConnected);for(let i=roots.length-1;i>=0;i--)mirrorShadowRoot(roots[i]);};
  const scheduleShadowSync=()=>{if(shadowSyncQueued)return;shadowSyncQueued=true;queueMicrotask(syncShadows);};
  const registerShadowRoot=root=>{if(!(root instanceof ShadowRoot)||shadowRoots.has(root))return;shadowRoots.add(root);try{const observer=new MutationObserver(()=>{discoverShadows(root);scheduleShadowSync();});observer.observe(root,{subtree:true,childList:true,attributes:true,characterData:true});shadowObservers.set(root,observer);}catch{}discoverShadows(root);scheduleShadowSync();};
  const discoverShadows=root=>{const scope=root instanceof Document||root instanceof ShadowRoot||root instanceof Element?root:null;if(!scope)return;const elements=[];if(scope instanceof Element)elements.push(scope);try{elements.push(...scope.querySelectorAll('*'));}catch{}for(const element of elements){if(!(element instanceof Element)||isShadowSnapshot(element))continue;if(element.shadowRoot?.mode==='open')registerShadowRoot(element.shadowRoot);}};
  try{const nativeAttachShadow=Element.prototype.attachShadow;Element.prototype.attachShadow=function(init){const root=nativeAttachShadow.call(this,init);registerShadowRoot(root);return root;};}catch{}
  discoverShadows(document);addEventListener('DOMContentLoaded',()=>{discoverShadows(document);scheduleShadowSync();},{once:true});addEventListener('load',()=>{discoverShadows(document);scheduleShadowSync();},{once:true});
  const recordElement=(el,at)=>{if(!recording||!(el instanceof Element)||isInternal(el)||birthSeen.has(el))return;birthSeen.add(el);const selector=selectorFor(el),entry={el,at,hidden:false};births.push(entry);birthCursor=births.length;loadEnd=Math.max(loadEnd,at);event('dom-build',el.tagName.toLowerCase(),{tag:el.tagName.toLowerCase(),domId:el.id||'',classes:[...el.classList].slice(0,6),depth:depthOf(el),selector},at);};
  const recordTree=(node,at)=>{if(!recording||!(node instanceof Element)||isInternal(node))return;recordElement(node,at);if(node.shadowRoot?.mode==='open')registerShadowRoot(node.shadowRoot);for(const child of node.querySelectorAll('*')){if(!isInternal(child))recordElement(child,at);if(child.shadowRoot?.mode==='open')registerShadowRoot(child.shadowRoot);}};
  const domObserver=new MutationObserver(records=>{if(!recording)return;const at=now();for(const record of records)for(const node of record.addedNodes)recordTree(node,at);discoverShadows(document);scheduleShadowSync();});
  try{domObserver.observe(document.documentElement||document,{subtree:true,childList:true});}catch{}
  event('document-lifecycle','Frame 0 · empty document',{phase:'bootstrap',url:location.href},0);
  addEventListener('DOMContentLoaded',()=>{const at=now();loadEnd=Math.max(loadEnd,at);event('document-lifecycle','DOMContentLoaded',{phase:'dom-content-loaded'},at);},{once:true});
  addEventListener('load',()=>{const at=now();loadEnd=Math.max(loadEnd,at);event('network-resource','document',{url:location.href,start:0,end:at,duration:at,initiatorType:'navigation'},at);event('document-lifecycle','Window load',{phase:'load'},at);flush();},{once:true});
  try{
    const resources=new PerformanceObserver(list=>{if(!recording)return;for(const entry of list.getEntries()){
      if(String(entry.name).includes('/__animator/'))continue;const start=Math.max(0,Number(entry.startTime)-started),end=Math.max(start,Number(entry.startTime)+Number(entry.duration)-started);loadEnd=Math.max(loadEnd,end);
      event('network-resource',entry.name.split('/').pop()||entry.name,{url:entry.name,start,end,duration:Math.max(0,end-start),initiatorType:entry.initiatorType||'resource'},end);
    }});
    resources.observe({type:'resource',buffered:true});addEventListener('beforeunload',()=>resources.disconnect(),{once:true});
  }catch{}
  try{const observer=new PerformanceObserver(list=>{if(!recording)return;for(const entry of list.getEntries())event('performance-long-task','Long task '+Math.round(entry.duration)+' ms',{duration:entry.duration,startTime:entry.startTime});});observer.observe({entryTypes:['longtask']});addEventListener('beforeunload',()=>observer.disconnect(),{once:true});}catch{}
  const frame=t=>{const delta=t-lastFrame;lastFrame=t;if(recording&&delta>50&&t-lastDrop>750){lastDrop=t;event('performance-frame-drop','Frame gap '+Math.round(delta)+' ms',{duration:delta});}const running=document.getAnimations().filter(a=>{if(a.playState!=='running'||a.__animatorMirror||a.__animatorMutationMirror)return false;const target=a.effect?.target;return !(target instanceof Element)||!isInternal(target);}).length;if(recording&&running>=10&&running!==lastConcurrent){lastConcurrent=running;event('performance-concurrency',String(running)+' concurrent animations',{count:running});}requestAnimationFrame(frame);};
  requestAnimationFrame(frame);
  const hideBirth=birth=>{if(birth.hidden||!(birth.el instanceof HTMLElement)||!birth.el.isConnected)return;if(!savedVisibility.has(birth.el))savedVisibility.set(birth.el,{value:birth.el.style.getPropertyValue('visibility'),priority:birth.el.style.getPropertyPriority('visibility')});birth.el.style.setProperty('visibility','hidden','important');birth.hidden=true;};
  const showBirth=birth=>{if(!birth.hidden||!(birth.el instanceof HTMLElement))return;const saved=savedVisibility.get(birth.el);if(saved&&saved.value)birth.el.style.setProperty('visibility',saved.value,saved.priority);else birth.el.style.removeProperty('visibility');birth.hidden=false;};
  const seekLoad=time=>{const target=Math.max(0,Number(time)||0);if(target<.5){while(birthCursor>0){birthCursor--;hideBirth(births[birthCursor]);}return;}while(birthCursor>0&&births[birthCursor-1].at>target){birthCursor--;hideBirth(births[birthCursor]);}while(birthCursor<births.length&&births[birthCursor].at<=target){showBirth(births[birthCursor]);birthCursor++;}};
  const releaseLoad=()=>{for(const birth of births)showBirth(birth);birthCursor=births.length;};
  const wrapReplay=()=>{const replay=window.__ANIMATOR_MUTATION_REPLAY__;if(!replay||replay.__animatorLoadWrapped)return false;replay.__animatorLoadWrapped=true;const baseSeek=replay.seek?.bind(replay),baseRelease=replay.release?.bind(replay),baseEnd=replay.end?.bind(replay);replay.seek=time=>{baseSeek?.(time);seekLoad(time);};replay.release=()=>{releaseLoad();baseRelease?.();};replay.end=()=>Math.max(Number(baseEnd?.())||0,loadEnd);replay.loadBirths=births;return true;};
  if(!wrapReplay()){const timer=setInterval(()=>{if(wrapReplay())clearInterval(timer);},10);setTimeout(()=>clearInterval(timer),2000);}
  const showPath=selector=>{let target=null;try{target=document.querySelector(selector);}catch{}if(!(target instanceof Element)||isInternal(target))return;target.scrollIntoView({block:'center',inline:'nearest',behavior:'smooth'});const rect=target.getBoundingClientRect();if(!highlight){highlight=document.createElement('div');highlight.dataset.animatorDomHighlight='';highlight.dataset.animatorInternal='';Object.assign(highlight.style,{position:'fixed',pointerEvents:'none',zIndex:'2147483644',border:'1px solid #8ab4f8',background:'rgba(138,180,248,.08)',boxSizing:'border-box',transition:'opacity .15s'});document.documentElement.appendChild(highlight);}Object.assign(highlight.style,{display:'block',opacity:'1',left:rect.left+'px',top:rect.top+'px',width:rect.width+'px',height:rect.height+'px'});setTimeout(()=>{if(highlight)highlight.style.opacity='0';},800);};
  addEventListener('message',messageEvent=>{const message=messageEvent.data;if(!message||typeof message.type!=='string')return;if(message.type==='SET_RECORDING'&&(message.source==='animator-editor'||message.source==='animator-timeline')){recording=!!message.enabled;if(!recording){eventQueue.length=0;if(flushTimer){clearTimeout(flushTimer);flushTimer=0;}syncShadows();}else{discoverShadows(document);scheduleShadowSync();}return;}if(message.source!=='animator-editor')return;if(message.type==='HIGHLIGHT_DOM_PATH'&&typeof message.selector==='string')showPath(message.selector);});
  addEventListener('beforeunload',()=>{syncShadows();domObserver.disconnect();for(const root of shadowRoots)shadowObservers.get(root)?.disconnect();if(flushTimer)clearTimeout(flushTimer);eventQueue.length=0;highlight?.remove();},{once:true});
})();`;