import type {MotionKeyframe,MotionSourceKind,MotionTrack,MotionTrigger} from '../src/types/motion.js';
import {getBrowserSession} from './browser-session.js';

export type BrowserMotionElement={id:string;tag:string;domId?:string|undefined;classes:string[];text?:string|undefined;rect:{x:number;y:number;width:number;height:number};alive:boolean};
export type BrowserMotionSnapshot={elements:BrowserMotionElement[];motionTracks:MotionTrack[];active:number;runtimeReady:boolean};

export async function scanBrowserMotion(id:string):Promise<BrowserMotionSnapshot>{
  const session=getBrowserSession(id);if(!session||session.destroyed||session.browserClosed)throw new Error('Browser preview session not found');
  return session.page.evaluate(()=>{
    const win=globalThis as typeof globalThis&{__ANIMATOR_ELEMENT_ID__?:((element:Element)=>string)|undefined;__ANIMATOR_RUNTIME__?:boolean|undefined;__ANIMATOR_BROWSER_SCAN_SEQ__?:number|undefined;};
    const elementIds=new Map<Element,string>();let fallbackSeq=Number(win.__ANIMATOR_BROWSER_SCAN_SEQ__)||0;
    const idFor=(element:Element):string=>{if(typeof win.__ANIMATOR_ELEMENT_ID__==='function'){try{return win.__ANIMATOR_ELEMENT_ID__(element);}catch{}}const object=element as Element&{__animatorBrowserElementId?:string|undefined};if(object.__animatorBrowserElementId)return object.__animatorBrowserElementId;const id=`browser-el-${++fallbackSeq}`;object.__animatorBrowserElementId=id;win.__ANIMATOR_BROWSER_SCAN_SEQ__=fallbackSeq;return id;};
    const elementMeta=(element:Element):BrowserMotionElement=>{const rect=element.getBoundingClientRect();return{id:idFor(element),tag:element.tagName.toLowerCase(),domId:element.id||undefined,classes:[...element.classList],text:(element.textContent||'').trim().slice(0,80)||undefined,rect:{x:rect.x,y:rect.y,width:rect.width,height:rect.height},alive:element.isConnected};};
    const rawAnimations=document.getAnimations().slice(0,600),motionTracks:MotionTrack[]=[];
    for(const animation of rawAnimations){
      const effect=animation.effect instanceof KeyframeEffect?animation.effect:null;if(!effect)continue;const target=effect.target;if(!(target instanceof Element)||target.hasAttribute('data-animator-internal'))continue;
      const object=animation as Animation&{__animatorId?:string|undefined;__animatorBrowserStartTime?:number|undefined;timeline?:AnimationTimeline|null};const id=object.__animatorId||(object.__animatorId=`browser-anim-${Math.random().toString(36).slice(2)}`),elementId=idFor(target);elementIds.set(target,elementId);
      let timing:ComputedEffectTiming={} as ComputedEffectTiming,rawFrames:ComputedKeyframe[]=[];try{timing=effect.getComputedTiming();rawFrames=effect.getKeyframes();}catch{}
      const keyframes:MotionKeyframe[]=rawFrames.map(frame=>{const values:Record<string,string|number|null>={};let offset:number|undefined,easing:string|undefined,composite:string|undefined;for(const[key,value]of Object.entries(frame)){if(key==='computedOffset')continue;if(key==='offset'){if(typeof value==='number')offset=value;continue;}if(key==='easing'){if(typeof value==='string')easing=value;continue;}if(key==='composite'){if(typeof value==='string')composite=value;continue;}if(value===undefined)continue;values[key]=value===null||typeof value==='number'||typeof value==='string'?value:String(value);}return{values,...(offset!==undefined?{offset}:{}),...(easing?{easing}:{}),...(composite?{composite}:{})};});
      const names=[...new Set(keyframes.flatMap(frame=>Object.keys(frame.values)))],properties=names.map(name=>({name,values:keyframes.map(frame=>frame.values[name]).filter(value=>value!=null).map(String)}));
      const cssAnimation=typeof CSSAnimation!=='undefined'&&animation instanceof CSSAnimation,cssTransition=typeof CSSTransition!=='undefined'&&animation instanceof CSSTransition,timelineName=object.timeline?.constructor?.name??'',scrollDriven=timelineName==='ScrollTimeline'||timelineName==='ViewTimeline',sourceKind:MotionSourceKind=scrollDriven?'scroll-timeline':cssAnimation?'css-animation':cssTransition?'css-transition':'waapi',trigger:MotionTrigger=scrollDriven?{kind:'scroll-progress',source:'scroll-timeline'}:cssAnimation?{kind:'auto'}:cssTransition?{kind:'interaction'}:{kind:'unknown'},name=cssAnimation?(animation as CSSAnimation).animationName:cssTransition?(animation as CSSTransition).transitionProperty:undefined,current=Number(animation.currentTime),rate=Math.abs(Number(animation.playbackRate))||1;
      if(!Number.isFinite(object.__animatorBrowserStartTime))object.__animatorBrowserStartTime=Math.max(0,performance.now()-(Number.isFinite(current)?Math.max(0,current)/rate:0));const runtimeState=animation.playState==='finished'?'finished':animation.playState==='paused'?'paused':animation.playState==='idle'?'idle':'running';
      motionTracks.push({id,...(name?{name}:{}),target:{elementId},timing:{start:Number(object.__animatorBrowserStartTime)||0,...(Number(timing.duration)?{duration:Number(timing.duration)}:{}),...(Number(timing.delay)?{delay:Number(timing.delay)}:{}),...(Number(timing.iterations)?{iterations:Number(timing.iterations)}:{}),...(timing.direction?{direction:String(timing.direction)}:{}),...(timing.easing?{easing:String(timing.easing)}:{}),...(timing.fill?{fill:String(timing.fill)}:{})},properties,keyframes,trigger,source:{kind:sourceKind,confidence:'runtime-observed'},runtimeState});
    }
    return{elements:[...elementIds.keys()].map(elementMeta),motionTracks,active:rawAnimations.length,runtimeReady:!!win.__ANIMATOR_RUNTIME__};
  });
}
