export const mutationRuntimeSource = String.raw`(()=>{
  if(window.__ANIMATOR_MUTATION_RUNTIME__)return;window.__ANIMATOR_MUTATION_RUNTIME__=true;
  const OUT='animator-preview',IN='animator-timeline',started=performance.now(),ids=new WeakMap(),tracksByElement=new WeakMap(),tracksById=new Map();
  let seq=0,controlled=false,highlight=null;
  const post=(type,payload={})=>parent.postMessage({source:OUT,type,...payload},'*');
  const now=()=>performance.now()-started;
  const idFor=el=>{let id=ids.get(el);if(!id){id='motion-el-'+(++seq);ids.set(el,id);}return id;};
  const elementMeta=el=>{const rect=el.getBoundingClientRect();return{id:idFor(el),tag:el.tagName.toLowerCase(),domId:el.id||undefined,classes:[...el.classList],text:(el.textContent||'').trim().slice(0,80)||undefined,rect:{x:rect.x,y:rect.y,width:rect.width,height:rect.height},alive:el.isConnected};};
  const parseStyle=text=>{const map=new Map();for(const part of String(text||'').split(';')){const at=part.indexOf(':');if(at<0)continue;const key=part.slice(0,at).trim(),value=part.slice(at+1).trim();if(key)map.set(key,value);}return map;};
  const changedProperties=(before,after)=>{const a=parseStyle(before),b=parseStyle(after),keys=new Set([...a.keys(),...b.keys()]);return[...keys].filter(key=>a.get(key)!==b.get(key));};
  const getTrack=el=>{let track=tracksByElement.get(el);if(track)return track;track={id:'runtime-style-'+Math.random().toString(36).slice(2),el,elementId:idFor(el),start:null,last:null,previous:el.getAttribute('style'),properties:new Set()};tracksByElement.set(el,track);tracksById.set(track.id,track);return track;};
  const report=track=>{if(track.start==null||track.last==null)return;const props=[...track.properties];post('ELEMENTS',{elements:[elementMeta(track.el)]});post('ANIMATION',{animation:{id:track.id,elementId:track.elementId,type:'runtime-style',name:props.length?'JS style · '+props.join(', '):'JS style mutation',startTime:track.start,duration:Math.max(1,track.last-track.start),properties:props.map(name=>({name})),confidence:'runtime-observed',runtimeState:controlled?'paused':'running'}});};
  const observer=new MutationObserver(records=>{if(controlled)return;for(const record of records){if(record.type!=='attributes'||record.attributeName!=='style'||!(record.target instanceof Element))continue;const track=getTrack(record.target),value=record.target.getAttribute('style'),at=now();const previous=track.previous??record.oldValue;for(const prop of changedProperties(previous,value))track.properties.add(prop);track.previous=value;if(track.start==null)track.start=at;track.last=at;report(track);}});
  observer.observe(document.documentElement,{subtree:true,attributes:true,attributeOldValue:true,attributeFilter:['style']});
  const targetFor=id=>{const track=tracksById.get(id);if(track?.el instanceof Element)return track.el;try{const animation=document.getAnimations({subtree:true}).find(item=>item.__animatorId===id);const target=animation?.effect?.target;return target instanceof Element?target:null;}catch{return null;}};
  const showTarget=id=>{const target=targetFor(id);if(!(target instanceof Element))return;const meta=elementMeta(target);post('ELEMENTS',{elements:[meta]});post('SELECT_ELEMENT',{element:meta});const rect=target.getBoundingClientRect();if(!highlight){highlight=document.createElement('div');Object.assign(highlight.style,{position:'fixed',pointerEvents:'none',zIndex:'2147483645',border:'2px solid #d4a44c',background:'rgba(212,164,76,.08)',boxSizing:'border-box',transition:'opacity .15s'});document.documentElement.appendChild(highlight);}Object.assign(highlight.style,{display:'block',opacity:'1',left:rect.left+'px',top:rect.top+'px',width:rect.width+'px',height:rect.height+'px'});setTimeout(()=>{if(highlight)highlight.style.opacity='0';},900);};
  addEventListener('message',event=>{const m=event.data;if(!m||m.source!==IN||typeof m.type!=='string')return;if(m.type==='SCRUB_TIMELINE'||m.type==='PLAY_ALL'||m.type==='PAUSE_ALL'||m.type==='RESTART_ALL')controlled=true;else if(m.type==='RELEASE_TIMELINE'||m.type==='CLEAR_OVERRIDES')controlled=false;else if(m.type==='HIGHLIGHT_ANIMATION')showTarget(m.id);});
})();`;
