export const runtimeSource = String.raw`(()=>{
  if(window.__ANIMATOR_RUNTIME__)return;window.__ANIMATOR_RUNTIME__=true;
  const SOURCE='animator-preview',started=performance.now(),ids=new WeakMap(),byId=new Map(),animationMeta=new Map(),lastAnimationReport=new Map(),reportedAnimations=new Map(),reportedElements=new WeakSet(),created=new Set(),visibleElements=new Set();
  const nativeRAF=window.requestAnimationFrame.bind(window),nativeCancelRAF=window.cancelAnimationFrame.bind(window),nativeAnimate=Element.prototype.animate;
  let seq=0,picker=false,recording=true,hover=null,reducedStyle=null,externalControl=false,autoViewportCapture=true,burstRaf=0,burstUntil=0,lastBurstScan=0,burstReason='idle',lastScrollEvent=0;
  const post=(type,payload={})=>{const message={source:SOURCE,type,...payload};if(typeof window.__animatorEmit==='function'){try{void window.__animatorEmit(message);return;}catch{}}parent.postMessage(message,'*');};
  const now=()=>performance.now()-started;
  const sourceKind=type=>type==='web-animation'?'waapi':type==='css-animation'?'css-animation':type==='css-transition'?'css-transition':type==='runtime-style'?'runtime-style':type==='javascript'?'javascript':type==='raf'?'raf':type==='gsap'?'gsap':type==='framer-motion'?'framer-motion':type==='scroll-timeline'?'scroll-timeline':type==='svg'?'svg':type==='canvas'?'canvas':'unknown';
  const triggerFor=type=>type==='css-animation'?{kind:'auto'}:type==='css-transition'?{kind:'interaction'}:type==='scroll-timeline'?{kind:'scroll-progress',source:'scroll-timeline'}:{kind:'unknown'};
  const canonicalFrames=frames=>(frames||[]).map(frame=>{const values={};let offset,easing,composite;for(const[key,value]of Object.entries(frame)){if(key==='offset'&&typeof value==='number'){offset=value;continue;}if(key==='easing'&&typeof value==='string'){easing=value;continue;}if(key==='composite'&&typeof value==='string'){composite=value;continue;}if(key==='computedOffset')continue;values[key]=value===null||typeof value==='string'||typeof value==='number'?value:String(value);}return{values,...(offset!==undefined?{offset}:{}),...(easing!==undefined?{easing}:{}),...(composite!==undefined?{composite}:{})};});
  const toMotionTrack=value=>({id:value.id,...(value.name?{name:value.name}:{}),target:{elementId:value.elementId},timing:{start:value.startTime,...(value.duration!==undefined?{duration:value.duration}:{}),...(value.delay!==undefined?{delay:value.delay}:{}),...(value.iterations!==undefined?{iterations:value.iterations}:{}),...(value.direction?{direction:value.direction}:{}),...(value.easing?{easing:value.easing}:{}),...(value.fill?{fill:value.fill}:{})},properties:value.properties||[],keyframes:canonicalFrames(value.keyframes),trigger:triggerFor(value.type),source:{kind:sourceKind(value.type),confidence:value.confidence||'runtime-observed'},runtimeState:value.runtimeState||'idle'});
  const documentAnimations=()=>{try{return document.getAnimations({subtree:true});}catch{return document.getAnimations();}};
  const mutationReplay=()=>window.__ANIMATOR_MUTATION_REPLAY__;
  const isInternal=el=>el instanceof Element&&(el.hasAttribute('data-animator-internal')||el.hasAttribute('data-animator-focus-overlay')||el.hasAttribute('data-animator-magnify-host')||el.hasAttribute('data-animator-magnify-lens')||el.hasAttribute('data-animator-magnify-clone')||el.hasAttribute('data-animator-selection-highlight')||el.hasAttribute('data-animator-dom-highlight')||el.hasAttribute('data-animator-picker-outline')||el.hasAttribute('data-animator-reduced-motion'));
  const idFor=el=>{let id=ids.get(el);if(!id){id='el-'+(++seq);ids.set(el,id);byId.set(id,el);}return id;};
  window.__ANIMATOR_ELEMENT_ID__=idFor;
  const meta=el=>{const rect=el.getBoundingClientRect();return{id:idFor(el),tag:el.tagName.toLowerCase(),domId:el.id||undefined,classes:[...el.classList],text:(el.textContent||'').trim().slice(0,80)||undefined,rect:{x:rect.x,y:rect.y,width:rect.width,height:rect.height},alive:el.isConnected};};
  const ensureElement=el=>{if(isInternal(el)||reportedElements.has(el))return;reportedElements.add(el);post('ELEMENTS',{elements:[meta(el)]});};
  const emitEvent=(kind,el,label,data={})=>{if(!recording||externalControl||isInternal(el))return;post('EVENT',{event:{id:'ev-'+Math.random().toString(36).slice(2),at:now(),kind,elementId:el?idFor(el):undefined,label,data}});};
  const normalize=(animation,el,type,name)=>{
    let timing={},frames=[];try{timing=animation.effect?.getComputedTiming?.()||{};frames=animation.effect?.getKeyframes?.()||[];}catch{}
    const id=animation.__animatorId||(animation.__animatorId='anim-'+Math.random().toString(36).slice(2));let info=animationMeta.get(id);
    if(!info){const current=Number(animation.currentTime),playback=Math.abs(Number(animation.playbackRate))||1;info={startTime:Math.max(0,now()-(Number.isFinite(current)?Math.max(0,current)/playback:0)),type:type||'unknown',name:name||undefined};animationMeta.set(id,info);}else{if(type&&info.type==='unknown')info.type=type;if(name&&!info.name)info.name=name;}
    const props=[...new Set(frames.flatMap(frame=>Object.keys(frame).filter(key=>!['offset','easing','composite','computedOffset'].includes(key))))].map(prop=>({name:prop,values:frames.map(frame=>frame[prop]).filter(value=>value!=null).map(String)}));
    return{id,elementId:idFor(el),type:info.type||type||'unknown',name:info.name||name,startTime:info.startTime,duration:Number(timing.duration)||undefined,delay:Number(timing.delay)||undefined,iterations:Number(timing.iterations)||undefined,direction:timing.direction,easing:timing.easing,fill:timing.fill,properties:props,confidence:'runtime-observed',runtimeState:externalControl?'paused':animation.playState==='finished'?'finished':animation.playState==='paused'?'paused':animation.playState==='idle'?'idle':'running',keyframes:frames};
  };
  const reportAnimation=(animation,type='unknown',name,force=false,manual=false)=>{if(!animation||animation.__animatorMirror||animation.__animatorMutationMirror||(!recording&&!manual))return null;const el=animation.effect?.target;if(!(el instanceof Element)||isInternal(el))return null;const normalized=normalize(animation,el,type,name);ensureElement(el);reportedAnimations.set(normalized.id,normalized);const signature=JSON.stringify([normalized.type,normalized.name,normalized.startTime,normalized.duration,normalized.delay,normalized.iterations,normalized.easing,normalized.runtimeState,normalized.properties.map(prop=>prop.name)]);if(!force&&lastAnimationReport.get(normalized.id)===signature)return normalized;lastAnimationReport.set(normalized.id,signature);post('MOTION_TRACK',{track:toMotionTrack(normalized)});return normalized;};
  const scanAnimations=(force=false,viewportOnly=false)=>{if(!recording||(externalControl&&!force))return 0;let count=0;for(const animation of documentAnimations()){if(animation.__animatorMirror||animation.__animatorMutationMirror)continue;const target=animation.effect?.target;if(target instanceof Element&&isInternal(target))continue;if(viewportOnly&&target instanceof Element&&!visibleElements.has(target))continue;if(reportAnimation(animation,'unknown',undefined,force))count++;}return count;};
  const reportVisibleHistory=()=>{if(!recording)return;for(const animation of reportedAnimations.values()){const el=byId.get(animation.elementId);if(el instanceof Element&&!isInternal(el)&&visibleElements.has(el))post('MOTION_TRACK',{track:toMotionTrack(animation)});}};
  const postVisibleElements=()=>{if(!recording)return 0;const items=[...visibleElements].filter(el=>el instanceof Element&&!isInternal(el)&&el.isConnected).slice(0,2400);for(let index=0;index<items.length;index+=160)post('ELEMENTS',{elements:items.slice(index,index+160).map(meta)});return items.length;};
  const captureStats=(reason,burstActive=false)=>{const styleStats=mutationReplay()?.stats?.()||{tracks:0};const active=documentAnimations().filter(animation=>{if(animation.__animatorMirror||animation.__animatorMutationMirror)return false;const target=animation.effect?.target;return !(target instanceof Element)||!isInternal(target);});post('CAPTURE_REPORT',{reason,visibleElements:[...visibleElements].filter(el=>!isInternal(el)).length,activeAnimations:active.length,capturedAnimations:reportedAnimations.size,styleTracks:Number(styleStats.tracks)||0,autoCapture:autoViewportCapture,burstActive,at:now()});};
  const burstTick=stamp=>{burstRaf=0;if(!recording||externalControl)return;if(stamp-lastBurstScan>=28){lastBurstScan=stamp;scanAnimations(false,true);}if(performance.now()<burstUntil){burstRaf=nativeRAF(burstTick);return;}captureStats(burstReason,false);};
  const startBurst=(reason,duration=900)=>{if(!recording||externalControl)return;if(!autoViewportCapture&&reason!=='manual'&&reason!=='auto-enabled')return;burstReason=reason;burstUntil=Math.max(burstUntil,performance.now()+duration);if(!burstRaf)burstRaf=nativeRAF(burstTick);};
  const viewportObserver='IntersectionObserver'in window?new IntersectionObserver(entries=>{let entered=false;for(const entry of entries){if(isInternal(entry.target))continue;if(entry.isIntersecting){if(!visibleElements.has(entry.target))entered=true;visibleElements.add(entry.target);}else visibleElements.delete(entry.target);}if(entered)startBurst('viewport-entry',850);},{root:null,rootMargin:'160px 0px 160px 0px',threshold:0}):null;
  const observeTree=node=>{if(!(node instanceof Element)||isInternal(node))return;viewportObserver?.observe(node);for(const child of node.querySelectorAll('*'))if(!isInternal(child))viewportObserver?.observe(child);};
  const registerAll=()=>{for(const element of document.querySelectorAll('body *'))if(!isInternal(element))viewportObserver?.observe(element);};
  const recalculateViewport=(reason='manual')=>{if(!recording){captureStats('recording-paused',false);return;}registerAll();const active=scanAnimations(true,false);reportVisibleHistory();const visible=postVisibleElements();const styleStats=mutationReplay()?.recalculateViewport?.()||{tracks:0};post('CAPTURE_REPORT',{reason,visibleElements:visible,activeAnimations:active,capturedAnimations:reportedAnimations.size,styleTracks:Number(styleStats.tracks)||0,autoCapture:autoViewportCapture,burstActive:true,at:now()});startBurst(reason==='manual'?'manual':reason,1200);};
  const queueTargetScan=el=>{if(!recording||isInternal(el))return;queueMicrotask(()=>{if(!recording||isInternal(el))return;for(const animation of documentAnimations())if(animation.effect?.target===el)reportAnimation(animation,'unknown',undefined,true);});};
  Element.prototype.animate=function(keyframes,options){const animation=nativeAnimate.call(this,keyframes,options);if(recording&&!isInternal(this)){queueMicrotask(()=>reportAnimation(animation,'web-animation',undefined,true));startBurst('waapi',650);}return animation;};
  document.addEventListener('animationstart',event=>{if(!(event.target instanceof Element)||isInternal(event.target))return;emitEvent('animationstart',event.target,event.animationName);if(recording)queueMicrotask(()=>{if(recording)documentAnimations().filter(animation=>animation.effect?.target===event.target).forEach(animation=>reportAnimation(animation,'css-animation',event.animationName,true));});startBurst('css-animation',750);},true);
  document.addEventListener('transitionrun',event=>{if(!(event.target instanceof Element)||isInternal(event.target))return;emitEvent('transition',event.target,event.propertyName,{elapsedTime:event.elapsedTime});if(recording)queueMicrotask(()=>{if(recording)documentAnimations().filter(animation=>animation.effect?.target===event.target).forEach(animation=>reportAnimation(animation,'css-transition',event.propertyName,true));});startBurst('css-transition',650);},true);
  ['animationend','animationcancel','transitionend','transitioncancel'].forEach(type=>document.addEventListener(type,event=>{if(!(event.target instanceof Element)||isInternal(event.target))return;emitEvent(type,event.target,event.animationName||event.propertyName);queueTargetScan(event.target);},true));

  const observer=new MutationObserver(records=>{if(!recording||externalControl)return;let structural=false;for(const record of records){if(record.type==='attributes'&&record.target instanceof Element){if(isInternal(record.target))continue;emitEvent(record.attributeName==='class'?'class-mutation':record.attributeName==='style'?'style-mutation':'attribute-mutation',record.target,(record.attributeName||'attribute')+' changed',{attribute:record.attributeName});if(record.attributeName!=='style'){queueTargetScan(record.target);structural=true;}continue;}if(record.type!=='childList')continue;let projectChange=false;for(const node of record.addedNodes){if(!(node instanceof Element)||isInternal(node))continue;projectChange=true;observeTree(node);emitEvent('dom-insert',node,'Element inserted');const descendants=Array.from(node.querySelectorAll('*')).filter(child=>!isInternal(child)).slice(0,200);post('ELEMENTS',{elements:[meta(node),...descendants.map(meta)]});}for(const node of record.removedNodes)if(node instanceof Element&&!isInternal(node)){projectChange=true;visibleElements.delete(node);emitEvent('dom-remove',node,'Element removed');}if(projectChange)structural=true;}if(structural)startBurst('dom-change',700);});
  observer.observe(document.documentElement,{subtree:true,childList:true,attributes:true,attributeOldValue:false,attributeFilter:['class','style','hidden','open','aria-expanded','aria-hidden']});

  const userEvents=['click','pointerdown','pointerup','focus','blur','input','change','submit','keydown'];
  userEvents.forEach(type=>document.addEventListener(type,event=>{if(event.target instanceof Element&&!isInternal(event.target))emitEvent('user-'+type,event.target,type,{key:event.key});},true));
  document.addEventListener('scroll',event=>{const stamp=performance.now(),target=event.target instanceof Element?event.target:document.documentElement;if(!isInternal(target)&&stamp-lastScrollEvent>90){lastScrollEvent=stamp;emitEvent('user-scroll',target,'scroll');}if(!isInternal(target))startBurst('scroll',1050);},true);
  addEventListener('resize',()=>startBurst('resize',700),{passive:true});
  const outline=document.createElement('div');outline.dataset.animatorPickerOutline='';outline.dataset.animatorInternal='';Object.assign(outline.style,{position:'fixed',pointerEvents:'none',zIndex:'2147483647',border:'1px solid #58a6ff',background:'rgba(88,166,255,.08)',display:'none'});document.documentElement.appendChild(outline);
  document.addEventListener('mousemove',event=>{if(!picker)return;const el=document.elementFromPoint(event.clientX,event.clientY);if(!(el instanceof Element)||isInternal(el))return;hover=el;const rect=el.getBoundingClientRect();Object.assign(outline.style,{display:'block',left:rect.left+'px',top:rect.top+'px',width:rect.width+'px',height:rect.height+'px'});},true);
  document.addEventListener('click',event=>{if(!picker||!(event.target instanceof Element)||isInternal(event.target))return;event.preventDefault();event.stopPropagation();picker=false;outline.style.display='none';ensureElement(event.target);post('SELECT_ELEMENT',{element:meta(event.target)});},true);

  const setReduced=enabled=>{if(enabled&&!reducedStyle){reducedStyle=document.createElement('style');reducedStyle.dataset.animatorReducedMotion='';reducedStyle.dataset.animatorInternal='';reducedStyle.textContent='*,*::before,*::after{scroll-behavior:auto!important;animation-duration:.001ms!important;animation-iteration-count:1!important;transition-duration:.001ms!important;transition-delay:0ms!important}';document.head.appendChild(reducedStyle);}else if(!enabled&&reducedStyle){reducedStyle.remove();reducedStyle=null;}post('DIAGNOSTIC',{level:'info',message:enabled?'Reduced-motion emulation enabled':'Reduced-motion emulation disabled'});};
  const setRecording=enabled=>{recording=!!enabled;if(!recording){if(burstRaf)nativeCancelRAF(burstRaf);burstRaf=0;burstUntil=0;captureStats('recording-paused',false);post('DIAGNOSTIC',{level:'info',message:'Recording stopped immediately; runtime discovery is frozen'});return;}post('DIAGNOSTIC',{level:'info',message:'Recording resumed'});startBurst('recording-resumed',900);};
  const commands={
    SET_PICKER:message=>{picker=!!message.enabled;outline.style.display='none';},
    SET_RECORDING:message=>setRecording(message.enabled),
    SET_REDUCED_MOTION:message=>setReduced(!!message.enabled),
    SET_AUTO_VIEWPORT_CAPTURE:message=>{autoViewportCapture=!!message.enabled;if(autoViewportCapture&&recording)recalculateViewport('auto-enabled');else captureStats(autoViewportCapture?'recording-paused':'auto-disabled',false);},
    RECALCULATE_VIEWPORT:()=>recalculateViewport('manual'),
    CREATE_ANIMATION:message=>{const el=byId.get(message.elementId);if(!el||isInternal(el))return;const animation=el.animate(message.keyframes,{duration:message.duration,delay:message.delay||0,easing:message.easing,iterations:message.iterations||1,direction:message.direction||'normal',fill:message.fill||'both'});const id=animation.__animatorId||(animation.__animatorId='anim-'+Math.random().toString(36).slice(2));created.add(id);reportAnimation(animation,'web-animation','Created animation',true,true);},
    CLEAR_OVERRIDES:()=>{for(const id of created){try{documentAnimations().find(animation=>animation.__animatorId===id)?.cancel();}catch{}animationMeta.delete(id);lastAnimationReport.delete(id);reportedAnimations.delete(id);}created.clear();setReduced(false);post('DIAGNOSTIC',{level:'info',message:'Temporary animation overrides cleared'});}
  };
  addEventListener('message',event=>{const message=event.data;if(!message||typeof message.type!=='string')return;if(message.source==='animator-editor'){commands[message.type]?.(message);return;}if(message.source!=='animator-timeline')return;if(message.type==='SET_RECORDING'){setRecording(message.enabled);return;}if(['SCRUB_TIMELINE','SEEK_FRAME','STEP_FRAME','PLAY_ALL','PAUSE_ALL','RESTART_ALL','SET_ANIMATION_TIME','SET_SOLO_ANIMATION','PLAY_ANIMATION','PAUSE_ANIMATION','RESTART_ANIMATION'].includes(message.type))externalControl=true;else if(message.type==='RELEASE_TIMELINE'||message.type==='CLEAR_OVERRIDES')externalControl=false;});

  const discover=()=>{const elements=Array.from(document.querySelectorAll('body *')).filter(element=>!isInternal(element)).slice(0,1200);elements.forEach(element=>{reportedElements.add(element);viewportObserver?.observe(element);});post('ELEMENTS',{elements:elements.map(meta)});};
  nativeRAF(()=>{discover();scanAnimations(true,false);startBurst('startup',1300);post('READY');});
  const scanTimer=setInterval(()=>{if(recording&&!externalControl)scanAnimations(false,false);},450);
  addEventListener('beforeunload',()=>{observer.disconnect();viewportObserver?.disconnect();if(burstRaf)nativeCancelRAF(burstRaf);clearInterval(scanTimer);},{once:true});
})();`;