export const runtimeSource = String.raw`(()=>{
  if(window.__ANIMATOR_RUNTIME__)return;window.__ANIMATOR_RUNTIME__=true;
  const SOURCE='animator-preview',started=performance.now(),ids=new WeakMap(),byId=new Map(),animationMeta=new Map(),lastAnimationReport=new Map(),reportedAnimations=new Map(),reportedElements=new WeakSet(),created=new Set(),visibleElements=new Set();
  const nativeRAF=window.requestAnimationFrame.bind(window),nativeCancelRAF=window.cancelAnimationFrame.bind(window),nativeAnimate=Element.prototype.animate;
  let seq=0,picker=false,recording=true,hover=null,reducedStyle=null,externalControl=false,autoViewportCapture=true,burstRaf=0,burstUntil=0,lastBurstScan=0,burstReason='idle',lastScrollEvent=0;
  const post=(type,payload={})=>parent.postMessage({source:SOURCE,type,...payload},'*');
  const now=()=>performance.now()-started;
  const documentAnimations=()=>{try{return document.getAnimations({subtree:true});}catch{return document.getAnimations();}};
  const mutationReplay=()=>window.__ANIMATOR_MUTATION_REPLAY__;
  const idFor=el=>{let id=ids.get(el);if(!id){id='el-'+(++seq);ids.set(el,id);byId.set(id,el);}return id;};
  const meta=el=>{const rect=el.getBoundingClientRect();return{id:idFor(el),tag:el.tagName.toLowerCase(),domId:el.id||undefined,classes:[...el.classList],text:(el.textContent||'').trim().slice(0,80)||undefined,rect:{x:rect.x,y:rect.y,width:rect.width,height:rect.height},alive:el.isConnected};};
  const ensureElement=el=>{if(reportedElements.has(el))return;reportedElements.add(el);post('ELEMENTS',{elements:[meta(el)]});};
  const emitEvent=(kind,el,label,data={})=>{if(!recording||externalControl)return;post('EVENT',{event:{id:'ev-'+Math.random().toString(36).slice(2),at:now(),kind,elementId:el?idFor(el):undefined,label,data}});};
  const normalize=(animation,el,type,name)=>{
    let timing={},frames=[];try{timing=animation.effect?.getComputedTiming?.()||{};frames=animation.effect?.getKeyframes?.()||[];}catch{}
    const id=animation.__animatorId||(animation.__animatorId='anim-'+Math.random().toString(36).slice(2));let info=animationMeta.get(id);
    if(!info){const current=Number(animation.currentTime),playback=Math.abs(Number(animation.playbackRate))||1;info={startTime:Math.max(0,now()-(Number.isFinite(current)?Math.max(0,current)/playback:0)),type:type||'unknown',name:name||undefined};animationMeta.set(id,info);}else{if(type&&info.type==='unknown')info.type=type;if(name&&!info.name)info.name=name;}
    const props=[...new Set(frames.flatMap(frame=>Object.keys(frame).filter(key=>!['offset','easing','composite','computedOffset'].includes(key))))].map(prop=>({name:prop,values:frames.map(frame=>frame[prop]).filter(value=>value!=null).map(String)}));
    return{id,elementId:idFor(el),type:info.type||type||'unknown',name:info.name||name,startTime:info.startTime,duration:Number(timing.duration)||undefined,delay:Number(timing.delay)||undefined,iterations:Number(timing.iterations)||undefined,direction:timing.direction,easing:timing.easing,fill:timing.fill,properties:props,confidence:'runtime-observed',runtimeState:externalControl?'paused':animation.playState==='finished'?'finished':animation.playState==='paused'?'paused':animation.playState==='idle'?'idle':'running',keyframes:frames};
  };
  const reportAnimation=(animation,type='unknown',name,force=false)=>{if(!animation||animation.__animatorMirror||animation.__animatorMutationMirror)return null;const el=animation.effect?.target;if(!(el instanceof Element))return null;const normalized=normalize(animation,el,type,name);ensureElement(el);reportedAnimations.set(normalized.id,normalized);const signature=JSON.stringify([normalized.type,normalized.name,normalized.startTime,normalized.duration,normalized.delay,normalized.iterations,normalized.easing,normalized.runtimeState,normalized.properties.map(prop=>prop.name)]);if(!force&&lastAnimationReport.get(normalized.id)===signature)return normalized;lastAnimationReport.set(normalized.id,signature);post('ANIMATION',{animation:normalized});return normalized;};
  const scanAnimations=(force=false,viewportOnly=false)=>{if(externalControl&&!force)return 0;let count=0;for(const animation of documentAnimations()){if(animation.__animatorMirror||animation.__animatorMutationMirror)continue;const target=animation.effect?.target;if(viewportOnly&&target instanceof Element&&!visibleElements.has(target))continue;if(reportAnimation(animation,'unknown',undefined,force))count++;}return count;};
  const reportVisibleHistory=()=>{for(const animation of reportedAnimations.values()){const el=byId.get(animation.elementId);if(el instanceof Element&&visibleElements.has(el))post('ANIMATION',{animation});}};
  const postVisibleElements=()=>{const items=[...visibleElements].filter(el=>el instanceof Element&&el.isConnected).slice(0,2400);for(let index=0;index<items.length;index+=160)post('ELEMENTS',{elements:items.slice(index,index+160).map(meta)});return items.length;};
  const captureStats=(reason,burstActive=false)=>{const styleStats=mutationReplay()?.stats?.()||{tracks:0};post('CAPTURE_REPORT',{reason,visibleElements:visibleElements.size,activeAnimations:documentAnimations().filter(animation=>!animation.__animatorMirror&&!animation.__animatorMutationMirror).length,capturedAnimations:reportedAnimations.size,styleTracks:Number(styleStats.tracks)||0,autoCapture:autoViewportCapture,burstActive,at:now()});};
  const burstTick=stamp=>{burstRaf=0;if(externalControl)return;if(stamp-lastBurstScan>=28){lastBurstScan=stamp;scanAnimations(false,true);}if(performance.now()<burstUntil){burstRaf=nativeRAF(burstTick);return;}captureStats(burstReason,false);};
  const startBurst=(reason,duration=900)=>{if(externalControl)return;if(!autoViewportCapture&&reason!=='manual'&&reason!=='auto-enabled')return;burstReason=reason;burstUntil=Math.max(burstUntil,performance.now()+duration);if(!burstRaf)burstRaf=nativeRAF(burstTick);};
  const viewportObserver='IntersectionObserver'in window?new IntersectionObserver(entries=>{let entered=false;for(const entry of entries){if(entry.isIntersecting){if(!visibleElements.has(entry.target))entered=true;visibleElements.add(entry.target);}else visibleElements.delete(entry.target);}if(entered)startBurst('viewport-entry',850);},{root:null,rootMargin:'160px 0px 160px 0px',threshold:0}):null;
  const observeTree=node=>{if(!(node instanceof Element))return;viewportObserver?.observe(node);for(const child of node.querySelectorAll('*'))viewportObserver?.observe(child);};
  const registerAll=()=>{for(const element of document.querySelectorAll('body *'))viewportObserver?.observe(element);};
  const recalculateViewport=(reason='manual')=>{registerAll();const active=scanAnimations(true,false);reportVisibleHistory();const visible=postVisibleElements();const styleStats=mutationReplay()?.recalculateViewport?.()||{tracks:0};post('CAPTURE_REPORT',{reason,visibleElements:visible,activeAnimations:active,capturedAnimations:reportedAnimations.size,styleTracks:Number(styleStats.tracks)||0,autoCapture:autoViewportCapture,burstActive:true,at:now()});startBurst(reason==='manual'?'manual':reason,1200);};
  const queueTargetScan=el=>{queueMicrotask(()=>{for(const animation of documentAnimations())if(animation.effect?.target===el)reportAnimation(animation,'unknown',undefined,true);});};
  Element.prototype.animate=function(keyframes,options){const animation=nativeAnimate.call(this,keyframes,options);queueMicrotask(()=>reportAnimation(animation,'web-animation',undefined,true));startBurst('waapi',650);return animation;};
  document.addEventListener('animationstart',event=>{emitEvent('animationstart',event.target,event.animationName);queueMicrotask(()=>documentAnimations().filter(animation=>animation.effect?.target===event.target).forEach(animation=>reportAnimation(animation,'css-animation',event.animationName,true)));startBurst('css-animation',750);},true);
  document.addEventListener('transitionrun',event=>{emitEvent('transition',event.target,event.propertyName,{elapsedTime:event.elapsedTime});queueMicrotask(()=>documentAnimations().filter(animation=>animation.effect?.target===event.target).forEach(animation=>reportAnimation(animation,'css-transition',event.propertyName,true)));startBurst('css-transition',650);},true);
  ['animationend','animationcancel','transitionend','transitioncancel'].forEach(type=>document.addEventListener(type,event=>{emitEvent(type,event.target,event.animationName||event.propertyName);queueTargetScan(event.target);},true));

  const observer=new MutationObserver(records=>{if(externalControl)return;let structural=false;for(const record of records){if(record.type==='attributes'&&record.target instanceof Element){emitEvent(record.attributeName==='class'?'class-mutation':record.attributeName==='style'?'style-mutation':'attribute-mutation',record.target,(record.attributeName||'attribute')+' changed',{attribute:record.attributeName});if(record.attributeName!=='style'){queueTargetScan(record.target);structural=true;}continue;}if(record.type!=='childList')continue;structural=true;for(const node of record.addedNodes){if(!(node instanceof Element))continue;observeTree(node);emitEvent('dom-insert',node,'Element inserted');post('ELEMENTS',{elements:[meta(node),...Array.from(node.querySelectorAll('*')).slice(0,200).map(meta)]});}for(const node of record.removedNodes)if(node instanceof Element){visibleElements.delete(node);emitEvent('dom-remove',node,'Element removed');}}if(structural)startBurst('dom-change',700);});
  observer.observe(document.documentElement,{subtree:true,childList:true,attributes:true,attributeOldValue:false,attributeFilter:['class','style','hidden','open','aria-expanded','aria-hidden']});

  const userEvents=['click','pointerdown','pointerup','focus','blur','input','change','submit','keydown'];
  userEvents.forEach(type=>document.addEventListener(type,event=>{if(event.target instanceof Element)emitEvent('user-'+type,event.target,type,{key:event.key});},true));
  document.addEventListener('scroll',event=>{const stamp=performance.now();if(stamp-lastScrollEvent>90){lastScrollEvent=stamp;const target=event.target instanceof Element?event.target:document.documentElement;emitEvent('user-scroll',target,'scroll');}startBurst('scroll',1050);},true);
  addEventListener('resize',()=>startBurst('resize',700),{passive:true});
  const outline=document.createElement('div');Object.assign(outline.style,{position:'fixed',pointerEvents:'none',zIndex:'2147483647',border:'1px solid #58a6ff',background:'rgba(88,166,255,.08)',display:'none'});document.documentElement.appendChild(outline);
  document.addEventListener('mousemove',event=>{if(!picker)return;const el=document.elementFromPoint(event.clientX,event.clientY);if(!(el instanceof Element)||el===outline)return;hover=el;const rect=el.getBoundingClientRect();Object.assign(outline.style,{display:'block',left:rect.left+'px',top:rect.top+'px',width:rect.width+'px',height:rect.height+'px'});},true);
  document.addEventListener('click',event=>{if(!picker||!(event.target instanceof Element))return;event.preventDefault();event.stopPropagation();picker=false;outline.style.display='none';ensureElement(event.target);post('SELECT_ELEMENT',{element:meta(event.target)});},true);

  const setReduced=enabled=>{if(enabled&&!reducedStyle){reducedStyle=document.createElement('style');reducedStyle.dataset.animatorReducedMotion='';reducedStyle.textContent='*,*::before,*::after{scroll-behavior:auto!important;animation-duration:.001ms!important;animation-iteration-count:1!important;transition-duration:.001ms!important;transition-delay:0ms!important}';document.head.appendChild(reducedStyle);}else if(!enabled&&reducedStyle){reducedStyle.remove();reducedStyle=null;}post('DIAGNOSTIC',{level:'info',message:enabled?'Reduced-motion emulation enabled':'Reduced-motion emulation disabled'});};
  const commands={
    SET_PICKER:message=>{picker=!!message.enabled;outline.style.display='none';},
    SET_RECORDING:message=>{recording=!!message.enabled;},
    SET_REDUCED_MOTION:message=>setReduced(!!message.enabled),
    SET_AUTO_VIEWPORT_CAPTURE:message=>{autoViewportCapture=!!message.enabled;if(autoViewportCapture)recalculateViewport('auto-enabled');else captureStats('auto-disabled',false);},
    RECALCULATE_VIEWPORT:()=>recalculateViewport('manual'),
    CREATE_ANIMATION:message=>{const el=byId.get(message.elementId);if(!el)return;const animation=el.animate(message.keyframes,{duration:message.duration,delay:message.delay||0,easing:message.easing,iterations:message.iterations||1,direction:message.direction||'normal',fill:message.fill||'both'});const id=animation.__animatorId||(animation.__animatorId='anim-'+Math.random().toString(36).slice(2));created.add(id);reportAnimation(animation,'web-animation','Created animation',true);},
    CLEAR_OVERRIDES:()=>{for(const id of created){try{documentAnimations().find(animation=>animation.__animatorId===id)?.cancel();}catch{}animationMeta.delete(id);lastAnimationReport.delete(id);reportedAnimations.delete(id);}created.clear();setReduced(false);post('DIAGNOSTIC',{level:'info',message:'Temporary animation overrides cleared'});}
  };
  addEventListener('message',event=>{const message=event.data;if(!message||typeof message.type!=='string')return;if(message.source==='animator-editor'){commands[message.type]?.(message);return;}if(message.source!=='animator-timeline')return;if(['SCRUB_TIMELINE','SEEK_FRAME','STEP_FRAME','PLAY_ALL','PAUSE_ALL','RESTART_ALL','SET_ANIMATION_TIME'].includes(message.type))externalControl=true;else if(message.type==='RELEASE_TIMELINE'||message.type==='CLEAR_OVERRIDES')externalControl=false;});

  const discover=()=>{const elements=Array.from(document.querySelectorAll('body *')).slice(0,1200);elements.forEach(element=>{reportedElements.add(element);viewportObserver?.observe(element);});post('ELEMENTS',{elements:elements.map(meta)});};
  nativeRAF(()=>{discover();scanAnimations(true,false);startBurst('startup',1300);post('READY');});
  setInterval(()=>{if(!externalControl)scanAnimations(false,false);},450);
  addEventListener('beforeunload',()=>{observer.disconnect();viewportObserver?.disconnect();if(burstRaf)nativeCancelRAF(burstRaf);},{once:true});
})();`;
