export const viewHistoryRuntimeSource = String.raw`(()=>{
  if(window.__ANIMATOR_VIEW_HISTORY__)return;
  const IN='animator-editor',started=performance.now(),MAX_SAMPLES=30000,MIN_SAMPLE_MS=20,seed=Array.isArray(window.__ANIMATOR_VIEW_HISTORY_SEED__)?window.__ANIMATOR_VIEW_HISTORY_SEED__:[];
  const samples=seed.map(sample=>({...sample})).slice(-MAX_SAMPLES);let recording=!samples.length,captureEnabled=false,mode='off',controlled=false,pointerX=0,pointerY=0,pointerInside=false,lastSampleAt=samples.at(-1)?.at??-Infinity,captureRaf=0,lastApplied=null,viewportBox=null,cursor=null,label=null;
  const now=()=>performance.now()-started;
  const currentSample=at=>({at,x:scrollX,y:scrollY,vw:innerWidth,vh:innerHeight,mx:pointerX,my:pointerY,inside:pointerInside,pageWidth:Math.max(document.documentElement.scrollWidth,document.body?.scrollWidth||0),pageHeight:Math.max(document.documentElement.scrollHeight,document.body?.scrollHeight||0)});
  const reset=()=>{samples.length=0;lastSampleAt=-Infinity;lastApplied=null;controlled=false;hideOverlay();};
  const capture=force=>{captureRaf=0;if(!captureEnabled||!recording||controlled)return;const at=now();if(!force&&at-lastSampleAt<MIN_SAMPLE_MS)return;lastSampleAt=at;const sample=currentSample(at),previous=samples[samples.length-1];if(!force&&previous&&previous.x===sample.x&&previous.y===sample.y&&previous.mx===sample.mx&&previous.my===sample.my&&previous.inside===sample.inside&&previous.vw===sample.vw&&previous.vh===sample.vh)return;samples.push(sample);if(samples.length>MAX_SAMPLES)samples.splice(0,samples.length-MAX_SAMPLES);};
  const scheduleCapture=force=>{if(force){capture(true);return;}if(!captureRaf)captureRaf=requestAnimationFrame(()=>capture(false));};
  const ensureOverlay=()=>{if(viewportBox&&cursor)return;viewportBox=document.createElement('div');viewportBox.dataset.animatorRecordedViewport='';viewportBox.dataset.animatorInternal='';Object.assign(viewportBox.style,{display:'none',position:'absolute',pointerEvents:'none',zIndex:'2147483644',border:'2px solid rgba(102,178,255,.98)',boxShadow:'0 0 0 100vmax rgba(0,0,0,.76)',background:'transparent',boxSizing:'border-box'});label=document.createElement('span');label.dataset.animatorInternal='';label.textContent='Recorded viewport';Object.assign(label.style,{position:'absolute',left:'6px',top:'6px',padding:'3px 6px',borderRadius:'4px',background:'rgba(7,14,22,.9)',color:'#b9dcff',font:'10px/1.2 system-ui,sans-serif',letterSpacing:'.02em'});viewportBox.appendChild(label);cursor=document.createElement('div');cursor.dataset.animatorRecordedCursor='';cursor.dataset.animatorInternal='';Object.assign(cursor.style,{display:'none',position:'fixed',width:'20px',height:'26px',pointerEvents:'none',zIndex:'2147483646',background:'#fff',clipPath:'polygon(0 0,0 100%,30% 72%,48% 100%,61% 94%,44% 67%,78% 67%)',filter:'drop-shadow(0 1px 1px #000) drop-shadow(0 0 1px #000)'});document.documentElement.append(viewportBox,cursor);};
  function hideOverlay(){if(viewportBox)viewportBox.style.display='none';if(cursor)cursor.style.display='none';}
  const findSample=time=>{if(!samples.length)return null;if(time<=samples[0].at)return samples[0];let low=0,high=samples.length-1;while(low<=high){const mid=(low+high)>>1;if(samples[mid].at<=time)low=mid+1;else high=mid-1;}const a=samples[Math.max(0,high)],b=samples[Math.min(samples.length-1,high+1)];if(!b||b===a||b.at<=a.at)return a;const t=Math.max(0,Math.min(1,(time-a.at)/(b.at-a.at))),mix=(x,y)=>x+(y-x)*t;return{at:time,x:mix(a.x,b.x),y:mix(a.y,b.y),vw:mix(a.vw,b.vw),vh:mix(a.vh,b.vh),mx:mix(a.mx,b.mx),my:mix(a.my,b.my),inside:t<.5?a.inside:b.inside,pageWidth:mix(a.pageWidth,b.pageWidth),pageHeight:mix(a.pageHeight,b.pageHeight)};};
  const renderSample=sample=>{if(!sample||mode==='off'){hideOverlay();return;}ensureOverlay();lastApplied=sample;if(mode==='attached'){viewportBox.style.display='none';try{scrollTo({left:sample.x,top:sample.y,behavior:'instant'});}catch{scrollTo(sample.x,sample.y);}cursor.style.position='fixed';cursor.style.left=sample.mx+'px';cursor.style.top=sample.my+'px';cursor.style.display=sample.inside?'block':'none';return;}viewportBox.style.display='block';viewportBox.style.left=sample.x+'px';viewportBox.style.top=sample.y+'px';viewportBox.style.width=Math.max(1,sample.vw)+'px';viewportBox.style.height=Math.max(1,sample.vh)+'px';if(label)label.textContent='Recorded viewport · '+Math.round(sample.x)+', '+Math.round(sample.y);cursor.style.position='absolute';cursor.style.left=(sample.x+sample.mx)+'px';cursor.style.top=(sample.y+sample.my)+'px';cursor.style.display=sample.inside?'block':'none';};
  const seek=time=>{controlled=true;if(mode==='off'){hideOverlay();return;}renderSample(findSample(Math.max(0,Number(time)||0)));};
  const release=()=>{controlled=false;lastApplied=null;hideOverlay();};
  const setCapture=(value,shouldReset)=>{captureEnabled=!!value;if(shouldReset)reset();if(captureEnabled&&recording)scheduleCapture(true);};
  const setMode=value=>{mode=value==='detached'?'detached':value==='attached'?'attached':'off';if(mode==='off')hideOverlay();else if(controlled)renderSample(lastApplied||findSample(0));};
  addEventListener('pointermove',event=>{pointerX=event.clientX;pointerY=event.clientY;pointerInside=true;scheduleCapture(false);},{capture:true,passive:true});
  addEventListener('pointerenter',event=>{pointerX=event.clientX;pointerY=event.clientY;pointerInside=true;scheduleCapture(true);},{capture:true,passive:true});
  addEventListener('mouseout',event=>{if(event.relatedTarget==null){pointerInside=false;scheduleCapture(true);}},{capture:true,passive:true});
  addEventListener('scroll',()=>scheduleCapture(true),{capture:true,passive:true});addEventListener('resize',()=>scheduleCapture(true),{passive:true});
  addEventListener('message',event=>{const message=event.data;if(!message||message.source!==IN||typeof message.type!=='string')return;if(message.type==='SET_RECORDING'){recording=!!message.enabled;if(recording&&captureEnabled)scheduleCapture(true);return;}if(message.type==='SET_VIEW_HISTORY_CAPTURE'){setCapture(message.enabled,!!message.reset);return;}if(message.type==='SET_VIEW_HISTORY_MODE'){setMode(message.mode);return;}if(message.type==='APPLY_VIEW_HISTORY_TIME'){if(message.controlled)seek(message.time);else release();return;}});
  const heartbeat=setInterval(()=>{if(captureEnabled&&recording&&!controlled)capture(true);},120);
  addEventListener('beforeunload',()=>{clearInterval(heartbeat);if(captureRaf)cancelAnimationFrame(captureRaf);},{once:true});
  window.__ANIMATOR_VIEW_HISTORY__={seek,release,setMode,setCapture,reset,snapshot:()=>samples.map(sample=>({...sample})),stats:()=>({samples:samples.length,end:samples.at(-1)?.at||0,start:samples[0]?.at||0,mode,enabled:captureEnabled,captureEnabled,recording,controlled})};
})();`;