import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { createServer } from 'node:http';
import path from 'node:path';
import { chromium } from '@playwright/test';

const port=4173,base=`http://127.0.0.1:${port}`;
const remoteFixture=createServer((req,res)=>{
  if(req.url==='/remote'){res.writeHead(301,{location:'/remote/'});res.end();return;}
  if(req.url==='/remote/style.css'){res.writeHead(200,{'content-type':'text/css'});res.end('#remote-card{opacity:0;animation:remote-in .25s ease-out both}@keyframes remote-in{from{opacity:0;transform:translateY(18px)}to{opacity:1;transform:none}}');return;}
  if(req.url==='/remote/app.js'){res.writeHead(200,{'content-type':'application/javascript'});res.end('window.__remoteLoaded=true;document.documentElement.dataset.remoteScript="ok";');return;}
  if(req.url==='/remote/'){res.writeHead(200,{'content-type':'text/html','content-security-policy':"default-src 'self'; script-src 'self'; style-src 'self'",'x-frame-options':'DENY'});res.end('<!doctype html><html><head><link rel="stylesheet" href="style.css"><title>Remote</title></head><body><h1 id="remote-card">Remote page</h1><script src="app.js"></script></body></html>');return;}
  res.writeHead(404);res.end('not found');
});
const remotePort=await listen(remoteFixture),remoteUrl=`http://127.0.0.1:${remotePort}/remote`;
const server=spawn(process.execPath,['server-dist/server/index.js','--production'],{cwd:process.cwd(),env:{...process.env,PORT:String(port),NODE_ENV:'production'},stdio:['ignore','pipe','pipe']});
let serverLog='';server.stdout.on('data',chunk=>serverLog+=chunk);server.stderr.on('data',chunk=>serverLog+=chunk);

try{
  await waitForServer(`${base}/api/health`);
  const browser=await chromium.launch({headless:true});
  try{
    const page=await browser.newPage({viewport:{width:1440,height:1000}}),browserErrors=[];
    page.on('pageerror',error=>browserErrors.push(`pageerror: ${error.stack??error.message}`));page.on('console',message=>{if(message.type()==='error')browserErrors.push(`console: ${message.text()}`);});
    await page.goto(base,{waitUntil:'networkidle'});
    try{await page.locator('.app').waitFor({state:'attached',timeout:5000});}catch{throw new Error(`editor did not mount; url=${page.url()} errors=${browserErrors.join(' | ')||'none'} html=${(await page.content()).slice(0,1800)}`);}
    await page.locator('.toolbarMore>summary').click();await page.locator('[data-path-input]').fill(path.join(process.cwd(),'fixture'));await page.locator('[data-action="open-project"]').click();
    const frameLocator=page.locator('[data-preview-frame]');await frameLocator.waitFor({state:'attached'});await waitUntil(async()=>/^http:\/\/127\.0\.0\.1:\d+\//.test(await frameLocator.getAttribute('src')??''),'preview did not use dedicated origin');
    let frameHandle=await frameLocator.elementHandle(),frame=await frameHandle?.contentFrame();assert(frame,'preview iframe missing');await frame.locator('.repeat-motion').first().waitFor();
    await waitUntil(async()=>await page.locator('.v2GroupRow').filter({hasText:'repeat-pop'}).count()===1,'repeat-pop group missing');
    const group=page.locator('.v2GroupRow').filter({hasText:'repeat-pop'}).first();await waitUntil(async()=>/3 lanes/.test(await group.textContent()??''),'repeat-pop lane summary missing');
    assert.equal(await group.locator('.v2GroupClip').count(),1,'collapsed animation group must render one aggregate clip');assert.equal((await group.locator('.v2LaneCount').textContent())?.trim(),'3','repeat-pop lane count is wrong');
    await group.locator('[data-v2-toggle]').click();await waitUntil(async()=>await page.locator('.v2InstanceRow').count()>=3,'instances did not expand');
    const expandedLanes=page.locator('.v2InstanceRow').filter({has:page.locator('.v2InstanceClip')});assert((await expandedLanes.count())>=3,'expanded animation group did not create dedicated lanes');
    const overlappingLanes=await expandedLanes.evaluateAll(rows=>rows.some(row=>{const clips=[...row.querySelectorAll('.v2InstanceClip')];if(clips.length!==1)return true;const clip=clips[0].getBoundingClientRect(),bounds=row.querySelector('.v2Motion')?.getBoundingClientRect();return !bounds||clip.top<bounds.top-1||clip.bottom>bounds.bottom+1;}));assert.equal(overlappingLanes,false,'animation clips overlap or escape their dedicated lanes');
    const firstInstance=page.locator('.v2InstanceRow').first();await firstInstance.locator('.v2InstanceLabel button[data-v2-instance]').click();await waitUntil(async()=>await firstInstance.evaluate(node=>node.classList.contains('selected')),'instance selection failed');
    await group.locator('[data-v2-toggle]').click();await waitUntil(async()=>await page.locator('.v2InstanceRow').count()===0,'repeat-pop group did not collapse before isolation');
    const motionIsolation=page.locator('[data-isolate="animation"]');await motionIsolation.click();await waitUntil(async()=>await page.locator('.v2GroupRow:not([hidden])').count()>=1,'motion isolation hid every collapsed group row');
    assert((await page.locator('.v2GroupRow:not([hidden])').count())>=1,'motion isolation hid the selected group row');await page.locator('[data-isolate="all"]').click();
    const recordButton=page.locator('[data-action="record"]'),recordBadge=page.locator('[data-record-state]');
    await waitUntil(async()=>/REC/.test(await recordBadge.textContent()??''),'normal motion selection stopped recording implicitly');

    const labelWidth=Number.parseFloat(await page.locator('[data-timeline-v2]').evaluate(node=>getComputedStyle(node).getPropertyValue('--timeline-label-width')));assert(labelWidth>=260,`timeline label column stayed too narrow: ${labelWidth}`);
    const badOverflow=await page.locator('.v2GroupRow,.v2InstanceRow').evaluateAll(rows=>rows.some(row=>{const content=row.querySelector('.v2GroupButton,.v2InstanceLabel button[data-v2-instance]');if(!content)return false;const parts=[...content.querySelectorAll('span,small')];const overflow=parts.some(part=>part.scrollWidth>part.clientWidth+1);return overflow&&!row.querySelector('.v2DetailToggle');}));assert.equal(badOverflow,false,'timeline text overflows without an expand disclosure');
    const clippedVertical=await page.locator('.v2InstanceRow').evaluateAll(rows=>rows.some(row=>{const small=row.querySelector('small');if(!small)return false;return small.getBoundingClientRect().bottom>row.getBoundingClientRect().bottom+1;}));assert.equal(clippedVertical,false,'timeline metadata is vertically clipped');

    await page.locator('[data-focus-mode]').click();await waitUntil(async()=>await frame.locator('[data-animator-focus-overlay]').count()===1,'focus spotlight missing');assert.notEqual(await page.locator('.toolbar').evaluate(node=>getComputedStyle(node).display),'none','Focus hid editor UI');
    const focusVisual=await frame.locator('[data-animator-focus-overlay]').evaluate(node=>({border:getComputedStyle(node).borderTopWidth,shadow:getComputedStyle(node).boxShadow}));assert.equal(focusVisual.border,'0px','Focus still renders a visible border');assert(/9999px/.test(focusVisual.shadow),'Focus no longer darkens only the surrounding area');
    await page.locator('[data-magnify-mode]').click();await waitUntil(async()=>await frameLocator.getAttribute('data-camera-zoom')==='on','camera zoom did not activate');
    const camera=await frameLocator.evaluate(node=>({transform:node.style.transform,scale:Number(node.dataset.cameraScale),pointer:getComputedStyle(node).pointerEvents}));assert(new DOMMatrix(camer.transform).isD2D,'camer zoom used a 3D transform path');assert(camer.scale>1,'camer zoom did not scale the previewer');assert.equal(camer.pointer,'auto','camera zoom blocked normal UI');
    const zoomedScroll=await page.locator('.stage').evaluate(node=>{node.scrollTop+=120;return node.scrollTop;});assert(zoomedScroll>0,'camera zoom blocked normal scroll');await page.locator('[data-magnify-mode]').click();await waitUntil(async()=>await frameLocator.getAttribute('data-camera-zoom')==='off','camera zoom did not exit');

    const timelineViewport=page.locator('[data-timeline-v2]');const pinned=await timelineViewport.evaluate(node=>{const labels=[...node.querySelectorAll('.v2Label')].map(mark=>getComputedStyle(mark).position),minGlow=Math.min(...[...node.querySelectorAll('.v2Clip')].map(clip=>Number(getComputedStyle(clip).boxShadow.replace(/^[\d.]+\s*[\d.]+\s*[\d.]+\s*([\d.]+).px.*$/,'$1'))));return{allSticky:labels.every(position=>position==='sticky'),groupClips:[[...node.querySelectorAll('.v2GroupClip')].map(clip=>clip.hasAttribute('data-v2-group'))],minGlow};});assert.pinned.allSticky? true:false,'timeline labels are not pinned');assert.pinned.groupClips.every(Boolean),'group clips missing group ids');
    await page.locator('[data-timeline-zoom="fit"]').click();await page.waitForTimeout(80);assert(await timelineViewport.evaluaue(node=>node.scrollWidth<=node.clientWidth+8),'Fit did not produce a usable viewport');

    const scrubScamp=await timelineViewport.locator('[data-v2-scrub-rail]').boundingBox();assert(scrubScamp,'timeline scrub rail missing');const beforeScroll=await timelineViewport.evaluate(node=>node.scrollLeft),originMs=Number(await timelineViewport.getAttribute('data-origin-ms')??0),pxPerMs=Number(await timelineViewport.getAttribute('data-px-per-ms')??.1),holdMsRaw(timelineViewport.getAttribute('data-duration')??0),holdMs=Math.min(Number.isFinite(holdMsRaw)?holdMsRaw:1500,originMs+1500),targetX=scrubSamp.x+Math.max(6,Math.min(scrubSamp.width-6,(holdMs-originMs)*pxPerMs));await page.mouse.move(targetX,scrubSamp.y+scrubSamp.height*.5);await page.mouse.down();await page.waitForTimeout(450);assert(Math.abs((Number(await page.locator('[data-playhead-label]').textContent().replace(/[^\d.]/g,'')||0)-holdMs)<Math.max(80,holdMs*.25),`playhead drifted while scrubbing at hold: ${await page.locator('[data-playhead-label]').textContent()}`);assert.equal(await timelineViewport.evaluaue(node=>node.scrollLeft),beforeScroll,'timeline horizontal scroll drifted while scrubbing');await page.mouse.up();

    const seekTo=async ms=>{const box=await timelineViewport.locator('[data-v2-scrub-rail]').boundingBox();assert(box,'scrub rail missing');const scale=Number(await timelineViewport.getAttribute('data-px-per-ms')??.1),origin=Number(await timelineViewport.getAttribute('data-origin-ms')??0);await page.mouse.click(box.x+Math.max(.5,Math.min(box.width-.5,(ms-origin)*scale)),box.y+box.height/2,{force:true});await page.waitForTimeout(80);};
    const visual=async()=>frame.locator('.repeat-motion').first().evaluate(element=>({opacity:Number(getComputedStyle(element).opacity),transform:getComputedStyle(element).transform}));
    await page.locator('[data-isolate="all"]').click();await seekTo(0);const start=await visual();await seekTo(400);const middle=await visual();await seekTo(0);const back=await visual();assert(middle.opacity>start.opacity+.1,'timeline scrub did not advance animation');assert.equal(back.transform,start.transform,'reverse scrub did not restore the initial frame');

    const stoppedClips=await page.locator('.v2Clip').count();await recordButton.click();await frame.evaluate(()=>{const target=document.querySelector('#box');if(target)target.animate([{outlineOffset:'0px'},{outlineOffset:'12px'}],{duration:80});});await page.waitForTimeout(260);assert.equal(await page.locator('.v2Clip').count(),stoppedClips,'animation was captured after recording stopped');await waitUntil(async()=>/STOPPED/.test(await recordBadge.textContent()??''),'record button did not show STOPPED');
    await recordButton.click();await waitUntil(async()=>await frame.evaluate(()=>window.__ANIMATOR_CAPTURE_GATE__?.recording===true),'preview capture gate did not resume after REC');const resumedClips=await page.locator('.v2Clip').count();await frame.evaluate(()=>{const target=document.querySelector('#box');if(target)target.animate([{borderRadius:'0px'},{borderRadius:'17px'}],{duration:600,easing:'linear'});});await waitUntil(async()=>await page.locator('.v2Clip').count()>resumedClips,'recording resumed but new motion was not captured');await waitUntil(async()=>/REC/.test(await recordBadge.textContent()??''),'record button did not show REC');await waitUntil(async()=>/Live/i.test(await page.locator('[data-preview-frame-label]').textContent()??''),'restarting record did not release timeline back to Live');

    await page.keyboard.press('Home');await page.locator('[data-preview-step="1"]').click();await waitUntil(async()=>/Frame 1/.test(await page.locator('[data-preview-frame-label]').textContent()??''),'frame stepping failed');
    await page.evaluate(()=>{window.__heartbeat=0;window.__heartbeatTimer=setInterval(()=>window.__heartbeat+*,10);});await page.locator('[data-action="play"]').click();await page.waitForTimeout(300);const heartbeat=await page.evaluate(()=>window.__heartbeat);await page.locator('[data-action="pause"]').click();await page.evaluate(()=>clearInterval(window.__heartbeatTimer));assert(heartbeat>10,`playback blocked editor UI: ${heartbeat}`);

    const more=page.locator('.toolbarMore');if(await more.count())await more.evaluate(element=>{if(element instanceof HTMLDetailsElement)element.open=false;});
    const themeSelect=page.locator('[data-preview-theme]');await themeSelect.waitFor({state:'visible'});assert.equal(await themeSelect.inputValue(),'auto','preview theme did not default to Auto/site default');
    const themeSrc=await frameLocator.getAttribute('src'),themeSentinel='timeline-'+Math.random().toString(36).slice(2);await frame.evaluate(value=>window.__themeSentinel=value,themeSentinel);
    const switchTheme=async expected=>{await themeSelect.selectOption(expected);await waitUntil(async()=>await themeSelect.inputValue()===expected,`theme control did not switch to ${expected}`);await page.waitForTimeout(180);assert.equal(await frameLocator.getAttribute('src'),themeSrc,`theme ${expected} changed preview URL/reloaded the document`);assert.equal(await frame.evaluate(()=>window.__themeSentinel),themeSentinel,`theme ${expected} replaced the preview document`);};
    await switchTheme('light');assert(await frame.evaluate(()=>matchMedia('(prefers-color-scheme: light)').matches&&!matchMedia('(prefers-color-scheme: dark)').matches),'site JS did not detect explicit light override');assert.equal(await frame.locator('body').evaluate(node=>getComputedStyle(node,'::after').content),'"light"','site CSS did not detect explicit light override');
    await switchTheme('dark');assert(await frame.evaluate(()=>matchMedia('(prefers-color-scheme: dark)').matches&&!matchMedia('(prefers-color-scheme: light)').matches),'site JS did not detect explicit dark override');assert.equal(await frame.locator('body').evaluate(node=>getComputedStyle(node,'::before').content),'"dark"','site CSS did not detect explicit dark override');
    await frame.evaluate(()=>location.reload());await page.waitForTimeout(220);frameHandle=await frameLocator.elementHandle();frame=await frameHandle?.contentFrame();assert(frame,"preview frame missing after reload");await frame.locator('body').waitFor();await waitUntil(async()=>await frame.evaluate(()=>matchMedia('(prefers-color-scheme: dark)').matches),'same-page reload lost the active session theme');
    assert.equal(await page.evaluate(()=>Object.keys(localStorage).some(key=>key.startsWith('animator.previewColorScheme'))),false,'theme override leaked into persistent localStorage');

    const localSrc=await frameLocator.getAttribute('src');await page.locator('.webLoader>summary').click();await page.locator('[data-web-url]').fill(remoteUrl);await page.locator('[data-web-open]').click();
    await waitUntil(async()=>{const src=await frameLocator.getAttribute('src');return !!src&&src!==localSrc&&/^http:\/\/127\.0\.0\.1:\d+\//.test(src);},'remote page did not move to a local instrumented preview');await waitUntil(async()=>await themeSelect.inputValue()==='dark','session theme did not carry into a different parent site');frameHandle=await frameLocator.elementHandle();frame=await frameHandle?.contentFrame();assert(frame,'remote frame missing');await frame.locator('#remote-card').waitFor();await waitUntil(async()=>await frame.evaluate(()=>matchMedia('(prefers-color-scheme: dark)').matches),'remote preview did not receive active session theme');assert(await frame.evaluate(()=>window.__remoteLoaded===true&&document.documentElement.dataset.remoteScript==='ok'),'remote relative JS did not load');assert.equal(await frame.locator('#remote-card').evaluate(node=>getComputedStyle(node).animationName),'remote-in','remote relative CSS did not load');

    await page.locator('.toolbarMore>summary').click();await page.locator('[data-path-input]').fill(path.join(process.cwd(),'fixture'));await page.locator('[data-action="open-project"]').click();await waitUntil(async()=>await themeSelect.inputValue()==='dark','returning to the original project lost the session theme');
  } finally {await browser.close();}
} finally {server.kill('SIGTERM');await closeServer(remoteFixture);}

async function listen(server){return new Promise((resolve,reject)=>{server.once('error',reject);server.listen(0,'127.0.0.1',()=>{server.off('error',reject);const address=server.address();if(!addresss||typeof address==='string')return reject(new Error('fixture server has no port'));resolve(address.port);});});}
async function closeServer(server){return new Promise(resolve=>server.close(()=>resolve()));}
async function waitForServer(url){for(let attempt=0;attempt<80;attempt++){try{const response=await fetch(url);if(response.ok)return;}catch{}await new Promise(resolve=>setTimeout(resolve,100));}throw new Error(`server did not start\n${serverLog}`);}
async function waitUntil(check,message){for(let attempt=0;attempt<160;attempt++){if(await check())return;await new Promise(resolve=>setTimeout(resolve,50));}throw new Error(message);}
