import type {MotionTrack} from '../core/motion';
import {generateMotionCss,generateMotionOverrideFiles,generateMotionTs,generateMotionUnifiedDiff} from '../exporters/generate';
import {loadCustomPresets} from '../presets/custom';
import {presets} from '../presets/presets';
import {connectPreview,sendCommand} from '../preview/bridge';
import {store,type AnimatorState} from '../state/store';
import type {ProjectDescriptor,ProjectFile,StaticAnalysis} from '../types/domain';

type Tab='motion'|'source'|'export';
type Viewport={width:number;height:number};
type SourceState={path:string;text:string};
type UiState={pathInput:string;viewport:Viewport;source?:SourceState;tab:Tab;playbackRate:number;reducedMotion:boolean;applyDiff:string};
type Signatures={project:string;elements:string;right:string;preview:string;diagnostic:string};
type FrameGetter=()=>HTMLIFrameElement|null;

const rates=[.1,.25,.5,1,2,4];

export function mountApp(root:HTMLElement):()=>void{
  const ui:UiState={pathInput:localStorage.getItem('animator.last-project')??'',viewport:{width:1100,height:700},tab:'motion',playbackRate:1,reducedMotion:false,applyDiff:''};
  const sig:Signatures={project:'',elements:'',right:'',preview:'',diagnostic:''};
  let iframe:HTMLIFrameElement|null=null,bridgeCleanup:(()=>void)|undefined,previewKey='',disposed=false,raf=0;
  root.innerHTML=shell();
  const getFrame:FrameGetter=()=>iframe;
  const render=():void=>{
    raf=0;if(disposed)return;const state=store.get();
    updateToolbar(root,state,ui);updateProject(root,state,sig);updateElements(root,state,sig);updateRight(root,state,ui,sig);updateDiagnostic(root,state,sig);
    const key=state.project?`${state.project.id}:${state.project.selectedEntry}`:'',signature=`${key}:${ui.viewport.width}x${ui.viewport.height}:${state.analysis?.reducedMotion??false}`;
    if(signature===sig.preview)return;sig.preview=signature;
    const device=root.querySelector<HTMLElement>('[data-device]'),chrome=root.querySelector<HTMLElement>('[data-preview-chrome]');
    if(device){const scale=Math.min(1,900/ui.viewport.width,620/ui.viewport.height);device.style.width=`${ui.viewport.width}px`;device.style.height=`${ui.viewport.height}px`;device.style.transform=`scale(${scale})`;}
    if(chrome)chrome.innerHTML=previewChrome(state.project,state.analysis,ui.reducedMotion);
    if(key===previewKey)return;bridgeCleanup?.();iframe?.remove();iframe=null;previewKey=key;
    if(state.project?.browserSessionId)bridgeCleanup=connectPreview(null);else if(device&&state.project){if(window.animatorDesktop)bridgeCleanup=connectPreview(null);else{iframe=document.createElement('iframe');iframe.dataset.previewFrame='';iframe.title='Project preview';iframe.src=previewUrl(state.project);device.appendChild(iframe);bridgeCleanup=connectPreview(iframe);}}
  };
  const requestRender=():void=>{if(!disposed&&!raf)raf=requestAnimationFrame(render);};
  const click=(event:MouseEvent)=>onClick(event,root,ui,getFrame,requestRender),change=(event:Event)=>onChange(event,ui,getFrame,requestRender),input=(event:Event)=>onInput(event,ui);
  root.addEventListener('click',click);root.addEventListener('change',change);root.addEventListener('input',input);const unsubscribe=store.subscribe(requestRender);render();
  return()=>{disposed=true;if(raf)cancelAnimationFrame(raf);bridgeCleanup?.();unsubscribe();root.removeEventListener('click',click);root.removeEventListener('change',change);root.removeEventListener('input',input);root.replaceChildren();};
}

function shell():string{return `<div class="app">
  <header class="toolbar"><b>Animator</b><button data-action="pick-folder">Open folder…</button><input class="path" data-path-input placeholder="Or enter local project path"><button data-action="open-project">Open path</button><span class="sep"></span><button data-action="picker">Pick element</button><button data-action="record">Record</button><span class="sep"></span><button data-action="previous-event">◀|</button><button data-action="restart">↺</button><button data-action="play">▶</button><button data-action="pause">Ⅱ</button><button data-action="next-event">|▶</button><select data-playback-rate>${rates.map(rate=>`<option value="${rate}">${rate}x</option>`).join('')}</select><label class="toolbarToggle"><input type="checkbox" data-reduced-motion> Reduced</label><button data-action="clear-overrides">Clear overrides</button><button data-action="undo">Undo</button><button data-action="redo">Redo</button><span class="grow"></span><select data-viewport><option value="390">Mobile</option><option value="768">Tablet</option><option value="1100" selected>Desktop</option></select><span data-viewport-label>1100×700</span></header>
  <main class="workspace"><aside class="leftPanel"><section data-project-region></section><section data-motion-region></section><section class="elementList" data-elements-region></section></aside><section class="previewArea"><div class="previewChrome" data-preview-chrome><span>No preview</span></div><div class="stage"><div class="device" data-device></div></div></section><aside class="rightPanel"><nav>${(['motion','source','export'] as const).map(tab=>`<button data-tab="${tab}" class="${tab==='motion'?'active':''}">${capitalize(tab)}</button>`).join('')}</nav><div data-right-region></div></aside></main>
  <section class="timeline"><div class="timelineTop"><b>Timeline</b><span data-playhead-label>0 ms</span><input data-zoom type="range" min="0.5" max="4" step="0.25" value="1"><span class="muted">drag playhead/keyframes</span></div><div class="timelineScroll"><div class="timelineCanvas" data-timeline data-duration="1000" data-px-per-ms="0.1" data-timeline-origin="0"><div class="ruler" data-ruler></div><div class="tracks" data-tracks></div><div class="eventTrack" data-event-track></div><div class="playhead" data-playhead></div></div></div></section><div class="diagnostics" data-diagnostic hidden></div>
</div>`;}

function updateToolbar(root:HTMLElement,state:AnimatorState,ui:UiState):void{const picker=root.querySelector<HTMLButtonElement>('[data-action="picker"]'),record=root.querySelector<HTMLButtonElement>('[data-action="record"]'),path=root.querySelector<HTMLInputElement>('[data-path-input]'),rate=root.querySelector<HTMLSelectElement>('[data-playback-rate]'),viewport=root.querySelector<HTMLSelectElement>('[data-viewport]'),label=root.querySelector<HTMLElement>('[data-viewport-label]'),reduced=root.querySelector<HTMLInputElement>('[data-reduced-motion]');picker?.classList.toggle('active',state.picker);if(record){record.classList.toggle('active',state.recording);record.textContent=state.recording?'Recording':'Record';}if(path&&document.activeElement!==path)path.value=ui.pathInput;if(rate)rate.value=String(ui.playbackRate);if(viewport)viewport.value=String(ui.viewport.width);if(label)label.textContent=`${ui.viewport.width}×${ui.viewport.height}`;if(reduced)reduced.checked=ui.reducedMotion;}
function updateProject(root:HTMLElement,state:AnimatorState,sig:Signatures):void{const signature=state.project?`${state.project.id}:${state.project.root}:${state.project.tree.length}`:'none';if(signature===sig.project)return;sig.project=signature;const region=root.querySelector<HTMLElement>('[data-project-region]');if(region)region.innerHTML=`<h3>Project</h3>${state.project?`<div class="projectRoot" title="${attr(state.project.root)}">${html(state.project.root)}</div>${renderTree(state.project.tree)}`:'<p class="muted">Open a local project folder.</p>'}`;}
function updateElements(root:HTMLElement,state:AnimatorState,sig:Signatures):void{const signature=`${state.selectedElementId??''}|${state.elements.map(element=>`${element.id}:${element.alive?1:0}`).join(',')}`;if(signature===sig.elements)return;sig.elements=signature;const region=root.querySelector<HTMLElement>('[data-elements-region]');if(region)region.innerHTML=`<h3>Elements <small>${state.elements.length}</small></h3>${state.elements.slice(0,300).map(element=>`<button class="row${state.selectedElementId===element.id?' selected':''}" data-element-id="${attr(element.id)}"><code>${html(element.tag)}</code>${element.domId?`#${html(element.domId)}`:''}${element.classes[0]?`.${html(element.classes[0])}`:''}</button>`).join('')}`;}
function updateRight(root:HTMLElement,state:AnimatorState,ui:UiState,sig:Signatures):void{root.querySelectorAll<HTMLElement>('[data-tab]').forEach(button=>button.classList.toggle('active',button.dataset.tab===ui.tab));const selected=selectMotionTrack(state),signature=`${ui.tab}|${state.selectedElementId??''}|${selected?`${selected.id}:${selected.timing.duration??''}:${selected.timing.delay??''}:${selected.timing.easing??''}:${JSON.stringify(selected.keyframes)}`:''}|${ui.source?.path??''}:${ui.source?.text.length??0}|${ui.applyDiff.length}`;if(signature===sig.right)return;sig.right=signature;const region=root.querySelector<HTMLElement>('[data-right-region]');if(!region)return;if(ui.tab==='motion'){region.innerHTML='';return;}region.innerHTML=ui.tab==='source'?sourcePanel(ui.source,selected):exportPanel(selected,ui.applyDiff);}
function updateDiagnostic(root:HTMLElement,state:AnimatorState,sig:Signatures):void{const message=state.diagnostics.at(-1)??'';if(message===sig.diagnostic)return;sig.diagnostic=message;const region=root.querySelector<HTMLElement>('[data-diagnostic]');if(region){region.hidden=!message;region.textContent=message;}}
function previewChrome(project:ProjectDescriptor|undefined,analysis:StaticAnalysis|undefined,reduced:boolean):string{const pages=project?`<select data-entry>${project.entries.map(entry=>`<option value="${attr(entry)}"${entry===project.selectedEntry?' selected':''}>${html(entry)}</option>`).join('')}</select>`:'<span>No preview</span>';return `${pages}<span>${reduced?'Reduced motion emulated':analysis?.reducedMotion?'Project has reduced-motion CSS':'Normal motion'}</span>`;}
function previewUrl(project:ProjectDescriptor):string{return `/preview/${encodeURIComponent(project.id)}/${project.selectedEntry.split('/').map(encodeURIComponent).join('/')}`;}
function renderTree(nodes:ProjectFile[]):string{return `<div class="tree">${nodes.map(node=>node.type==='directory'?`<details><summary>${html(node.name)}</summary>${node.children?renderTree(node.children):''}</details>`:`<button data-file="${attr(node.path)}">${html(node.name)}</button>`).join('')}</div>`;}
function sourcePanel(source:SourceState|undefined,selected:MotionTrack|undefined):string{const reference=selected?.source.reference,open=reference?`<button data-file="${attr(reference.file)}">Open ${html(reference.file)}:${reference.line??'?'}</button>`:'';return `<div class="sourceView">${open}<h3>${html(source?.path??'Source')}</h3><pre>${html(source?.text??reference?.snippet??'Select a file or source-correlated animation.')}</pre></div>`;}
function exportPanel(selected:MotionTrack|undefined,applyDiff:string):string{const generated=selected?{css:generateMotionCss(selected),ts:generateMotionTs(selected),diff:generateMotionUnifiedDiff(selected)}:{css:'',ts:'',diff:''},reference=selected?.source.reference,safe=!!reference?.file.endsWith('.css')&&!!reference.selector&&(selected?.source.confidence==='exact'||selected?.source.confidence==='source-correlated');return `<div class="exportView"><h3>Generated change</h3><div class="actions"><button data-copy="css">Copy CSS</button><button data-copy="ts">Copy TS</button><button data-copy="diff">Copy diff</button><button data-action="write-overrides">Write override files</button>${safe?'<button data-action="preview-apply">Preview apply</button><button data-action="apply-source">Apply to CSS</button>':''}</div>${safe?'<p class="muted">Direct apply creates a .animator-backup.</p>':''}<h4>Proposed diff</h4><pre data-generated="diff">${html(applyDiff||generated.diff||'Select an animation.')}</pre><h4>CSS</h4><pre data-generated="css">${html(generated.css||'Select an animation.')}</pre><h4>TypeScript</h4><pre data-generated="ts">${html(generated.ts||'Select an animation.')}</pre></div>`;}

function onClick(event:MouseEvent,root:HTMLElement,ui:UiState,getFrame:FrameGetter,render:()=>void):void{const target=(event.target as Element|null)?.closest<HTMLElement>('button,[data-tab]');if(!target)return;const action=target.dataset.action;if(action==='pick-folder'){void pickFolder(ui);return;}if(action==='open-project'){void openProject(ui);return;}if(action==='picker'){const enabled=!store.get().picker;store.set({picker:enabled});sendCommand(getFrame(),{type:'SET_PICKER',enabled});return;}if(action==='record'){const enabled=!store.get().recording;store.set({recording:enabled});sendCommand(getFrame(),{type:'SET_RECORDING',enabled});return;}if(action==='undo'){store.undo();syncSelectedToPreview(getFrame());return;}if(action==='redo'){store.redo();syncSelectedToPreview(getFrame());return;}if(action==='clear-overrides'){sendCommand(getFrame(),{type:'CLEAR_OVERRIDES'});return;}if(action==='previous-event'){jump(-1,getFrame());return;}if(action==='next-event'){jump(1,getFrame());return;}if(action==='restart'){store.set({playhead:0});sendCommand(getFrame(),{type:'RESTART_ALL'});return;}if(action==='play'){sendCommand(getFrame(),{type:'PLAY_ALL'});return;}if(action==='pause'){sendCommand(getFrame(),{type:'PAUSE_ALL'});return;}if(action==='write-overrides'){void writeOverrides();return;}if(action==='create-animation'){const elementId=store.get().selectedElementId;if(elementId)sendCommand(getFrame(),{type:'CREATE_ANIMATION',elementId,keyframes:[{offset:0,opacity:0,transform:'translateY(24px)'},{offset:1,opacity:1,transform:'translateY(0px)'}],duration:400,easing:'ease-out',fill:'both'});return;}if(action==='preview-apply'){void previewApply(ui);return;}if(action==='apply-source'){void applySource(ui);return;}if(target.dataset.tab){ui.tab=target.dataset.tab as Tab;render();return;}if(target.dataset.file){void openFile(target.dataset.file,ui);return;}if(target.dataset.elementId){store.set({selectedElementId:target.dataset.elementId});return;}if(target.dataset.animationId){store.set({selectedAnimationId:target.dataset.animationId});return;}if(target.dataset.copy){const element=root.querySelector<HTMLElement>(`[data-generated="${target.dataset.copy}"]`);if(element)void navigator.clipboard.writeText(element.textContent??'');}}
function onChange(event:Event,ui:UiState,getFrame:FrameGetter,render:()=>void):void{const target=event.target;if(!(target instanceof HTMLInputElement||target instanceof HTMLSelectElement))return;if(target.matches('[data-playback-rate]')){ui.playbackRate=Number(target.value);sendCommand(getFrame(),{type:'SET_ALL_PLAYBACK_RATE',rate:ui.playbackRate});return;}if(target instanceof HTMLInputElement&&target.matches('[data-reduced-motion]')){ui.reducedMotion=target.checked;sendCommand(getFrame(),{type:'SET_REDUCED_MOTION',enabled:ui.reducedMotion});render();return;}if(target.matches('[data-viewport]')){const width=Number(target.value);ui.viewport=width===390?{width:390,height:844}:width===768?{width:768,height:1024}:{width:1100,height:700};render();return;}if(target.matches('[data-entry]')){const project=store.get().project;if(project)store.set({project:{...project,selectedEntry:target.value},motionTracks:[],events:[],elements:[],playhead:0});return;}if(target instanceof HTMLSelectElement&&target.matches('[data-preset]')){if(store.get().selectedAnimationId)return;const elementId=store.get().selectedElementId,preset=[...presets,...loadCustomPresets()].find(item=>item.id===target.value);if(elementId&&preset)sendCommand(getFrame(),{type:'CREATE_ANIMATION',elementId,keyframes:preset.keyframes,duration:preset.duration,easing:preset.easing,fill:'both'});target.value='';return;}if(target instanceof HTMLInputElement&&target.matches('[data-zoom]'))store.set({zoom:Number(target.value)});}
function onInput(event:Event,ui:UiState):void{const target=event.target;if(target instanceof HTMLInputElement&&target.matches('[data-path-input]'))ui.pathInput=target.value;}
function jump(direction:-1|1,frame:HTMLIFrameElement|null):void{const state=store.get(),events=[...state.events].sort((a,b)=>a.at-b.at),match=direction>0?events.find(event=>event.at>state.playhead+.5):[...events].reverse().find(event=>event.at<state.playhead-.5);if(match){store.set({playhead:match.at});sendCommand(frame,{type:'SCRUB_TIMELINE',time:match.at});}}
function syncSelectedToPreview(frame:HTMLIFrameElement|null):void{const track=selectMotionTrack(store.get());if(!track)return;sendCommand(frame,{type:'APPLY_OVERRIDE',animationId:track.id,duration:track.timing.duration,delay:track.timing.delay,easing:track.timing.easing,keyframes:track.keyframes.length?track.keyframes.map(keyframe=>({...keyframe.values,...(keyframe.offset!==undefined?{offset:keyframe.offset}:{}),...(keyframe.easing!==undefined?{easing:keyframe.easing}:{}),...(keyframe.composite!==undefined?{composite:keyframe.composite}:{})})):undefined});}

async function pickFolder(ui:UiState):Promise<void>{try{const response=await fetch('/api/projects/pick-folder',{method:'POST'});if(response.status===204)return;const body=await response.json() as ProjectDescriptor&{error?:string};if(!response.ok)return diagnostic(body.error??'Folder selection failed');ui.pathInput=body.root;localStorage.setItem('animator.last-project',body.root);await activateProject(body);}catch(error){diagnostic(String(error));}}
async function openProject(ui:UiState):Promise<void>{if(!ui.pathInput.trim())return diagnostic('Enter a local project path or choose Open folder…');try{const response=await fetch('/api/projects/open',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({path:ui.pathInput})}),body=await response.json() as ProjectDescriptor&{error?:string};if(!response.ok)return diagnostic(body.error??'Open failed');localStorage.setItem('animator.last-project',body.root);await activateProject(body);}catch(error){diagnostic(String(error));}}
async function activateProject(project:ProjectDescriptor):Promise<void>{store.set({project,analysis:undefined,motionTracks:[],events:[],elements:[],selectedElementId:undefined,selectedAnimationId:undefined,playhead:0});const response=await fetch(`/api/projects/${project.id}/analysis`);if(!response.ok)return diagnostic('Static analysis failed');const analysis=await response.json() as StaticAnalysis;store.set({analysis,motionTracks:analysis.motionTracks});}
async function openFile(file:string,ui:UiState):Promise<void>{const project=store.get().project;if(!project)return;try{const response=await fetch(`/api/projects/${project.id}/source?path=${encodeURIComponent(file)}`);ui.source={path:file,text:await response.text()};ui.tab='source';store.touch();}catch(error){diagnostic(String(error));}}
async function writeOverrides():Promise<void>{const state=store.get();if(!state.project)return;try{const output=generateMotionOverrideFiles(state.motionTracks.filter(track=>track.source.confidence!=='unknown')),response=await fetch(`/api/projects/${state.project.id}/export-overrides`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(output)}),body=await response.json() as{cssPath?:string;error?:string};diagnostic(response.ok?`Overrides written: ${body.cssPath??'.animator'}`:body.error??'Export failed');}catch(error){diagnostic(String(error));}}
async function previewApply(ui:UiState):Promise<void>{const state=store.get(),selected=selectMotionTrack(state),reference=selected?.source.reference;if(!state.project||!selected||!reference?.file||!reference.selector)return;const response=await fetch(`/api/projects/${state.project.id}/preview-css-apply`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({file:reference.file,selector:reference.selector,duration:selected.timing.duration,delay:selected.timing.delay,easing:selected.timing.easing})}),body=await response.json() as{before?:string;after?:string;file?:string;error?:string};if(!response.ok)return diagnostic(body.error??'Could not preview apply');ui.applyDiff=simpleDiff(body.before??'',body.after??'',body.file??reference.file);ui.tab='export';store.touch();}
async function applySource(ui:UiState):Promise<void>{const state=store.get(),selected=selectMotionTrack(state),reference=selected?.source.reference;if(!state.project||!selected||!reference?.file||!reference.selector)return;await previewApply(ui);if(!confirm(`Apply timing changes to ${reference.file}? A backup will be created.`))return;const response=await fetch(`/api/projects/${state.project.id}/apply-css`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({file:reference.file,selector:reference.selector,duration:selected.timing.duration,delay:selected.timing.delay,easing:selected.timing.easing})}),body=await response.json() as{file?:string;backup?:string;error?:string};diagnostic(response.ok?`Applied to ${body.file}; backup: ${body.backup}`:body.error??'Apply failed');}
function simpleDiff(before:string,after:string,file:string):string{const previous=before.split('\n'),next=after.split('\n'),out=[`--- ${file}`,`+++ ${file}`],max=Math.max(previous.length,next.length);for(let index=0;index<max;index++){if(previous[index]===next[index])continue;if(previous[index]!==undefined)out.push(`-${previous[index]}`);if(next[index]!==undefined)out.push(`+${next[index]}`);}return out.join('\n');}
function selectMotionTrack(state:AnimatorState):MotionTrack|undefined{return state.motionTracks.find(track=>track.id===state.selectedAnimationId)??state.motionTracks.find(track=>track.target.elementId===state.selectedElementId);}
function diagnostic(message:string):void{store.set({diagnostics:[...store.get().diagnostics,message]});}
function capitalize(value:string):string{return value.charAt(0).toUpperCase()+value.slice(1);}
function html(value:string):string{return value.replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[char]??char);}
function attr(value:string):string{return html(value);}