import { useEffect, useMemo, useRef, useState } from 'react';
import { connectPreview, sendCommand } from '../preview/bridge';
import { store, useStore } from '../state/store';
import { presets } from '../presets/presets';
import { generateCss, generateOverrideFiles, generateTs, generateUnifiedDiff } from '../exporters/generate';
import { timelineDuration, timeToPercent } from '../utils/timeline';
import type { DetectedAnimation, ProjectDescriptor, ProjectFile, StaticAnalysis } from '../types/domain';

const fixtureDefault = '__fixture__';
export function App(){
  const iframe=useRef<HTMLIFrameElement>(null); const project=useStore(s=>s.project); const animations=useStore(s=>s.animations); const events=useStore(s=>s.events); const elements=useStore(s=>s.elements); const selectedElementId=useStore(s=>s.selectedElementId); const selectedAnimationId=useStore(s=>s.selectedAnimationId); const picker=useStore(s=>s.picker); const playhead=useStore(s=>s.playhead); const zoom=useStore(s=>s.zoom); const diagnostics=useStore(s=>s.diagnostics); const analysis=useStore(s=>s.analysis);
  const [pathInput,setPathInput]=useState(fixtureDefault); const [viewport,setViewport]=useState({width:1100,height:700}); const [source,setSource]=useState<{path:string;text:string}>(); const [tab,setTab]=useState<'motion'|'source'|'export'>('motion');
  useEffect(()=>{const frame=iframe.current;if(!frame)return;return connectPreview(frame);},[project?.id]);
  useEffect(()=>{if(!project)return;fetch(`/api/projects/${project.id}/analysis`).then(r=>r.json()).then((a:StaticAnalysis)=>{store.set({analysis:a}); for(const x of a.animations as DetectedAnimation[])store.addAnimation(x);}).catch(e=>store.set({diagnostics:[...store.get().diagnostics,String(e)]}));},[project?.id]);
  const selected=animations.find(a=>a.id===selectedAnimationId) ?? animations.find(a=>a.elementId===selectedElementId); const duration=timelineDuration(animations,events);
  async function openProject(){const r=await fetch('/api/projects/open',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({path:pathInput})});const body=await r.json();if(!r.ok){store.set({diagnostics:[...diagnostics,body.error??'Open failed']});return;}store.set({project:body as ProjectDescriptor,animations:[],events:[],elements:[],selectedElementId:undefined,selectedAnimationId:undefined});}
  async function openFile(file:string){if(!project)return;const r=await fetch(`/api/projects/${project.id}/source?path=${encodeURIComponent(file)}`);setSource({path:file,text:await r.text()});setTab('source');}
  function togglePicker(){const next=!picker;store.set({picker:next});sendCommand(iframe.current,{type:'SET_PICKER',enabled:next});}
  function scrub(value:number){store.set({playhead:value}); if(selected)sendCommand(iframe.current,{type:'SET_ANIMATION_TIME',id:selected.id,time:Math.max(0,value-selected.startTime)});}
  function editAnimation(patch:Partial<DetectedAnimation>){if(!selected)return;store.updateAnimation(selected.id,patch);sendCommand(iframe.current,{type:'APPLY_OVERRIDE',animationId:selected.id,duration:patch.duration??selected.duration,easing:patch.easing??selected.easing,keyframes:patch.keyframes??selected.keyframes});}
  function createFromPreset(id:string){const p=presets.find(x=>x.id===id);if(!p||!selectedElementId)return;sendCommand(iframe.current,{type:'CREATE_ANIMATION',elementId:selectedElementId,keyframes:p.keyframes,duration:p.duration,easing:p.easing});}
  const generated=useMemo(()=>selected?{css:generateCss(selected),ts:generateTs(selected),diff:generateUnifiedDiff(selected)}:{css:'',ts:'',diff:''},[selected]);
  async function exportOverrides(){if(!project)return;const out=generateOverrideFiles(animations.filter(a=>a.confidence!=='unknown'));const r=await fetch(`/api/projects/${project.id}/export-overrides`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(out)});const body=await r.json();store.set({diagnostics:[...store.get().diagnostics,r.ok?`Overrides written: ${body.cssPath}`:body.error]});}
  return <div className="app">
    <header className="toolbar"><b>Animator</b><input className="path" value={pathInput} onChange={e=>setPathInput(e.target.value)} placeholder="Local project path"/><button onClick={openProject}>Open project</button><span className="sep"/><button className={picker?'active':''} onClick={togglePicker}>Pick element</button><button onClick={()=>{const next=!store.get().recording;store.set({recording:next});sendCommand(iframe.current,{type:'SET_RECORDING',enabled:next});}}>{store.get().recording?'Recording':'Record'}</button><span className="sep"/><button onClick={()=>selected&&sendCommand(iframe.current,{type:'RESTART_ANIMATION',id:selected.id})}>↺</button><button onClick={()=>selected&&sendCommand(iframe.current,{type:'PLAY_ANIMATION',id:selected.id})}>▶</button><button onClick={()=>selected&&sendCommand(iframe.current,{type:'PAUSE_ANIMATION',id:selected.id})}>Ⅱ</button><button onClick={store.undo}>Undo</button><button onClick={store.redo}>Redo</button><span className="grow"/><select value={viewport.width} onChange={e=>{const w=Number(e.target.value);setViewport(w===390?{width:390,height:844}:w===768?{width:768,height:1024}:{width:1100,height:700});}}><option value={390}>Mobile</option><option value={768}>Tablet</option><option value={1100}>Desktop</option></select><span>{viewport.width}×{viewport.height}</span></header>
    <main className="workspace">
      <aside className="leftPanel"><section><h3>Project</h3>{project?<Tree nodes={project.tree} onOpen={openFile}/>:<p className="muted">Open a local project. The included fixture path is prefilled.</p>}</section><section className="elementList"><h3>Elements <small>{elements.length}</small></h3>{elements.slice(0,300).map(el=><button key={el.id} className={selectedElementId===el.id?'row selected':'row'} onClick={()=>store.set({selectedElementId:el.id})}><code>{el.tag}</code>{el.domId&&`#${el.domId}`}{el.classes[0]&&`.${el.classes[0]}`}</button>)}</section></aside>
      <section className="previewArea"><div className="previewChrome">{project?<select value={project.selectedEntry} onChange={e=>store.set({project:{...project,selectedEntry:e.target.value}})}>{project.entries.map(entry=><option key={entry}>{entry}</option>)}</select>:<span>No preview</span>}<span>{analysis?.reducedMotion?'Reduced motion CSS detected':'Normal motion'}</span></div><div className="stage"><div className="device" style={{width:viewport.width,height:viewport.height,transform:`scale(${Math.min(1,900/viewport.width,620/viewport.height)})`}}>{project&&<iframe ref={iframe} src={`/preview/${project.id}/${project.selectedEntry}`} title="Project preview"/>}</div></div></section>
      <aside className="rightPanel"><nav><button className={tab==='motion'?'active':''} onClick={()=>setTab('motion')}>Motion</button><button className={tab==='source'?'active':''} onClick={()=>setTab('source')}>Source</button><button className={tab==='export'?'active':''} onClick={()=>setTab('export')}>Export</button></nav>{tab==='motion'?<MotionInspector selected={selected} onEdit={editAnimation} onPreset={createFromPreset} hasElement={!!selectedElementId}/>:tab==='source'?<SourceView source={source} selected={selected} onOpen={openFile}/>:<ExportView generated={generated} onWrite={exportOverrides}/>}</aside>
    </main>
    <Timeline animations={animations} events={events} duration={duration} playhead={playhead} zoom={zoom} onScrub={scrub}/>
    {diagnostics.length>0&&<div className="diagnostics">{diagnostics.at(-1)}</div>}
  </div>;
}
function Tree({nodes,onOpen}:{nodes:ProjectFile[];onOpen:(p:string)=>void}){return <div className="tree">{nodes.map(n=><div key={n.path}>{n.type==='directory'?<details><summary>{n.name}</summary>{n.children&&<Tree nodes={n.children} onOpen={onOpen}/>}</details>:<button onClick={()=>onOpen(n.path)}>{n.name}</button>}</div>)}</div>}
function MotionInspector({selected,onEdit,onPreset,hasElement}:{selected?:DetectedAnimation;onEdit:(p:Partial<DetectedAnimation>)=>void;onPreset:(id:string)=>void;hasElement:boolean}){return <div className="inspector"><h3>{selected?.name||selected?.type||'No animation selected'}</h3>{selected&&<><div className="badges"><span>{selected.type}</span><span>{selected.confidence}</span></div><label>Duration <input type="range" min="50" max="5000" step="10" value={selected.duration??400} onChange={e=>onEdit({duration:Number(e.target.value)})}/><input type="number" value={selected.duration??400} onChange={e=>onEdit({duration:Number(e.target.value)})}/> ms</label><label>Delay <input type="number" value={selected.delay??0} onChange={e=>onEdit({delay:Number(e.target.value)})}/> ms</label><label>Easing <select value={selected.easing??'ease'} onChange={e=>onEdit({easing:e.target.value})}><option>linear</option><option>ease</option><option>ease-in</option><option>ease-out</option><option>ease-in-out</option><option value="cubic-bezier(.2,.8,.2,1)">cubic-bezier(.2,.8,.2,1)</option><option value="steps(4,end)">steps(4,end)</option></select></label><h4>Properties</h4>{selected.properties.length?selected.properties.map(p=><div className="prop" key={p.name}><code>{p.name}</code><span>{p.values?.join(' → ')||`${p.from??'?'} → ${p.to??'?'}`}</span></div>):<p className="muted">No normalized property values available.</p>}</>}
    <h4>Create / presets</h4><select disabled={!hasElement} defaultValue="" onChange={e=>onPreset(e.target.value)}><option value="" disabled>Apply editable preset…</option>{presets.map(p=><option value={p.id} key={p.id}>{p.label}</option>)}</select>{!hasElement&&<p className="muted">Pick an element first.</p>}</div>}
function SourceView({source,selected,onOpen}:{source?:{path:string;text:string};selected?:DetectedAnimation;onOpen:(p:string)=>void}){return <div className="sourceView">{selected?.source&&<button onClick={()=>onOpen(selected.source!.file)}>Open {selected.source.file}:{selected.source.line??'?'}</button>}<h3>{source?.path??'Source'}</h3><pre>{source?.text??selected?.source?.snippet??'Select a file or a source-correlated animation.'}</pre></div>}
function ExportView({generated,onWrite}:{generated:{css:string;ts:string;diff:string};onWrite:()=>void}){const copy=(s:string)=>navigator.clipboard.writeText(s);return <div className="exportView"><h3>Generated change</h3><div className="actions"><button onClick={()=>copy(generated.css)}>Copy CSS</button><button onClick={()=>copy(generated.ts)}>Copy TS</button><button onClick={()=>copy(generated.diff)}>Copy diff</button><button onClick={onWrite}>Write override files</button></div><h4>Proposed diff</h4><pre>{generated.diff||'Select an animation.'}</pre><h4>CSS</h4><pre>{generated.css||'Select an animation.'}</pre><h4>TypeScript</h4><pre>{generated.ts||'Select an animation.'}</pre></div>}
function Timeline({animations,events,duration,playhead,zoom,onScrub}:{animations:DetectedAnimation[];events:import('../types/domain').TimelineEvent[];duration:number;playhead:number;zoom:number;onScrub:(v:number)=>void}){
  const width=Math.max(100,duration*zoom/10); return <section className="timeline"><div className="timelineTop"><b>Timeline</b><span>{Math.round(playhead)} ms</span><input type="range" min="0.5" max="4" step="0.25" value={zoom} onChange={e=>store.set({zoom:Number(e.target.value)})}/></div><div className="timelineScroll"><div className="timelineCanvas" style={{width}} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);const r=e.currentTarget.getBoundingClientRect();onScrub((e.clientX-r.left)/r.width*duration)}} onPointerMove={e=>{if(!e.currentTarget.hasPointerCapture(e.pointerId))return;const r=e.currentTarget.getBoundingClientRect();onScrub((e.clientX-r.left)/r.width*duration)}}><div className="ruler">{Array.from({length:11},(_,i)=><span key={i} style={{left:`${i*10}%`}}>{Math.round(duration*i/10)}ms</span>)}</div><div className="tracks">{animations.slice(0,80).map(a=><button className="track" key={a.id} onClick={()=>store.set({selectedAnimationId:a.id})}><span className="trackLabel">{a.name||a.type}</span><span className="clip" style={{left:`${timeToPercent(a.startTime,duration)}%`,width:`${Math.max(.8,timeToPercent((a.duration??100),duration))}%`}}/></button>)}<div className="eventTrack">{events.slice(-200).map(ev=><i key={ev.id} title={ev.label} style={{left:`${timeToPercent(ev.at,duration)}%`}}/>)}</div></div><div className="playhead" style={{left:`${timeToPercent(playhead,duration)}%`}}/></div></div></section>
}
