import { store } from '../state/store';
import type { DetectedAnimation, RuntimeElement } from '../types/domain';

type MotionSnapshot={elements:RuntimeElement[];animations:DetectedAnimation[];active:number;runtimeReady:boolean};
type BrowserState={url:string;title:string;width:number;height:number;engine:string;profile:string;external:boolean;recording:boolean;closed:boolean;snapshotReady:boolean;snapshotStatus:'idle'|'capturing'|'ready'|'error';snapshotVersion:number;checkpointReady:boolean;snapshotError?:string};

export function mountBrowserPreview(root:HTMLElement):()=>void{
  const device=root.querySelector<HTMLElement>('[data-device]'),stage=device?.parentElement;if(!device||!stage)return()=>{};
  let sessionId='',surface:HTMLDivElement|null=null,disposed=false,stateTimer=0,motionTimer=0,motionBusy=false,lastWidth=1100,lastHeight=700,runtimeHealthy=false,lastUrl='',lastState:BrowserState|null=null,lastSnapshotVersion=-1,lastGuardState='';
  const motionSignatures=new Map<string,string>(),motionElements=new Set<string>();
  const applyDeviceSize=(width:number,height:number):void=>{const safeWidth=Math.max(1,width),safeHeight=Math.max(1,height),availableWidth=Math.max(1,stage.clientWidth),availableHeight=Math.max(1,stage.clientHeight),scale=Math.min(1,availableWidth/safeWidth,availableHeight/safeHeight);device.dataset.browserDevice='';device.style.setProperty('--browser-device-width',`${safeWidth}px`);device.style.setProperty('--browser-device-height',`${safeHeight}px`);device.style.setProperty('--browser-device-scale',String(scale));};
  const resetDeviceSize=():void=>{delete device.dataset.browserDevice;device.style.removeProperty('--browser-device-width');device.style.removeProperty('--browser-device-height');device.style.removeProperty('--browser-device-scale');};
  const nextMotionDelay=():number=>runtimeHealthy?4000:650;
  const nextStateDelay=():number=>lastState?.recording?120:lastState?.snapshotReady?600:180;
  const scheduleMotion=(delay=nextMotionDelay()):void=>{if(disposed||!sessionId)return;if(motionTimer)clearTimeout(motionTimer);motionTimer=window.setTimeout(()=>{motionTimer=0;void pollMotion();},delay);};
  const applyMotion=(snapshot:MotionSnapshot):void=>{runtimeHealthy=snapshot.runtimeReady;if(surface){surface.dataset.browserMotion=String(snapshot.animations.length);surface.dataset.browserRuntime=String(snapshot.runtimeReady);}if(!store.get().recording)return;const freshElements=snapshot.elements.filter(element=>{if(motionElements.has(element.id))return false;motionElements.add(element.id);return true;});if(freshElements.length)store.upsertElements(freshElements);for(const animation of snapshot.animations){const signature=JSON.stringify([animation.type,animation.name,animation.startTime,animation.duration,animation.delay,animation.iterations,animation.direction,animation.easing,animation.fill,animation.runtimeState,animation.properties.map(property=>property.name),animation.keyframes?.map(frame=>frame.offset)]);if(motionSignatures.get(animation.id)===signature)continue;motionSignatures.set(animation.id,signature);store.addAnimation(animation);}};
  const pollMotion=async():Promise<void>=>{if(disposed||!sessionId||motionBusy||!store.get().recording)return;const requestedSession=sessionId;motionBusy=true;try{const response=await fetch(`/api/browser-sessions/${encodeURIComponent(requestedSession)}/motion`,{cache:'no-store'});if(response.ok&&requestedSession===sessionId&&store.get().recording)applyMotion(await response.json() as MotionSnapshot);}catch{}finally{motionBusy=false;if(!disposed&&requestedSession===sessionId&&store.get().recording)scheduleMotion();}};
  const syncReconstructionGuard=(state:BrowserState):void=>{if(!sessionId||state.closed)return;const enabled=state.recording?!state.checkpointReady:true,mode=state.recording?'preparing':state.snapshotReady?'complete':'finalizing',key=`${enabled}:${mode}`;if(key===lastGuardState)return;lastGuardState=key;void fetch(`/api/browser-sessions/${encodeURIComponent(sessionId)}/command`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({type:'SET_RECONSTRUCTION_GUARD',enabled,mode})}).catch(()=>{});};
  const ensureLiveStatus=(state:BrowserState,target:HTMLDivElement):void=>{
    if(target.querySelector('[data-browser-snapshot-frame]'))target.innerHTML='';lastSnapshotVersion=-1;
    let status=target.querySelector<HTMLElement>('.browserPreviewSession');if(!status){target.innerHTML='<div class="browserPreviewSession"><strong data-browser-session-title></strong><span data-browser-session-meta></span><p data-browser-session-hint></p><small data-browser-session-detail></small></div>';status=target.querySelector<HTMLElement>('.browserPreviewSession');}
    const title=status?.querySelector<HTMLElement>('[data-browser-session-title]'),meta=status?.querySelector<HTMLElement>('[data-browser-session-meta]'),hint=status?.querySelector<HTMLElement>('[data-browser-session-hint]'),detail=status?.querySelector<HTMLElement>('[data-browser-session-detail]');
    if(state.recording){if(!state.checkpointReady){if(title)title.textContent='Preparing reconstruction…';if(hint)hint.textContent='The external page is temporarily locked while Animator secures a reconstructable copy of the current document.';if(detail)detail.textContent='Keep the browser open. It will unlock automatically when it is safe to close.';}else{if(title)title.textContent=`${browserLabel(state.engine)} recording — ready to close browser`;if(hint)hint.textContent=state.external?'Interact, scroll and navigate in the browser window. Animator records motion and events without streaming frames.':'CI/headless mode: motion and events are being captured without a video stream.';if(detail)detail.textContent='A safe reconstruction is ready and kept updated. Closing the browser will automatically stop REC.';}}
    else{if(title)title.textContent=state.snapshotStatus==='error'?'Capture stopped — reconstruction unavailable':state.snapshotReady?'Capture complete':'Finalizing reconstruction…';if(hint)hint.textContent=state.snapshotStatus==='error'?(state.snapshotError??'No usable reconstruction was available.'):state.snapshotReady?'The reconstructed document is ready in Animator.':'Recording is already stopped. Animator is finishing the captured document.';if(detail)detail.textContent=state.closed?'Browser window closed and REC was finalized automatically.':'Snapshot work does not block recording controls.';}
    if(meta)meta.textContent=`${state.profile==='mobile'?'Mobile':'Desktop'} · ${state.width} × ${state.height} viewport${state.title?` · ${state.title}`:''}`;delete target.dataset.browserSnapshot;
  };
  const ensureSnapshot=(target:HTMLDivElement,state:BrowserState):void=>{let frame=target.querySelector<HTMLIFrameElement>('[data-browser-snapshot-frame]');if(!frame){target.innerHTML='';frame=document.createElement('iframe');frame.dataset.browserSnapshotFrame='';frame.title='Recorded browser document';target.append(frame);}if(lastSnapshotVersion!==state.snapshotVersion){lastSnapshotVersion=state.snapshotVersion;frame.src=`/api/browser-sessions/${encodeURIComponent(sessionId)}/snapshot?v=${state.snapshotVersion}`;}target.dataset.browserSnapshot='true';};
  const renderState=(state:BrowserState,target:HTMLDivElement):void=>{if(!state.recording&&state.snapshotReady)ensureSnapshot(target,state);else ensureLiveStatus(state,target);};
  const removeSurface=():void=>{if(stateTimer)clearTimeout(stateTimer);if(motionTimer)clearTimeout(motionTimer);stateTimer=0;motionTimer=0;motionBusy=false;runtimeHealthy=false;lastUrl='';lastState=null;lastSnapshotVersion=-1;lastGuardState='';motionSignatures.clear();motionElements.clear();surface?.remove();surface=null;resetDeviceSize();};
  const removeIframes=():void=>device.querySelectorAll<HTMLIFrameElement>('[data-preview-frame]').forEach(frame=>frame.remove());
  const pollState=async():Promise<void>=>{
    if(disposed||!sessionId||!surface)return;const requestedSession=sessionId,requestedSurface=surface;
    try{const response=await fetch(`/api/browser-sessions/${encodeURIComponent(requestedSession)}/state`,{cache:'no-store'});if(response.ok&&requestedSession===sessionId&&requestedSurface===surface&&requestedSurface.isConnected){const state=await response.json() as BrowserState;if(requestedSession!==sessionId||requestedSurface!==surface||!requestedSurface.isConnected)return;lastState=state;lastWidth=state.width;lastHeight=state.height;applyDeviceSize(lastWidth,lastHeight);if(lastUrl&&state.url!==lastUrl){runtimeHealthy=false;lastGuardState='';motionSignatures.clear();motionElements.clear();if(state.recording)scheduleMotion(40);}lastUrl=state.url;requestedSurface.title=`${state.title||'Browser capture'} — ${state.url}`;requestedSurface.dataset.browserEngineActive=state.engine;requestedSurface.dataset.browserProfileActive=state.profile;requestedSurface.dataset.browserWidth=String(state.width);requestedSurface.dataset.browserHeight=String(state.height);requestedSurface.dataset.browserExternal=String(state.external);requestedSurface.dataset.browserRecording=String(state.recording);requestedSurface.dataset.browserClosed=String(state.closed);requestedSurface.dataset.browserSnapshotStatus=state.snapshotStatus;requestedSurface.dataset.browserReconstructionReady=String(state.checkpointReady||state.snapshotReady);syncReconstructionGuard(state);renderState(state,requestedSurface);}}
    catch{}finally{if(!disposed&&requestedSession===sessionId&&requestedSurface===surface&&requestedSurface.isConnected)stateTimer=window.setTimeout(()=>void pollState(),nextStateDelay());}
  };
  const mount=():void=>{
    const project=store.get().project,next=project?.browserSessionId??'';if(next)removeIframes();
    if(next===sessionId&&surface?.isConnected){applyDeviceSize(lastWidth,lastHeight);if(lastState)renderState(lastState,surface);if(store.get().recording&&!motionTimer&&!motionBusy)scheduleMotion();return;}
    const previous=sessionId;removeSurface();sessionId=next;if(previous&&previous!==next)void fetch(`/api/browser-sessions/${encodeURIComponent(previous)}`,{method:'DELETE'}).catch(()=>{});if(!sessionId)return;
    removeIframes();lastWidth=project?.browserWidth??(project?.browserProfile==='mobile'?390:1100);lastHeight=project?.browserHeight??(project?.browserProfile==='mobile'?844:700);applyDeviceSize(lastWidth,lastHeight);
    surface=document.createElement('div');surface.className='browserPreviewSurface';surface.dataset.browserPreview='';surface.dataset.browserSessionId=sessionId;surface.dataset.browserReconstructionReady='false';surface.dataset.browserEngineActive=project?.browserEngine??'chromium';surface.dataset.browserProfileActive=project?.browserProfile??'desktop';surface.dataset.browserWidth=String(lastWidth);surface.dataset.browserHeight=String(lastHeight);surface.dataset.browserExternal=String(project?.browserExternal??false);surface.innerHTML='<div class="browserPreviewSession"><strong data-browser-session-title>Starting browser window…</strong><span data-browser-session-meta></span><p data-browser-session-hint>Animator is connecting and preparing a safe reconstruction.</p><small data-browser-session-detail>Keep the browser open until Animator reports Ready to close browser.</small></div>';device.append(surface);void pollState();scheduleMotion(40);
  };
  const observer=new MutationObserver(mount);observer.observe(device,{childList:true});const resizeObserver=new ResizeObserver(()=>{if(sessionId)applyDeviceSize(lastWidth,lastHeight);});resizeObserver.observe(stage);const unsubscribe=store.subscribe(mount);mount();
  return()=>{disposed=true;const current=sessionId;unsubscribe();observer.disconnect();resizeObserver.disconnect();removeSurface();sessionId='';if(current)void fetch(`/api/browser-sessions/${encodeURIComponent(current)}`,{method:'DELETE'}).catch(()=>{});};
}

function browserLabel(engine:string):string{return engine==='firefox'?'Firefox':engine==='webkit'?'Safari / WebKit':'Chromium';}
