import {normalizedMotionKeyframes,motionKeyframesToLegacy} from './motion-ir-inspector';
import {sendCommand} from '../preview/bridge';
import {store} from '../state/store';
import type {MotionTrack} from '../core/motion';
import type {ProjectFile,TimelineEvent} from '../types/domain';

type ResizeKind='left'|'right'|'timeline';
type ResizeState={kind:ResizeKind;startX:number;startY:number;initial:number};

export function mountEditorExtras(root:HTMLElement):()=>void{
 const toolbar=root.querySelector<HTMLElement>('.toolbar'),left=root.querySelector<HTMLElement>('.leftPanel'),right=root.querySelector<HTMLElement>('[data-right-region]'),workspace=root.querySelector<HTMLElement>('.workspace'),timeline=root.querySelector<HTMLElement>('.timeline'),app=root.querySelector<HTMLElement>('.app');
 const controls=document.createElement('span');controls.className='extraControls';controls.innerHTML='<button data-open-create-motion>New animation…</button><label class="toolbarToggle"><input type="checkbox" data-loop-all> Loop</label><input data-custom-width type="number" min="200" max="5000" value="1100" title="Custom viewport width"><span>×</span><input data-custom-height type="number" min="200" max="5000" value="700" title="Custom viewport height"><button data-apply-custom-viewport>Custom</button>';toolbar?.append(controls);
 const search=document.createElement('section');search.className='globalSearch';search.innerHTML='<h3>Search all</h3><input data-global-search placeholder="Files, elements, animations"><div data-global-results></div>';left?.insertBefore(search,left.querySelector('[data-motion-region]'));
 const graph=document.createElement('section');graph.className='eventGraph';graph.innerHTML='<h3>Event graph</h3><p class="muted">Interactions, mutations and motion will appear here.</p>';left?.insertBefore(graph,left.querySelector('.elementList'));
 const dialog=createMotionDialog();root.append(dialog);const resizeHandles=createResizeHandles(workspace,timeline);let resize:ResizeState|undefined,customViewport:{width:number;height:number}|undefined;const getFrame=()=>root.querySelector<HTMLIFrameElement>('[data-preview-frame]');
 const viewportLabel=root.querySelector<HTMLElement>('[data-viewport-label]');
 const applyCustomViewport=():void=>{if(!customViewport)return;applyViewport(root,customViewport.width,customViewport.height);};
 const labelObserver=viewportLabel?new MutationObserver(()=>{if(customViewport&&viewportLabel.textContent!==`${customViewport.width}×${customViewport.height}`)viewportLabel.textContent=`${customViewport.width}×${customViewport.height}`;}):undefined;labelObserver?.observe(viewportLabel!,{childList:true,characterData:true,subtree:true});
 const click=(event:MouseEvent):void=>{const target=event.target;if(!(target instanceof HTMLElement))return;if(target.matches('[data-apply-custom-viewport]')){const width=Number(controls.querySelector<HTMLInputElement>('[data-custom-width]')?.value??1100),height=Number(controls.querySelector<HTMLInputElement>('[data-custom-height]')?.value??700);if(!validViewport(width,height)){store.set({diagnostics:[...store.get().diagnostics,'Viewport width and height must be between 200 and 5000 pixels.'].slice(-100)});return;}customViewport={width,height};applyCustomViewport();return;}if(target.matches('[data-open-create-motion]')){if(!store.get().selectedElementId){store.set({diagnostics:[...store.get().diagnostics,'Pick an element before creating an animation.']});return;}dialog.showModal();}};
 const change=(event:Event):void=>{const target=event.target;if(target instanceof HTMLInputElement&&target.matches('[data-loop-all]'))sendCommand(getFrame(),{type:'SET_LOOP_ALL',enabled:target.checked});if(target instanceof HTMLSelectElement&&target.matches('[data-viewport]')){customViewport=undefined;const device=root.querySelector<HTMLElement>('[data-device]');if(device)delete device.dataset.customViewport;queueMicrotask(()=>syncViewportInputs(root,controls));}};
 const input=(event:Event):void=>{const target=event.target;if(target instanceof HTMLInputElement&&target.matches('[data-global-search]'))renderSearch(search,target.value);};
 const submit=(event:SubmitEvent):void=>{event.preventDefault();const elementId=store.get().selectedElementId;if(!elementId)return;const data=new FormData(event.currentTarget as HTMLFormElement),property=String(data.get('property')??'opacity').trim()||'opacity',from=String(data.get('from')??'0'),to=String(data.get('to')??'1'),duration=Math.max(1,Number(data.get('duration')??400)),delay=Number(data.get('delay')??0),easing=String(data.get('easing')??'ease-out'),iterations=Math.max(1,Number(data.get('iterations')??1)),direction=String(data.get('direction')??'normal'),fill=String(data.get('fill')??'both');sendCommand(getFrame(),{type:'CREATE_ANIMATION',elementId,keyframes:[{offset:0,[property]:from},{offset:1,[property]:to}],duration,delay,easing,iterations,direction,fill});dialog.close();};
 const beginResize=(event:PointerEvent):void=>{const target=event.currentTarget as HTMLElement,kind=target.dataset.resize as ResizeKind,initial=kind==='left'?(left?.getBoundingClientRect().width??250):kind==='right'?(root.querySelector<HTMLElement>('.rightPanel')?.getBoundingClientRect().width??340):(timeline?.getBoundingClientRect().height??270);resize={kind,startX:event.clientX,startY:event.clientY,initial};target.setPointerCapture(event.pointerId);document.body.classList.add('isResizing');};
 const moveResize=(event:PointerEvent):void=>{if(!resize||!workspace||!app)return;if(resize.kind==='left')workspace.style.setProperty('--left-panel',`${clamp(resize.initial+event.clientX-resize.startX,160,520)}px`);else if(resize.kind==='right')workspace.style.setProperty('--right-panel',`${clamp(resize.initial-(event.clientX-resize.startX),220,600)}px`);else app.style.setProperty('--timeline-height',`${clamp(resize.initial-(event.clientY-resize.startY),150,560)}px`);};
 const endResize=():void=>{resize=undefined;document.body.classList.remove('isResizing');};
 root.addEventListener('click',click);root.addEventListener('change',change);root.addEventListener('input',input);dialog.querySelector('form')?.addEventListener('submit',submit as EventListener);for(const handle of resizeHandles)handle.addEventListener('pointerdown',beginResize);window.addEventListener('pointermove',moveResize);window.addEventListener('pointerup',endResize);
 const renderGraph=():void=>{const events=store.queryEvents({limit:80});graph.innerHTML=`<h3>Event graph <small>${store.recordingStats().count}</small></h3>${eventGraph(events)}`;const query=search.querySelector<HTMLInputElement>('[data-global-search]')?.value??'';if(query)renderSearch(search,query);};const unsubscribe=store.subscribe(renderGraph);renderGraph();
 const observer=right?new MutationObserver(()=>enhanceRightPanel(root,right,getFrame)):undefined;if(right)observer?.observe(right,{childList:true,subtree:true});enhanceRightPanel(root,right,getFrame);
 return()=>{unsubscribe();observer?.disconnect();labelObserver?.disconnect();root.removeEventListener('click',click);root.removeEventListener('change',change);root.removeEventListener('input',input);dialog.querySelector('form')?.removeEventListener('submit',submit as EventListener);for(const handle of resizeHandles)handle.removeEventListener('pointerdown',beginResize);window.removeEventListener('pointermove',moveResize);window.removeEventListener('pointerup',endResize);controls.remove();search.remove();graph.remove();dialog.remove();resizeHandles.forEach(handle=>handle.remove());};
}

function createMotionDialog():HTMLDialogElement{const dialog=document.createElement('dialog');dialog.className='motionDialog';dialog.innerHTML='<form><header><b>Create animation</b><button type="button" data-dialog-close>×</button></header><label>Property<input name="property" value="opacity"></label><div class="dialogPair"><label>From<input name="from" value="0"></label><label>To<input name="to" value="1"></label></div><div class="dialogPair"><label>Duration ms<input name="duration" type="number" min="1" value="400"></label><label>Delay ms<input name="delay" type="number" value="0"></label></div><label>Easing<input name="easing" value="ease-out"></label><div class="dialogPair"><label>Iterations<input name="iterations" type="number" min="1" value="1"></label><label>Direction<select name="direction"><option>normal</option><option>reverse</option><option>alternate</option><option>alternate-reverse</option></select></label></div><label>Fill<select name="fill"><option>both</option><option>forwards</option><option>backwards</option><option>none</option></select></label><footer><button type="button" data-dialog-cancel>Cancel</button><button type="submit">Create</button></footer></form>';dialog.addEventListener('click',event=>{const target=event.target;if(target instanceof HTMLElement&&(target.matches('[data-dialog-close]')||target.matches('[data-dialog-cancel]')))dialog.close();});return dialog;}
function createResizeHandles(workspace:HTMLElement|null,timeline:HTMLElement|null):HTMLElement[]{const handles:HTMLElement[]=[];if(workspace)for(const kind of ['left','right'] as const){const handle=document.createElement('div');handle.className=`panelResizer ${kind}`;handle.dataset.resize=kind;workspace.append(handle);handles.push(handle);}if(timeline){const handle=document.createElement('div');handle.className='timelineResizer';handle.dataset.resize='timeline';timeline.append(handle);handles.push(handle);}return handles;}
function validViewport(width:number,height:number):boolean{return Number.isFinite(width)&&Number.isFinite(height)&&width>=200&&height>=200&&width<=5000&&height<=5000;}
function applyViewport(root:HTMLElement,width:number,height:number):void{if(!validViewport(width,height))return;const device=root.querySelector<HTMLElement>('[data-device]'),label=root.querySelector<HTMLElement>('[data-viewport-label]');if(!device)return;device.style.width=`${width}px`;device.style.height=`${height}px`;device.style.removeProperty('transform');device.dataset.customViewport=`${width}x${height}`;if(label)label.textContent=`${width}×${height}`;root.dispatchEvent(new CustomEvent('animator:workspace-fit-request',{bubbles:true}));}
function syncViewportInputs(root:HTMLElement,controls:HTMLElement):void{const [w,h]=(root.querySelector<HTMLElement>('[data-viewport-label]')?.textContent??'').split('×').map(Number),wi=controls.querySelector<HTMLInputElement>('[data-custom-width]'),hi=controls.querySelector<HTMLInputElement>('[data-custom-height]');if(wi&&Number.isFinite(w))wi.value=String(w);if(hi&&Number.isFinite(h))hi.value=String(h);}
function renderSearch(section:HTMLElement,query:string):void{const output=section.querySelector<HTMLElement>('[data-global-results]');if(!output)return;const needle=query.trim().toLowerCase();if(!needle){output.replaceChildren();return;}const state=store.get(),files=state.project?flattenFiles(state.project.tree).filter(file=>file.toLowerCase().includes(needle)).slice(0,8):[],elements=state.elements.filter(element=>[element.tag,element.domId,...element.classes,element.text].filter(Boolean).join(' ').toLowerCase().includes(needle)).slice(0,8),tracks=state.motionTracks.filter(track=>[track.name,track.source.kind,track.source.reference?.file,track.source.reference?.selector,...track.properties.map(property=>property.name)].filter(Boolean).join(' ').toLowerCase().includes(needle)).slice(0,8);output.innerHTML=[...files.map(file=>`<button data-file="${escapeHtml(file)}"><small>file</small>${escapeHtml(file)}</button>`),...elements.map(element=>`<button data-element-id="${escapeHtml(element.id)}"><small>element</small>${escapeHtml(element.domId?`#${element.domId}`:`${element.tag}.${element.classes[0]??''}`)}</button>`),...tracks.map(track=>`<button data-animation-id="${escapeHtml(track.id)}"><small>motion</small>${escapeHtml(track.name??track.source.kind)}</button>`)].join('')||'<p class="muted">No matches.</p>';}
function flattenFiles(nodes:ProjectFile[],prefix=''):string[]{const out:string[]=[];for(const node of nodes){const value=node.path||`${prefix}/${node.name}`;if(node.type==='file')out.push(value);else if(node.children)out.push(...flattenFiles(node.children,value));}return out;}
function eventGraph(events:TimelineEvent[]):string{if(!events.length)return'<p class="muted">No recorded events yet.</p>';const groups:Array<{root:TimelineEvent;children:TimelineEvent[]}>=[];let current:{root:TimelineEvent;children:TimelineEvent[]}|undefined;for(const event of events){if(event.kind.startsWith('user-')){current={root:event,children:[]};groups.push(current);}else if(current&&event.at-current.root.at<2500)current.children.push(event);else{current={root:event,children:[]};groups.push(current);}}return`<div class="eventGraphRows">${groups.slice(-20).map(group=>`<div class="eventNode"><div><span>${Math.round(group.root.at)}ms</span>${escapeHtml(group.root.label)}</div>${group.children.slice(0,12).map(child=>`<div class="eventChild"><span>${Math.round(child.at-group.root.at)}ms</span>${escapeHtml(child.label)} <small>${escapeHtml(child.kind)}</small></div>`).join('')}</div>`).join('')}</div>`;}
function enhanceRightPanel(root:HTMLElement,panel:HTMLElement|null|undefined,getFrame:()=>HTMLIFrameElement|null):void{enhanceSource(panel);enhanceBezier(root,panel,getFrame);enhanceTransformOrigin(panel,getFrame);}
function enhanceSource(panel:HTMLElement|null|undefined):void{const pre=panel?.querySelector<HTMLElement>('.sourceView pre');if(!pre||pre.dataset.enhanced==='1')return;const source=pre.textContent??'';pre.dataset.enhanced='1';pre.classList.add('sourceLines');pre.innerHTML=source.split('\n').map((line,index)=>`<span data-line="${index+1}">${highlight(line)}</span>`).join('');}
function enhanceBezier(root:HTMLElement,panel:HTMLElement|null|undefined,getFrame:()=>HTMLIFrameElement|null):void{const svg=panel?.querySelector<SVGSVGElement>('.easingEditor svg');if(!svg||svg.dataset.handles==='1')return;svg.dataset.handles='1';const curve=svg.querySelector<SVGPathElement>('.curve'),inputs=[...root.querySelectorAll<HTMLInputElement>('[data-bezier-index]')];if(!curve||inputs.length!==4)return;for(const pointIndex of [0,1]){const circle=document.createElementNS('http://www.w3.org/2000/svg','circle');circle.classList.add('bezierHandle');circle.setAttribute('r','5');svg.append(circle);const updateCircle=()=>{const x=Number(inputs[pointIndex*2]?.value??0),y=Number(inputs[pointIndex*2+1]?.value??0);circle.setAttribute('cx',String(10+x*140));circle.setAttribute('cy',String(150-y*140));};updateCircle();circle.addEventListener('pointerdown',event=>{circle.setPointerCapture(event.pointerId);event.preventDefault();});circle.addEventListener('pointermove',event=>{if(!circle.hasPointerCapture(event.pointerId))return;const rect=svg.getBoundingClientRect(),localX=(event.clientX-rect.left)/rect.width*160,localY=(event.clientY-rect.top)/rect.height*160,x=clamp((localX-10)/140,0,1),y=clamp((150-localY)/140,-1,2),xInput=inputs[pointIndex*2],yInput=inputs[pointIndex*2+1];if(!xInput||!yInput)return;xInput.value=x.toFixed(3);yInput.value=y.toFixed(3);updateCircle();const points=inputs.map(input=>Number(input.value));curve.setAttribute('d',bezierPath(points));const selected=selectedTrack();if(selected)sendCommand(getFrame(),{type:'APPLY_OVERRIDE',animationId:selected.id,easing:`cubic-bezier(${points.join(',')})`});});circle.addEventListener('pointerup',event=>{if(circle.hasPointerCapture(event.pointerId))circle.releasePointerCapture(event.pointerId);const selected=selectedTrack();if(!selected)return;const points=inputs.map(input=>Number(input.value));store.updateMotionTrack(selected.id,{timing:{easing:`cubic-bezier(${points.join(',')})`}});});}}
function enhanceTransformOrigin(panel:HTMLElement|null|undefined,getFrame:()=>HTMLIFrameElement|null):void{const grid=panel?.querySelector<HTMLElement>('.transformGrid');if(!grid||grid.querySelector('[data-transform-origin-extra]'))return;const selected=selectedTrack();if(!selected)return;const frames=normalizedMotionKeyframes(selected),value=String(frames.at(-1)?.values.transformOrigin??'50% 50%'),label=document.createElement('label');label.className='transformOrigin';label.innerHTML=`transform-origin<input data-transform-origin-extra value="${escapeHtml(value)}">`;grid.append(label);const input=label.querySelector<HTMLInputElement>('input');input?.addEventListener('change',()=>{const current=selectedTrack();if(!current||!input)return;const next=normalizedMotionKeyframes(current),last=next.at(-1);if(!last)return;next[next.length-1]={...last,values:{...last.values,transformOrigin:input.value}};store.updateMotionTrack(current.id,{keyframes:next});sendCommand(getFrame(),{type:'APPLY_OVERRIDE',animationId:current.id,keyframes:motionKeyframesToLegacy(next)});});}
function selectedTrack():MotionTrack|undefined{const state=store.get();return state.motionTracks.find(track=>track.id===state.selectedAnimationId)??state.motionTracks.find(track=>track.target.elementId===state.selectedElementId);}
function bezierPath(points:number[]):string{const[x1=.25,y1=.1,x2=.25,y2=1]=points;return`M 10 150 C ${10+x1*140} ${150-y1*140}, ${10+x2*140} ${150-y2*140}, 150 10`;}
function highlight(line:string):string{let value=escapeHtml(line);value=value.replace(/\b(const|let|var|function|return|if|else|for|while|class|interface|type|import|from|export|async|await|new|true|false|null|undefined)\b/g,'<b class="tok-keyword">$1</b>');value=value.replace(/(&quot;[^&]*?&quot;|&#39;[^&]*?&#39;)/g,'<i class="tok-string">$1</i>');return value;}
function clamp(value:number,min:number,max:number):number{return Math.max(min,Math.min(max,value));}
function escapeHtml(value:string):string{return value.replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[char]??char);}
