import type { MotionKeyframe,MotionTrack,MotionValue } from '../core/motion';
import type { DetectedAnimation } from '../types/domain';

export type InspectorMotionPatch={timing?:Partial<MotionTrack['timing']>;keyframes?:MotionKeyframe[]};

export function selectMotionTrack(tracks:MotionTrack[],selectedId:string|undefined):MotionTrack|undefined{return selectedId?tracks.find(track=>track.id===selectedId):undefined;}
export function motionKeyframesToLegacy(frames:MotionKeyframe[]):Array<Record<string,MotionValue>>{return frames.map(frame=>({...frame.values,...(frame.offset!==undefined?{offset:frame.offset}:{}),...(frame.easing!==undefined?{easing:frame.easing}:{}),...(frame.composite!==undefined?{composite:frame.composite}:{})}));}
export function legacyKeyframesToMotion(frames:Array<Record<string,string|number|null>>):MotionKeyframe[]{return frames.map(frame=>{const values:Record<string,MotionValue>={};let offset:number|undefined,easing:string|undefined,composite:string|undefined;for(const [key,value] of Object.entries(frame)){if(key==='offset'&&typeof value==='number'){offset=value;continue;}if(key==='easing'&&typeof value==='string'){easing=value;continue;}if(key==='composite'&&typeof value==='string'){composite=value;continue;}values[key]=value;}return{values,...(offset!==undefined?{offset}:{}),...(easing!==undefined?{easing}:{}),...(composite!==undefined?{composite}:{})};});}
export function legacyPatchToMotion(patch:Partial<DetectedAnimation>):InspectorMotionPatch{const timing:Partial<MotionTrack['timing']>={};if(patch.duration!==undefined)timing.duration=patch.duration;if(patch.delay!==undefined)timing.delay=patch.delay;if(patch.easing!==undefined)timing.easing=patch.easing;if(patch.iterations!==undefined)timing.iterations=patch.iterations;if(patch.direction!==undefined)timing.direction=patch.direction;if(patch.fill!==undefined)timing.fill=patch.fill;return{...(Object.keys(timing).length?{timing}:{}),...(patch.keyframes!==undefined?{keyframes:legacyKeyframesToMotion(patch.keyframes)}:{})};}
export function motionTrackPreview(track:MotionTrack,patch:InspectorMotionPatch={}):{duration:number|undefined;delay:number|undefined;easing:string|undefined;keyframes:Array<Record<string,MotionValue>>|undefined}{const timing={...track.timing,...patch.timing},frames=patch.keyframes??track.keyframes;return{duration:timing.duration,delay:timing.delay,easing:timing.easing,keyframes:frames.length?motionKeyframesToLegacy(frames):undefined};}
