import {bezierPath,parseBezier,parseTransform,type TransformParts} from '../editor/motion';
import {presets} from '../presets/presets';
import {loadCustomPresets} from '../presets/custom';
import {store} from '../state/store';
import type {MotionTrack} from '../core/motion';
import {motionKeyframesToLegacy} from './motion-ir-inspector';

const risky=new Set(['width','height','top','left','right','bottom','margin','margin-left','margin-right','margin-top','margin-bottom','padding','padding-left','padding-right','padding-top','padding-bottom']);

export function renderMotionIrPanel(track:MotionTrack|undefined,hasElement:boolean,all:MotionTrack[]):string{
  const custom=loadCustomPresets(),allPresets=[...presets,...custom],frames=track?motionKeyframesToLegacy(track.keyframes):[],bezier=track?parseBezier(track.timing.easing??''):undefined,last=frames.at(-1),transform=parseTransform(typeof last?.transform==='string'?last.transform:undefined),issues=track?track.properties.flatMap(property=>risky.has(property.name)?[{severity:'warn',message:`${property.name} can trigger layout; measure before optimizing.`}]:property.name==='filter'?[{severity:'info',message:'filter can be GPU-expensive depending on blur radius and affected area.'}]:[]):[];
  const details=track?`<div class="badges"><span>${html(sourceLabel(track))}</span><span>${html(track.source.confidence)}</span><span>${html(track.runtimeState)}</span></div><div class="controlGrid"><label>Duration<input data-duration-range type="range" min="1" max="10000" step="1" value="${track.timing.duration??400}"><input data-duration-number type="number" value="${track.timing.duration??400}"><em>ms</em></label><label>Delay<input data-delay type="number" value="${track.timing.delay??0}"><em>ms</em></label><label>Easing<input data-easing-text value="${attr(track.timing.easing??'ease')}"></label><label>Iterations<input data-iterations type="number" min="1" step="1" value="${track.timing.iterations??1}"></label></div>${easingEditor(bezier)}<h4>Keyframes <button class="tiny" data-action="add-keyframe">+</button><button class="tiny" data-action="add-property">property</button></h4><div class="keyframeEditor">${frames.map((frame,index)=>keyframeCard(frame,index,frames.length)).join('')}</div><h4>Transform · last keyframe</h4>${transformEditor(transform)}${issues.length?`<h4>Performance</h4>${issues.map(issue=>`<div class="perf ${issue.severity}">${html(issue.message)}</div>`).join('')}`:''}`:'';
  const title=track?(track.name??sourceLabel(track)):'No animation selected';
  return `<div class="inspector" data-motion-ir-panel><h3>${html(title)}</h3>${details}<h4>Create / presets</h4><div class="actions"><button data-action="create-animation" ${hasElement?'':'disabled'}>Create animation</button><select data-preset ${hasElement?'':'disabled'}><option value="">Apply preset…</option>${allPresets.map(preset=>`<option value="${attr(preset.id)}">${html(preset.label)}</option>`).join('')}</select></div>${track?'<div class="actions"><button data-action="save-preset">Save as preset</button></div>':''}${custom.length?`<div class="customPresets">${custom.map(preset=>`<span>${html(preset.label)}<button data-delete-preset="${attr(preset.id)}">×</button></span>`).join('')}</div>`:''}${hasElement?'':'<p class="muted">Pick an element first.</p>'}<h4>Scene diagnostics</h4><p class="muted">${all.length} motion tracks. CSS/WAAPI scrub frame by frame; arbitrary JS/rAF is observation-only.</p></div>`;
}

export function mountMotionIrPanel(root:HTMLElement):()=>void{
  let raf=0,signature='';
  const schedule=()=>{if(!raf)raf=requestAnimationFrame(render);};
  const render=()=>{raf=0;const tab=root.querySelector<HTMLElement>('[data-tab="motion"]');if(!tab?.classList.contains('active'))return;const region=root.querySelector<HTMLElement>('[data-right-region]');if(!region)return;const state=store.get(),track=state.motionTracks.find(item=>item.id===state.selectedAnimationId)??state.motionTracks.find(item=>item.target.elementId===state.selectedElementId),next=`${track?.id??''}:${track?.timing.duration??''}:${track?.timing.delay??''}:${track?.timing.easing??''}:${JSON.stringify(track?.keyframes??[])}:${state.motionTracks.length}:${state.selectedElementId??''}:${localStorage.getItem('animator.custom-presets.v1')??''}`;if(next===signature&&region.querySelector('[data-motion-ir-panel]'))return;signature=next;region.innerHTML=renderMotionIrPanel(track,!!state.selectedElementId,state.motionTracks);};
  const click=()=>schedule();root.addEventListener('click',click);const unsubscribe=store.subscribe(schedule);schedule();
  return()=>{unsubscribe();root.removeEventListener('click',click);if(raf)cancelAnimationFrame(raf);};
}

function sourceLabel(track:MotionTrack):string{return track.source.kind==='waapi'?'WAAPI':track.source.kind;}
function easingEditor(bezier:[number,number,number,number]|undefined):string{const points=bezier??[.25,.1,.25,1];return `<div class="easingEditor"><svg viewBox="0 0 160 160"><path d="M10 150 L150 10" class="guide"></path><path d="${bezierPath(points)}" class="curve"></path></svg><div>${points.map((value,index)=>`<label>P${Math.floor(index/2)+1}${index%2===0?'x':'y'}<input data-bezier-index="${index}" type="number" step="0.01" value="${value}"></label>`).join('')}</div></div>`;}
function keyframeCard(frame:Record<string,string|number|null>,index:number,count:number):string{const keys=Object.keys(frame).filter(key=>!['computedOffset','composite','offset'].includes(key));return `<div class="keyframeCard"><header><b>${index+1}</b><label>offset <input data-kf-index="${index}" data-kf-key="offset" type="number" min="0" max="1" step="0.01" value="${Number(frame.offset??index/Math.max(1,count-1))}"></label><button class="tiny" data-duplicate-kf="${index}">duplicate</button><button class="tiny" data-delete-kf="${index}" ${count<=2?'disabled':''}>delete</button></header>${keys.map(key=>`<label><code>${html(key)}</code><input data-kf-index="${index}" data-kf-key="${attr(key)}" value="${attr(String(frame[key]??''))}"></label>`).join('')}</div>`;}
function transformEditor(transform:TransformParts):string{return `<div class="transformGrid">${(['translateX','translateY','scaleX','scaleY','rotate','skewX','skewY'] as const).map(key=>`<label>${key}<input data-transform-key="${key}" type="number" step="${key.startsWith('scale')?'.01':'1'}" value="${transform[key]}"></label>`).join('')}</div>`;}
function html(value:string):string{return value.replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[char]??char);}
function attr(value:string):string{return html(value);}
