import {type MotionSourceKind,type MotionTrack} from '../core/motion';
import {groupAnimations,type AnimationGroup} from '../editor/grouping';
import {TimelineEngine,TimelineVirtualizer,timelineRulerMarks,timelineTimeFromPointer,timelineTimeToPx,timelineTimingDuration,timelineTimingStart,timelineVisibleRange} from '../core/timeline';
import {sendCommand,TIMELINE_STATE_EVENT} from '../preview/bridge';
import {store} from '../state/store';
import type {PreviewMessage,RuntimeElement,TimelineEvent} from '../types/domain';

export const ANIMATION_INSPECT_EVENT='animator:inspect-animation';
export const ANIMATION_CLEAR_INSPECTION_EVENT='animator:clear-animation-inspection';
export const TIMELINE_VIRTUALIZATION_EVENT='animator:timeline-virtualization-change';
type TimelineStateMessage=Extract<PreviewMessage,{type:'TIMELINE_STATE'}>;
type InspectionDetail={id:string;elementId:string;origin:number};
type DragState={motion:HTMLElement;pointerId:number;rectLeft:number;pxPerMs:number;duration:number;origin:number;scrollLeft:number};
type EventCluster={at:number;events:TimelineEvent[]};
type VirtualRow={key:string;height:number;html:string};
type RowHeights={group:number;instance:number;expanded:number;ruler:number};
type MotionGroup=AnimationGroup<MotionTrack>;

export function mountTimelineV2(root:HTMLElement):()=>void{
  const timeline=root.querySelector<HTMLElement>('.timeline'),legacy=root.querySelector<HTMLElement>('.timelineScroll');if(!timeline||!legacy)return()=>{};
  legacy.classList.add('legacyTimeline');const viewport=document.createElement('div');viewport.className='timelineV2Viewport';viewport.dataset.timelineV2='';viewport.dataset.timelineIsolation='all';timeline.append(viewport);
  const expanded=new Set<string>(),expandedDetails=new Set<string>(),engine=new TimelineEngine(),virtualizer=new TimelineVirtualizer();
  let structuralSignature='',windowSignature='',eventSignature='',drag:DragState|undefined,raf=0,livePxPerMs=.1,viewOriginMs=0,inspectedAnimationId:string|undefined,lastProject='',rows:VirtualRow[]=[],rowHeights:RowHeights|undefined;
  const frame=()=>root.querySelector<HTMLIFrameElement>('[data-preview-frame]');
  const schedule=():void=>{if(!raf)raf=requestAnimationFrame(render);};
  const render=():void=>{
    raf=0;if(drag){viewport.style.setProperty('--timeline-playhead',`${Math.max(0,(store.get().playhead-drag.origin)*drag.pxPerMs)}px`);return;}
    const state=store.get(),projectKey=state.project?.id??'';
    if(projectKey!==lastProject){lastProject=projectKey;engine.reset();viewOriginMs=0;inspectedAnimationId=undefined;expanded.clear();expandedDetails.clear();structuralSignature='';windowSignature='';eventSignature='';rows=[];rowHeights=undefined;viewport.scrollTop=0;}
    const groups=groupAnimations(state.motionTracks,state.selectedAnimationId),elements=new Map(state.elements.map(element=>[element.id,element]));
    const inspected=inspectedAnimationId?state.motionTracks.find(track=>track.id===inspectedAnimationId):undefined;if(inspectedAnimationId&&!inspected){inspectedAnimationId=undefined;viewOriginMs=0;}
    const metrics=engine.measure({tracks:state.motionTracks,events:state.events,zoom:state.zoom,playhead:state.playhead,origin:viewOriginMs,...(inspected?{isolatedTrackId:inspected.id}:{})});
    const{origin,duration,pxPerMs,canvasWidth,gridMajorPx,gridMinorPx}=metrics;if(inspected)viewOriginMs=origin;livePxPerMs=pxPerMs;
    viewport.style.setProperty('--timeline-canvas-width',`${canvasWidth}px`);viewport.style.setProperty('--timeline-playhead',`${metrics.playheadPx}px`);viewport.style.setProperty('--timeline-grid-major',`${gridMajorPx}px`);viewport.style.setProperty('--timeline-grid-minor',`${gridMinorPx}px`);viewport.dataset.pxPerMs=String(pxPerMs);viewport.dataset.duration=String(duration);viewport.dataset.originMs=String(origin);
    const signature=[state.zoom,state.selectedAnimationId??'',inspectedAnimationId??'',origin,duration,groups.map(group=>groupSignature(group)).join('|'),[...expanded].sort().join(','),[...expandedDetails].sort().join(',')].join('::');
    if(signature!==structuralSignature){structuralSignature=signature;windowSignature='';eventSignature='';rowHeights=measureRowHeights(viewport);rows=flattenRows(groups,elements,expanded,expandedDetails,state.selectedAnimationId,pxPerMs,origin,rowHeights);virtualizer.setItems(rows);}
    renderRows(viewport,rows,virtualizer,rowHeights??measureRowHeights(viewport),groups.length,!!inspected,duration,pxPerMs);updateEvents(viewport,pxPerMs,origin,duration);
  };
  const renderRows=(view:HTMLElement,allRows:VirtualRow[],list:TimelineVirtualizer,heights:RowHeights,groupCount:number,inspected:boolean,duration:number,pxPerMs:number):void=>{
    const virtualizationEnabled=(view.dataset.timelineIsolation??'all')==='all'&&allRows.length>80,bodyScrollTop=Math.max(0,view.scrollTop-heights.ruler),visibleHeight=Math.max(1,view.clientHeight-heights.ruler),window=virtualizationEnabled?list.window(bodyScrollTop,visibleHeight,Math.max(260,visibleHeight)):{start:0,end:allRows.length,top:0,bottom:0,total:allRows.reduce((sum,row)=>sum+row.height,0)},next=[structuralSignature,virtualizationEnabled?'v':'all',window.start,window.end,Math.round(window.top),Math.round(window.bottom)].join(':');if(next===windowSignature)return;windowSignature=next;eventSignature='';
    const left=view.scrollLeft,top=view.scrollTop,visible=allRows.slice(window.start,window.end);view.innerHTML=`<div class="v2Row v2RulerRow"><div class="v2Label v2Corner"><span>${inspected?'Isolated motion':'Animation lanes'}</span><small>${groupCount}</small></div><div class="v2Motion v2RulerMotion" data-v2-scrub-rail>${ruler(duration,pxPerMs)}</div></div>${virtualSpacer(window.top,'top')}${visible.map(row=>row.html).join('')}${virtualSpacer(window.bottom,'bottom')}<div class="v2Row v2EventRow"><div class="v2Label"><span class="v2LaneIcon event"></span><span class="v2GroupTitle">Events</span><small data-v2-event-count>0</small></div><div class="v2Motion" data-v2-event-motion></div></div>`;view.dataset.virtualized=String(virtualizationEnabled);view.dataset.virtualTotalRows=String(allRows.length);view.dataset.virtualRenderedRows=String(visible.length);if(view.scrollLeft!==left)view.scrollLeft=left;if(view.scrollTop!==top)view.scrollTop=top;
  };
  const liveState=(event:Event):void=>{if(drag)return;const detail=(event as CustomEvent<TimelineStateMessage>).detail;if(!detail)return;viewport.style.setProperty('--timeline-playhead',`${Math.max(0,(detail.time-viewOriginMs)*livePxPerMs)}px`);};
  const syncInspection=(event:Event):void=>{const detail=(event as CustomEvent<InspectionDetail>).detail;if(!detail)return;inspectedAnimationId=detail.id;viewOriginMs=Math.max(0,detail.origin);structuralSignature='';schedule();};
  const selectTrack=(track:MotionTrack,inspect=false):void=>{const elementId=track.target.elementId;store.set({selectedAnimationId:track.id,selectedElementId:elementId.startsWith('static:')?store.get().selectedElementId:elementId});sendCommand(frame(),{type:'HIGHLIGHT_ANIMATION',id:track.id,reveal:inspect});if(!inspect)return;inspectedAnimationId=track.id;viewOriginMs=trackStart(track);structuralSignature='';sendCommand(frame(),{type:'SET_SOLO_ANIMATION',id:track.id,elementId,anchorTime:viewOriginMs});window.dispatchEvent(new CustomEvent<InspectionDetail>(ANIMATION_INSPECT_EVENT,{detail:{id:track.id,elementId,origin:viewOriginMs}}));schedule();};
  const click=(event:MouseEvent):void=>{const target=(event.target as Element|null)?.closest<HTMLElement>('[data-v2-detail-toggle],[data-v2-inspect],[data-v2-toggle],[data-v2-instance],[data-v2-group]');if(!target)return;if(target.dataset.v2DetailToggle){const key=target.dataset.v2DetailToggle;if(expandedDetails.has(key))expandedDetails.delete(key);else expandedDetails.add(key);structuralSignature='';schedule();event.stopPropagation();return;}if(target.dataset.v2Toggle){const key=target.dataset.v2Toggle;if(expanded.has(key))expanded.delete(key);else expanded.add(key);structuralSignature='';schedule();event.stopPropagation();return;}const id=target.dataset.v2Inspect??target.dataset.v2Instance??target.dataset.v2Group;if(!id)return;const track=store.get().motionTracks.find(item=>item.id===id);if(!track)return;selectTrack(track,!!target.dataset.v2Inspect);event.stopPropagation();};
  const scrubWith=(event:PointerEvent,state:DragState):void=>{if(viewport.scrollLeft!==state.scrollLeft)viewport.scrollLeft=state.scrollLeft;const metrics={origin:state.origin,duration:state.duration,pxPerMs:state.pxPerMs,rulerStep:100},time=timelineTimeFromPointer(event.clientX,state.rectLeft,metrics),local=timelineTimeToPx(time,state.origin,state.pxPerMs);viewport.style.setProperty('--timeline-playhead',`${local}px`);store.set({playhead:time});sendCommand(frame(),{type:'SCRUB_TIMELINE',time});};
  const canStartScrub=(event:PointerEvent,motion:HTMLElement):boolean=>{if(motion.matches('[data-v2-scrub-rail]'))return true;const rect=motion.getBoundingClientRect(),pxPerMs=Number(viewport.dataset.pxPerMs??.1),origin=Number(viewport.dataset.originMs??0),playheadX=timelineTimeToPx(store.get().playhead,origin,pxPerMs);return Math.abs((event.clientX-rect.left)-playheadX)<=7;};
  const down=(event:PointerEvent):void=>{const motion=(event.target as Element|null)?.closest<HTMLElement>('.v2Motion');if(!motion||!canStartScrub(event,motion))return;const rect=motion.getBoundingClientRect(),pxPerMs=Math.max(.0001,Number(viewport.dataset.pxPerMs??.1));drag={motion,pointerId:event.pointerId,rectLeft:rect.left,pxPerMs,duration:Math.max(0,Number(viewport.dataset.duration??0)),origin:Math.max(0,Number(viewport.dataset.originMs??0)),scrollLeft:viewport.scrollLeft};viewport.classList.add('isScrubbing');viewport.setPointerCapture(event.pointerId);scrubWith(event,drag);event.preventDefault();};
  const move=(event:PointerEvent):void=>{if(drag&&drag.pointerId===event.pointerId&&viewport.hasPointerCapture(event.pointerId))scrubWith(event,drag);};
  const up=(event:PointerEvent):void=>{if(!drag||drag.pointerId!==event.pointerId)return;if(viewport.hasPointerCapture(event.pointerId))viewport.releasePointerCapture(event.pointerId);drag=undefined;viewport.classList.remove('isScrubbing');structuralSignature='';windowSignature='';eventSignature='';schedule();};
  const keepScrollStable=():void=>{if(drag&&viewport.scrollLeft!==drag.scrollLeft)viewport.scrollLeft=drag.scrollLeft;else if(!drag)schedule();};
  const clearInspection=():void=>{if(!inspectedAnimationId&&viewOriginMs===0)return;inspectedAnimationId=undefined;viewOriginMs=0;structuralSignature='';windowSignature='';eventSignature='';schedule();};const virtualizationChanged=():void=>{windowSignature='';schedule();};
  viewport.addEventListener('click',click);viewport.addEventListener('pointerdown',down);viewport.addEventListener('pointermove',move);viewport.addEventListener('pointerup',up);viewport.addEventListener('pointercancel',up);viewport.addEventListener('scroll',keepScrollStable);window.addEventListener(TIMELINE_STATE_EVENT,liveState);window.addEventListener(ANIMATION_INSPECT_EVENT,syncInspection);window.addEventListener(ANIMATION_CLEAR_INSPECTION_EVENT,clearInspection);window.addEventListener(TIMELINE_VIRTUALIZATION_EVENT,virtualizationChanged);const unsubscribe=store.subscribe(schedule);render();
  return()=>{unsubscribe();if(raf)cancelAnimationFrame(raf);viewport.removeEventListener('click',click);viewport.removeEventListener('pointerdown',down);viewport.removeEventListener('pointermove',move);viewport.removeEventListener('pointerup',up);viewport.removeEventListener('pointercancel',up);viewport.removeEventListener('scroll',keepScrollStable);window.removeEventListener(TIMELINE_STATE_EVENT,liveState);window.removeEventListener(ANIMATION_INSPECT_EVENT,syncInspection);window.removeEventListener(ANIMATION_CLEAR_INSPECTION_EVENT,clearInspection);window.removeEventListener(TIMELINE_VIRTUALIZATION_EVENT,virtualizationChanged);viewport.remove();legacy.classList.remove('legacyTimeline');};
  function updateEvents(view:HTMLElement,pxPerMs:number,origin:number,duration:number):void{const rawLabel=getComputedStyle(view).getPropertyValue('--timeline-label-width'),parsedLabel=Number.parseFloat(rawLabel),labelWidth=Number.isFinite(parsedLabel)?parsedLabel:184,range=timelineVisibleRange(view.scrollLeft,view.clientWidth,labelWidth,{origin,duration,pxPerMs},160),stats=store.recordingStats(),visible=store.queryEvents({start:range.start,end:range.end,limit:1000}),next=`${pxPerMs}:${origin}:${duration}:${Math.round(range.start)}:${Math.round(range.end)}:${stats.version}:${windowSignature}`;if(next===eventSignature)return;eventSignature=next;const motion=view.querySelector<HTMLElement>('[data-v2-event-motion]'),count=view.querySelector<HTMLElement>('[data-v2-event-count]');if(!motion||!count)return;const clusters=clusterEvents(visible,pxPerMs);count.textContent=visible.length===stats.count?String(stats.count):`${visible.length}/${stats.count}`;motion.innerHTML=clusters.map(cluster=>{const x=Math.max(0,(cluster.at-origin)*pxPerMs),many=cluster.events.length>1,title=cluster.events.slice(0,4).map(item=>item.label).join(' · ')+(cluster.events.length>4?` · +${cluster.events.length-4}`:'');return`<i class="v2Event${many?' cluster':''}" style="left:${x}px" title="${attr(title)}">${many?cluster.events.length:''}</i>`;}).join('');}
}

function flattenRows(groups:MotionGroup[],elements:Map<string,RuntimeElement>,expanded:Set<string>,expandedDetails:Set<string>,selectedId:string|undefined,pxPerMs:number,originMs:number,heights:RowHeights):VirtualRow[]{const rows:VirtualRow[]=[];for(const group of groups){const detailOpen=expandedDetails.has(`g:${group.key}`);rows.push({key:`g:${group.key}`,height:detailOpen?heights.expanded:heights.group,html:groupRow(group,expanded,expandedDetails,selectedId,pxPerMs,originMs)});if(!expanded.has(group.key))continue;const runtime=group.instances.filter(instance=>!instance.target.elementId.startsWith('static:')),instances=runtime.length?runtime:group.instances;instances.forEach((instance,index)=>{const open=expandedDetails.has(`i:${instance.id}`);rows.push({key:`i:${instance.id}`,height:open?heights.expanded:heights.instance,html:instanceRow(instance,index,instances.length,elements,expandedDetails,selectedId,pxPerMs,originMs)});});}return rows;}
function groupRow(group:MotionGroup,expanded:Set<string>,expandedDetails:Set<string>,selectedId:string|undefined,pxPerMs:number,originMs:number):string{const runtime=group.instances.filter(instance=>!instance.target.elementId.startsWith('static:')),instances=runtime.length?runtime:group.instances,selected=group.instances.some(instance=>instance.id===selectedId),representative=instances.find(instance=>instance.id===selectedId)??instances[0]??group.representative,open=expanded.has(group.key),title=group.representative.name??humanType(group.representative.source.kind),start=Math.min(...instances.map(trackStart)),end=Math.max(...instances.map(item=>trackStart(item)+trackLength(item))),span=Math.max(1,end-start),selector=group.representative.source.reference?.selector,detail=`${humanType(group.representative.source.kind)} · ${instances.length} lane${instances.length===1?'':'s'} · ${formatTime(span)} span${selector?` · ${selector}`:''}`,detailKey=`g:${group.key}`,detailOpen=expandedDetails.has(detailKey),long=needsDisclosure(title,detail),detailToggle=long?`<button class="v2DetailToggle${detailOpen?' open':''}" data-v2-detail-toggle="${attr(detailKey)}" aria-expanded="${detailOpen}" title="${detailOpen?'Collapse details':'Expand full label'}">${detailOpen?'⌄':'›'}</button>`:'',visual=visualType(group.representative);return`<div class="v2Row v2GroupRow${selected?' selected':''}${detailOpen?' v2DetailsExpanded':''}" data-animation-type="${attr(visual)}" data-motion-source="${attr(group.representative.source.kind)}"><div class="v2Label"><button class="v2Disclosure" data-v2-toggle="${attr(group.key)}" title="${open?'Collapse lanes':'Expand into individual lanes'}">${open?'▾':'▸'}</button><span class="v2TypeDot" data-animation-type="${attr(visual)}"></span><button class="v2GroupButton" data-v2-group="${attr(representative.id)}" title="${attr(`${title} · ${detail}`)}"><span class="v2GroupTitle">${html(title)}</span><small>${html(detail)}</small></button><span class="v2LaneCount" title="${instances.length} animation lanes">${instances.length}</span>${detailToggle}<button class="v2Inspect" data-v2-inspect="${attr(representative.id)}" title="Inspect / isolate this animation">◎</button></div><div class="v2Motion">${aggregateClip(instances,representative,pxPerMs,originMs,start,end)}</div></div>`;}
function instanceRow(instance:MotionTrack,index:number,total:number,elements:Map<string,RuntimeElement>,expandedDetails:Set<string>,selectedId:string|undefined,pxPerMs:number,originMs:number):string{const name=componentName(instance,elements),properties=instance.properties.map(item=>item.name).slice(0,3).join(', ')||'motion',source=componentDetail(instance,elements),detail=`${humanType(instance.source.kind)} · ${formatTime(trackLength(instance))} · ${properties}${source?` · ${source}`:''}`,detailKey=`i:${instance.id}`,detailOpen=expandedDetails.has(detailKey),long=needsDisclosure(name,detail),detailToggle=long?`<button class="v2DetailToggle${detailOpen?' open':''}" data-v2-detail-toggle="${attr(detailKey)}" aria-expanded="${detailOpen}" title="${detailOpen?'Collapse details':'Expand full label'}">${detailOpen?'⌄':'›'}</button>`:'',visual=visualType(instance);return`<div class="v2Row v2InstanceRow${instance.id===selectedId?' selected':''}${detailOpen?' v2DetailsExpanded':''}" data-animation-type="${attr(visual)}" data-motion-source="${attr(instance.source.kind)}" data-runtime-state="${attr(instance.runtimeState)}"><div class="v2Label v2InstanceLabel"><span class="v2Branch">${index===total-1?'└':'├'}</span><span class="v2TypeDot" data-animation-type="${attr(visual)}"></span><button data-v2-instance="${attr(instance.id)}" title="${attr(`${name} · ${detail}`)}"><span>${html(name)}</span><small>${html(detail)}</small></button>${detailToggle}<button class="v2Inspect" data-v2-inspect="${attr(instance.id)}" title="Inspect / isolate this animation">◎</button></div><div class="v2Motion">${clip(instance,pxPerMs,instance.id===selectedId,'v2InstanceClip',originMs)}</div></div>`;}
function measureRowHeights(viewport:HTMLElement):RowHeights{const probe=(className:string):number=>{const node=document.createElement('div');node.className=`v2Row ${className}`;node.style.cssText='position:absolute!important;visibility:hidden!important;pointer-events:none!important;left:-100000px!important;top:0!important';node.innerHTML='<div class="v2Label"></div><div class="v2Motion"></div>';viewport.append(node);const height=Math.max(1,node.getBoundingClientRect().height);node.remove();return height;};return{group:probe('v2GroupRow'),instance:probe('v2InstanceRow'),expanded:probe('v2GroupRow v2DetailsExpanded'),ruler:probe('v2RulerRow')};}
function virtualSpacer(height:number,position:'top'|'bottom'):string{return height>0?`<div class="v2VirtualSpacer" data-v2-spacer="${position}" style="height:${Math.max(0,height)}px"></div>`:'';}
function aggregateClip(instances:MotionTrack[],representative:MotionTrack,pxPerMs:number,originMs:number,startMs:number,endMs:number):string{const left=Math.max(0,(startMs-originMs)*pxPerMs),width=Math.max(6,(endMs-startMs)*pxPerMs),count=instances.length,visual=visualType(representative);return`<button class="v2Clip v2GroupClip${instances.some(item=>item.id===representative.id)?' representative':''}" data-v2-group="${attr(representative.id)}" data-animation-type="${attr(visual)}" data-motion-source="${attr(representative.source.kind)}" style="left:${left}px;width:${width}px" title="${attr(`${count} lane${count===1?'':'s'} · ${formatTime(endMs-startMs)} total span`)}"><span class="v2ClipLabel">${count>1?`${count} lanes`:humanType(representative.source.kind)}</span></button>`;}
function clip(track:MotionTrack,pxPerMs:number,selected:boolean,className:string,originMs:number):string{const start=Math.max(0,(trackStart(track)-originMs)*pxPerMs),duration=Math.max(1,trackLength(track)*pxPerMs),label=track.name??humanType(track.source.kind),visual=visualType(track);return`<button class="v2Clip ${className}${selected?' selected':''}" data-v2-instance="${attr(track.id)}" data-animation-type="${attr(visual)}" data-motion-source="${attr(track.source.kind)}" data-runtime-state="${attr(track.runtimeState)}" style="left:${start}px;width:${Math.max(5,duration)}px" title="${attr(`${label} · ${formatTime(trackStart(track))} start · ${formatTime(trackLength(track))} duration · ${track.timing.easing??'linear'}`)}"><span class="v2ClipLabel">${html(label)}</span></button>`;}
function clusterEvents(events:TimelineEvent[],pxPerMs:number):EventCluster[]{const thresholdMs=8/Math.max(.0001,pxPerMs),sorted=[...events].sort((a,b)=>a.at-b.at),clusters:EventCluster[]=[];for(const event of sorted){const last=clusters.at(-1);if(last&&event.at-last.at<=thresholdMs){last.events.push(event);last.at=last.events.reduce((sum,item)=>sum+item.at,0)/last.events.length;}else clusters.push({at:event.at,events:[event]});}return clusters;}
function trackStart(track:MotionTrack):number{return timelineTimingStart(track.timing.start,track.timing.delay);}
function trackLength(track:MotionTrack):number{return timelineTimingDuration(track.timing.duration,track.timing.iterations);}
function componentName(track:MotionTrack,elements:Map<string,RuntimeElement>):string{const elementId=track.target.elementId,element=elements.get(elementId);if(element){if(element.domId)return`#${element.domId}`;if(element.classes.length)return`${element.tag}.${element.classes.slice(0,4).join('.')}`;return element.text?`${element.tag} · ${element.text.slice(0,48)}`:element.tag;}return track.source.reference?.selector??elementId.replace(/^static:/,'source:');}
function componentDetail(track:MotionTrack,elements:Map<string,RuntimeElement>):string{const element=elements.get(track.target.elementId);if(element){if(element.domId)return`#${element.domId}`;if(element.classes.length)return`.${element.classes.slice(0,3).join('.')}`;return element.text?.slice(0,48)??'';}const source=track.source.reference;return source?.file?`${source.file}:${source.line??'?'}${source.selector?` · ${source.selector}`:''}`:track.source.confidence;}
function visualType(track:MotionTrack):string{return track.source.kind==='waapi'?'web-animation':track.source.kind;}
function humanType(kind:MotionSourceKind):string{const labels:Record<MotionSourceKind,string>={'css-animation':'CSS animation','css-transition':'Transition',waapi:'WAAPI',javascript:'JavaScript',raf:'rAF','runtime-style':'Style write',gsap:'GSAP','framer-motion':'Framer Motion','scroll-timeline':'Scroll timeline',svg:'SVG',canvas:'Canvas',unknown:'Unknown'};return labels[kind];}
function needsDisclosure(primary:string,secondary:string):boolean{return primary.length>30||secondary.length>54||primary.length+secondary.length>72;}
function ruler(duration:number,pxPerMs:number):string{return timelineRulerMarks(duration,pxPerMs).map(time=>`<span style="left:${time*pxPerMs}px">${formatTime(time)}</span>`).join('');}
function groupSignature(group:MotionGroup):string{return`${group.key}:${group.instances.map(track=>`${track.id}:${track.timing.start}:${track.timing.duration??0}:${track.timing.delay??0}:${track.timing.iterations??1}:${track.runtimeState}:${track.source.kind}`).join(',')}`;}
function formatTime(ms:number):string{return ms>=1000?`${(ms/1000).toFixed(ms%1000===0?0:1)}s`:`${Math.round(ms)}ms`;}
function html(value:string):string{return value.replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[char]??char);}
function attr(value:string):string{return html(value);}
