import {describe,expect,it} from 'vitest';
import {createMotionProperty,filterMotionTracks,motionAdapterForAnimationType,overviewMotionTracks,type MotionTrack} from '..';
import {applyMotionCommand,commandForTrackChange} from '../../../state/history-store';

const track=(patch:Partial<MotionTrack>={}):MotionTrack=>({id:'a',name:'fade',target:{elementId:'el'},timing:{start:0,duration:300,easing:'ease'},properties:[createMotionProperty('opacity',{values:['0','1']}),createMotionProperty('display',{values:['none','block']}),createMotionProperty('transform',{values:['scale(.8)','scale(1)']})],keyframes:[{offset:0,values:{opacity:0}},{offset:1,values:{opacity:1}}],trigger:{kind:'auto'},source:{kind:'css-animation',confidence:'exact'},runtimeState:'idle',...patch});

describe('Motion IR architecture',()=>{
  it('maps source adapters without losing extended kinds',()=>{expect(motionAdapterForAnimationType('gsap').sourceKind).toBe('gsap');expect(motionAdapterForAnimationType('framer-motion').sourceKind).toBe('framer-motion');expect(motionAdapterForAnimationType('canvas').editable).toBe(false);});
  it('formalizes source triggers at the adapter boundary',()=>{expect(motionAdapterForAnimationType('scroll-timeline').defaultTrigger).toMatchObject({kind:'scroll-progress',source:'scroll-timeline'});expect(motionAdapterForAnimationType('css-animation').defaultTrigger.kind).toBe('auto');});
  it('classifies property semantics',()=>{const byName=new Map(track().properties.map(property=>[property.name,property]));expect(byName.get('opacity')).toMatchObject({valueKind:'number',interpolable:true});expect(byName.get('display')).toMatchObject({valueKind:'discrete',interpolable:false});expect(byName.get('transform')).toMatchObject({valueKind:'transform',interpolable:true});});
  it('filters and summarizes canonical tracks',()=>{const tracks=[track(),track({id:'b',source:{kind:'waapi',confidence:'runtime-observed'},trigger:{kind:'unknown'}})];expect(overviewMotionTracks(tracks)).toMatchObject({total:2,cssAnimations:1,waapi:1});expect(filterMotionTracks(tracks,'opacity','waapi').map(item=>item.id)).toEqual(['b']);});
  it('creates reversible domain commands instead of opaque snapshots',()=>{const before=track(),after:MotionTrack={...before,timing:{...before.timing,duration:700},keyframes:[...before.keyframes,{offset:.5,values:{opacity:.5}}]};const command=commandForTrackChange(before,after);expect(command?.kind).toBe('compound');const forward=command?applyMotionCommand(before,command,'forward'):before,reverse=command?applyMotionCommand(forward,command,'reverse'):forward;expect(forward.timing.duration).toBe(700);expect(forward.keyframes).toHaveLength(3);expect(reverse.timing.duration).toBe(300);expect(reverse.keyframes).toEqual(before.keyframes);});
});
