import { randomUUID } from 'node:crypto';
import { browserSnapshotRuntimeSource } from '../browser-snapshot-runtime.js';
import { recordResumeRuntimeSource } from '../record-resume-runtime.js';
import { seekRuntimeSource } from '../seek-runtime.js';
import type { BrowserEvent, BrowserSession, EmergencyCheckpoint, SnapshotAnimation, SnapshotPayload, SnapshotVisual } from './types.js';

const emergencyCheckpoints=new Map<string,EmergencyCheckpoint>();

export function clearEmergencyCheckpoint(id:string):void{emergencyCheckpoints.delete(id);}
export function rememberEmergencyCheckpoint(session:BrowserSession,message:BrowserEvent):void{const html=typeof message.html==='string'?message.html:'',url=typeof message.url==='string'?message.url:'';if(!html||!sameDocumentUrl(url,session.url))return;emergencyCheckpoints.set(session.id,{html,url,scrollX:Number(message.scrollX)||0,scrollY:Number(message.scrollY)||0,history:Array.isArray(message.history)?message.history:[],animations:Array.isArray(message.animations)?message.animations as SnapshotAnimation[]:[],visuals:[],capturedAt:Number(message.capturedAt)||Date.now()});}
export function hasValidEmergencyCheckpoint(session:BrowserSession):boolean{return !!validEmergencyCheckpoint(session);}
export function promoteEmergencyCheckpoint(session:BrowserSession):boolean{const payload=validEmergencyCheckpoint(session);if(!payload)return false;session.snapshotHtml=assembleSnapshot(payload,[]);session.snapshotStatus='ready';session.snapshotVersion++;session.snapshotError=undefined;return true;}

export async function buildBrowserSnapshot(session:BrowserSession,generation:number,visualLimit:number):Promise<string|undefined>{
  if(!captureCurrent(session,generation))return undefined;
  const visualToken='visual-'+randomUUID().replace(/-/g,''),payload=await session.page.evaluate(({token,limit}):SnapshotPayload=>{
    const host=globalThis as typeof globalThis&{__ANIMATOR_ELEMENT_ID__?:(element:Element)=>string;__ANIMATOR_VIEW_HISTORY__?:{snapshot?:()=>unknown[]}},idFor=host.__ANIMATOR_ELEMENT_ID__,marked:Array<{element:Element;previous:string|null}>=[],all=[document.documentElement,...document.documentElement.querySelectorAll('*')];
    for(const element of all){if(element.hasAttribute('data-animator-internal'))continue;const id=typeof idFor==='function'?idFor(element):element.id?`dom-${element.id}`:'';if(!id)continue;marked.push({element,previous:element.getAttribute('data-animator-capture-id')});element.setAttribute('data-animator-capture-id',id);}
    const visuals:Array<{id:string;tag:string;width:number;height:number}>=[];let visualIndex=0;
    for(const element of document.querySelectorAll('canvas,video,iframe,object,embed')){if(element.hasAttribute('data-animator-internal'))continue;const rect=element.getBoundingClientRect();if(rect.width<1||rect.height<1)continue;const id=`${token}-${++visualIndex}`;element.setAttribute('data-animator-visual-id',id);visuals.push({id,tag:element.tagName.toLowerCase(),width:rect.width,height:rect.height});if(visuals.length>=limit)break;}
    const animations:SnapshotAnimation[]=[];
    for(const animation of document.getAnimations?.()??[]){const effect=animation.effect;if(!(effect instanceof KeyframeEffect))continue;const target=effect.target;if(!(target instanceof Element)||target.hasAttribute('data-animator-internal'))continue;const elementId=typeof idFor==='function'?idFor(target):target.getAttribute('data-animator-capture-id')||'';if(!elementId)continue;let timing={} as ComputedEffectTiming,rawFrames:ComputedKeyframe[]=[];try{timing=effect.getComputedTiming();rawFrames=effect.getKeyframes();}catch{}const keyframes=rawFrames.map(frame=>{const out:Record<string,unknown>={};for(const [key,value] of Object.entries(frame))if(value!==undefined)out[key]=value===null||typeof value==='number'||typeof value==='string'?value:String(value);return out;}),object=animation as Animation&{__animatorId?:string;__animatorBrowserStartTime?:number},current=Number(animation.currentTime),rate=Math.abs(Number(animation.playbackRate))||1,id=object.__animatorId||`anim-snapshot-${animations.length+1}`,knownStart=Number(object.__animatorBrowserStartTime),iterations=Number(timing.iterations);animations.push({id,elementId,startTime:Number.isFinite(knownStart)?knownStart:Math.max(0,performance.now()-(Number.isFinite(current)?Math.max(0,current)/rate:0)),duration:Number(timing.duration)||0,delay:Number(timing.delay)||0,iterations:Number.isFinite(iterations)?iterations:'Infinity',direction:String(timing.direction||'normal'),easing:String(timing.easing||'linear'),fill:String(timing.fill||'both'),keyframes,currentTime:Number.isFinite(current)?current:null,playbackRate:Number(animation.playbackRate)||1});}
    const clone=document.documentElement.cloneNode(true) as HTMLElement;for(const item of marked){if(item.previous==null)item.element.removeAttribute('data-animator-capture-id');else item.element.setAttribute('data-animator-capture-id',item.previous);}clone.querySelectorAll('script,[data-animator-internal],[data-animator-picker-outline],[data-animator-recorded-viewport],[data-animator-recorded-cursor]').forEach(node=>node.remove());clone.querySelectorAll('meta[http-equiv]').forEach(node=>{if((node.getAttribute('http-equiv')||'').toLowerCase()==='content-security-policy')node.remove();});clone.querySelectorAll('base').forEach(node=>node.remove());return{html:'<!doctype html>'+clone.outerHTML,url:location.href,scrollX,scrollY,history:host.__ANIMATOR_VIEW_HISTORY__?.snapshot?.()??[],animations,visuals};
  },{token:visualToken,limit:visualLimit});
  if(!captureCurrent(session,generation))return undefined;const capturedVisuals:SnapshotVisual[]=[];
  try{for(const visual of payload.visuals){if(!captureCurrent(session,generation))return undefined;try{const locator=session.page.locator(`[data-animator-visual-id="${visual.id}"]`).first(),box=await locator.boundingBox();if(!box||box.width<1||box.height<1)continue;const buffer=await locator.screenshot({type:'png',animations:'allow',caret:'hide',scale:'css',timeout:850});capturedVisuals.push({...visual,dataUrl:'data:image/png;base64,'+buffer.toString('base64')});}catch{}}}
  finally{try{if(!session.browserClosed)await session.page.evaluate(ids=>{for(const id of ids)document.querySelector(`[data-animator-visual-id="${id}"]`)?.removeAttribute('data-animator-visual-id');},payload.visuals.map(visual=>visual.id));}catch{}}
  if(!captureCurrent(session,generation))return undefined;return assembleSnapshot(payload,capturedVisuals);
}

function validEmergencyCheckpoint(session:BrowserSession):EmergencyCheckpoint|undefined{const payload=emergencyCheckpoints.get(session.id);return payload&&sameDocumentUrl(payload.url,session.url)?payload:undefined;}
function captureCurrent(session:BrowserSession,generation:number):boolean{return !session.destroyed&&!session.browserClosed&&session.snapshotGeneration===generation;}
function sameDocumentUrl(left:string,right:string):boolean{try{const a=new URL(left),b=new URL(right);if(!['http:','https:'].includes(a.protocol)||!['http:','https:'].includes(b.protocol))return false;a.hash='';b.hash='';return a.href===b.href;}catch{return false;}}
function assembleSnapshot(payload:SnapshotPayload,capturedVisuals:SnapshotVisual[]):string{const base=`<base href="${escapeHtml(payload.url)}">`,freeze='<style data-animator-snapshot-freeze>*,*::before,*::after{animation:none!important;transition:none!important}</style>',seed=`<script>window.__ANIMATOR_VIEW_HISTORY_SEED__=${safeJson(payload.history)};window.__ANIMATOR_SNAPSHOT_STATE__=${safeJson({scrollX:payload.scrollX,scrollY:payload.scrollY})};window.__ANIMATOR_SNAPSHOT_ANIMATIONS__=${safeJson(payload.animations)};window.__ANIMATOR_SNAPSHOT_VISUALS__=${safeJson(capturedVisuals)};</script>`,runtimes=inlineScript(browserSnapshotRuntimeSource)+inlineScript(recordResumeRuntimeSource)+inlineScript(seekRuntimeSource);let html=payload.html.replace(/<head([^>]*)>/i,match=>match+base+freeze);if(!/<head[\s>]/i.test(html))html=html.replace(/<html([^>]*)>/i,match=>match+'<head>'+base+freeze+'</head>');return /<\/body>/i.test(html)?html.replace(/<\/body>/i,seed+runtimes+'</body>'):html.replace(/<\/html>/i,seed+runtimes+'</html>');}
function safeJson(value:unknown):string{return JSON.stringify(value).replace(/</g,'\\u003c').replace(/>/g,'\\u003e').replace(/&/g,'\\u0026');}
function inlineScript(source:string):string{return`<script>${source.replace(/<\/script/gi,'<\\/script')}</script>`;}
function escapeHtml(value:string):string{return value.replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;').replace(/>/g,'&gt;');}
