import {describe,expect,it} from 'vitest';
import type {MotionTrack} from '../../core/motion';
import {addMotionKeyframe,addMotionProperty,deleteMotionKeyframe,duplicateMotionKeyframe,motionTrackPreview,normalizedMotionKeyframes,sanitizeBezierPoints,sanitizeKeyframeOffset,sanitizeMotionDelay,sanitizeMotionDuration,sanitizeMotionIterations,selectMotionTrack,updateMotionKeyframe} from '../motion-ir-inspector';
const track:MotionTrack={id:'a',target:{elementId:'el'},timing:{start:10,duration:300,delay:20,easing:'linear'},properties:[{name:'opacity'}],keyframes:[{offset:0,values:{opacity:0}},{offset:1,values:{opacity:1}}],trigger:{kind:'unknown'},source:{kind:'waapi',confidence:'runtime-observed'},runtimeState:'running'};
describe('Motion IR inspector',()=>{
 it('selects directly from canonical tracks',()=>expect(selectMotionTrack([track],'a')).toBe(track));
 it('applies timing patches without replacing unrelated timing',()=>{const patch={timing:{duration:500,easing:'ease-in'}};expect(motionTrackPreview(track,patch)).toMatchObject({duration:500,delay:20,easing:'ease-in'});});
 it('round-trips inspector keyframes through Motion IR',()=>{const patch={keyframes:[{offset:0,values:{opacity:0}},{offset:.5,easing:'ease-out',values:{opacity:.8}},{offset:1,values:{opacity:1}}]};expect(patch.keyframes[1]).toEqual({offset:.5,easing:'ease-out',values:{opacity:.8}});expect(motionTrackPreview(track,patch).keyframes?.[1]).toEqual({offset:.5,easing:'ease-out',opacity:.8});});
 it('edits keyframes natively without leaving the canonical MotionTrack model',()=>{const frames=normalizedMotionKeyframes(track);const changed=updateMotionKeyframe(frames,0,'opacity',.25);expect(changed[0]?.values.opacity).toBe(.25);const added=addMotionKeyframe(changed);expect(added).toHaveLength(3);expect(added[1]?.offset).toBe(.5);const duplicated=duplicateMotionKeyframe(added,1);expect(duplicated).toHaveLength(4);expect(deleteMotionKeyframe(duplicated,1)).toHaveLength(3);});
 it('adds new animated properties to MotionKeyframe values only',()=>{const frames=addMotionProperty(normalizedMotionKeyframes(track),'transform');expect(frames.every(frame=>frame.values.transform==='')).toBe(true);expect(Object.prototype.hasOwnProperty.call(frames[0]??{},'transform')).toBe(false);});
 it('rejects invalid timing values before they reach the runtime',()=>{expect(sanitizeMotionDuration(-20,300)).toBe(300);expect(sanitizeMotionDuration('',300)).toBe(300);expect(sanitizeMotionDuration(0,300)).toBe(300);expect(sanitizeMotionDuration(180,300)).toBe(180);expect(sanitizeMotionIterations(0,2)).toBe(2);expect(sanitizeMotionIterations(-4,2)).toBe(2);expect(sanitizeMotionDelay('bad',20)).toBe(20);expect(sanitizeMotionDelay(-50,20)).toBe(-50);});
 it('clamps offsets and cubic-bezier x coordinates to valid domains',()=>{expect(sanitizeKeyframeOffset(-1,.5)).toBe(0);expect(sanitizeKeyframeOffset(2,.5)).toBe(1);expect(sanitizeKeyframeOffset('bad',.5)).toBe(.5);expect(sanitizeBezierPoints([-2,-.5,3,1.5])).toEqual([0,-.5,1,1.5]);expect(sanitizeBezierPoints([0,'bad',1,1])).toBeUndefined();});
});