import './app/styles.css';
import './app/extras.css';
import './app/ui-polish.css';
import './app/timeline-v2.css';
import './app/timeline-labels.css';
import './app/preview-camera.css';
import './app/preview-theme.css';
import './app/record-view-history.css';
import './app/browser-preview.css';
import './app/browser-runtime.css';
import './app/motion-catalog.css';
import './app/editor-pro.css';
import { mountApp } from './app/app';
import { mountEditorExtras } from './app/extras';
import { mountUiPolish } from './app/ui-polish';
import { mountTimelineV2 } from './app/timeline-v2';
import { mountTimelineLabelFit } from './app/timeline-label-fit';
import { mountPreviewOrigin } from './app/preview-origin';
import { mountPreviewEditor } from './app/preview-editor';
import { mountPreviewCamera } from './app/preview-camera';
import { mountPreviewTheme } from './app/preview-theme';
import { mountRecordViewHistory } from './app/record-view-history';
import { mountBrowserPreview } from './app/browser-preview';
import { mountMotionCatalog } from './app/motion-catalog';
import { mountRemoteOpen } from './app/remote-open';
import { mountTimelineTools } from './app/timeline-tools';
import { mountLoadTimeline } from './app/load-timeline';
import { mountDomLoadTree } from './app/dom-load-tree';
import { mountControlSync } from './app/control-sync';
import { installPreviewNavigationGate, mountRecordGate } from './app/record-gate';

const root=document.querySelector<HTMLElement>('#root');
if(!root)throw new Error('Animator root element not found');

const cleanupNavigationGate=installPreviewNavigationGate();
const cleanupApp=mountApp(root);
const cleanupControlSync=mountControlSync();
const cleanupRecordGate=mountRecordGate(root);
const cleanupRecordViewHistory=mountRecordViewHistory(root);
const cleanupExtras=mountEditorExtras(root);
const cleanupPolish=mountUiPolish(root);
const cleanupTimeline=mountTimelineV2(root);
const cleanupTimelineLabels=mountTimelineLabelFit(root);
const cleanupPreviewOrigin=mountPreviewOrigin(root);
const cleanupPreviewEditor=mountPreviewEditor(root);
const cleanupMotionCatalog=mountMotionCatalog(root);
const cleanupRemoteOpen=mountRemoteOpen(root);
const cleanupTimelineTools=mountTimelineTools(root);
const cleanupBrowserPreview=mountBrowserPreview(root);
const cleanupPreviewCamera=mountPreviewCamera(root);
const cleanupPreviewTheme=mountPreviewTheme(root);
const cleanupLoadTimeline=mountLoadTimeline(root);
const cleanupDomLoadTree=mountDomLoadTree(root);
const cleanup=():void=>{cleanupDomLoadTree();cleanupLoadTimeline();cleanupPreviewTheme();cleanupPreviewCamera();cleanupBrowserPreview();cleanupTimelineTools();cleanupRemoteOpen();cleanupMotionCatalog();cleanupPreviewEditor();cleanupPreviewOrigin();cleanupTimelineLabels();cleanupTimeline();cleanupPolish();cleanupExtras();cleanupRecordViewHistory();cleanupRecordGate();cleanupControlSync();cleanupApp();cleanupNavigationGate();};

if(import.meta.hot)import.meta.hot.dispose(cleanup);
